------------------------------------------------------------------------------------------------------------------------------------------
--                                                   DATABASE TABLE UPDATE SCRIPT (SQLSERVER)                                              --
------------------------------------------------------------------------------------------------------------------------------------------
-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCEOID column to PROCESSUNITOID
IF COL_LENGTH('OBJT_PROCESSAGGREGATION','PROCESSUNITOID') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJT_PROCESSAGGREGATION.PROCESSRESOURCEOID','PROCESSUNITOID', 'COLUMN';
     COMMIT
  END;
GO

-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATE column to PROCESSUNITSTATE
IF COL_LENGTH('OBJT_PROCESSAGGREGATION','PROCESSUNITSTATE') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATE','PROCESSUNITSTATE', 'COLUMN';
     COMMIT
  END;
GO

-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATEDURATION column to PROCESSUNITSTATEDURATION
IF COL_LENGTH('OBJT_PROCESSAGGREGATION','PROCESSUNITSTATEDURATION') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATEDURATION','PROCESSUNITSTATEDURATION', 'COLUMN';
     COMMIT
  END;
GO

-- Rename OBJT_UOMCONVERSION.OFFSET column to OFFSETVALUE
IF COL_LENGTH('OBJT_UOMCONVERSION','OFFSETVALUE') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJT_UOMCONVERSION.OFFSET','OFFSETVALUE', 'COLUMN';
     COMMIT
  END;
GO

-- Rename OBJT_ATTENDANCEPATTERNLINK.OFFSET column to OFFSETVALUE
IF COL_LENGTH('OBJT_ATTENDANCEPATTERNLINK','OFFSETVALUE') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJT_ATTENDANCEPATTERNLINK.OFFSET','OFFSETVALUE', 'COLUMN';
     COMMIT
  END;
GO

-- Rename OBJTBU_BALANCINGCONFIG.OFFSET column to OFFSETVALUE
IF COL_LENGTH('OBJTBU_BALANCINGCONFIG','OFFSETVALUE') IS NULL
  BEGIN
    BEGIN TRANSACTION
      exec sp_rename 'OBJTBU_BALANCINGCONFIG.OFFSET','OFFSETVALUE', 'COLUMN';
     COMMIT
  END;
GO