BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CAPACITYALLOCATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CAPACITYALLOCATIONS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  PLANNINGCELL_OID     NUMBER(19),
  DTS                  DATE,
  SKILL_OID            NUMBER(19),
  SKILL_LEVEL          NUMBER(10),
  SHIFT_TYPE_OID       NUMBER(19),
  SHIFT_DTSSTART       DATE,
  SHIFT_DTSSTOP        DATE,
  QTY_ALLOCATED        NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_CAPACITYALLOCATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_CAPACITYALLCTNS_MPLY_D ON DCEREPORT_CAPACITYALLOCATIONS(EMPLOYEE_OID)
/

CREATE INDEX IREPRT_CPCTYLLCTNS_PLNNNGCLL_D ON DCEREPORT_CAPACITYALLOCATIONS(PLANNINGCELL_OID)
/

CREATE INDEX IREPORT_CAPACITYALLCTNS_SKLL_D ON DCEREPORT_CAPACITYALLOCATIONS(SKILL_OID)
/

CREATE INDEX IREPORT_CPCTYLLCTNS_SHFT_TYP_D ON DCEREPORT_CAPACITYALLOCATIONS(SHIFT_TYPE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CAPALLOC_ANOMALIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CAPALLOC_ANOMALIES
(
  OID                  NUMBER(19) NOT NULL,
  CAPACITY_ALLOCATION_OID NUMBER(19),
  CAP_ANOMALY_REASON_OID NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_CAPALLOC_ANOMALIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRPRT_CPLLC_NMLS_CPCTY_LLCTN_D ON DCEREPORT_CAPALLOC_ANOMALIES(CAPACITY_ALLOCATION_OID)
/

CREATE INDEX IRPRT_CPLLC_NMLS_CP_NMLY_RSN_D ON DCEREPORT_CAPALLOC_ANOMALIES(CAP_ANOMALY_REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFTCAPREQUIREMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFTCAPREQUIREMENTS
(
  OID                  NUMBER(19) NOT NULL,
  PLANNINGCELL_OID     NUMBER(19),
  DTS                  DATE,
  SKILL_OID            NUMBER(19),
  SKILL_LEVEL          NUMBER(10),
  SHIFT_TYPE_OID       NUMBER(19),
  SHIFT_DTSSTART       DATE,
  SHIFT_DTSSTOP        DATE,
  QTYREQUIRED          NUMBER,
  QTYALLOCATED         NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_SHIFTCAPREQUIREMENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IPRT_SHFTCPRQRMNTS_PLNNNGCLL_D ON DCEREPORT_SHIFTCAPREQUIREMENTS(PLANNINGCELL_OID)
/

CREATE INDEX IREPORT_SHIFTCAPRQRMNTS_SKLL_D ON DCEREPORT_SHIFTCAPREQUIREMENTS(SKILL_OID)
/

CREATE INDEX IRPRT_SHFTCPRQRMNTS_SHFT_TYP_D ON DCEREPORT_SHIFTCAPREQUIREMENTS(SHIFT_TYPE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES
(
  OID                  NUMBER(19) NOT NULL,
  SHIFT_CAPREQUIREMENT_OID NUMBER(19),
  CAP_ANOMALY_REASON_OID NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_SHFTCAPREQ_ANOMALIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX ISHFTCPRQ_NMLS_SHFT_CPRQRMNT_D ON DCEREPORT_SHFTCAPREQ_ANOMALIES(SHIFT_CAPREQUIREMENT_OID)
/

CREATE INDEX IT_SHFTCPRQ_NMLS_CP_NMLY_RSN_D ON DCEREPORT_SHFTCAPREQ_ANOMALIES(CAP_ANOMALY_REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFT_CAPREQ_LINK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFT_CAPREQ_LINK
(
  OID                  NUMBER(19) NOT NULL,
  CAPACITYREQUIREMENT_OID NUMBER(19),
  SHIFT_CAPREQUIREMENT_OID NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SHIFT_CAPREQ_LINK
  PRIMARY KEY (OID)
)
/

CREATE INDEX IT_SHFT_CPRQ_LNK_CPCTYRQRMNT_D ON DCEREPORT_SHIFT_CAPREQ_LINK(CAPACITYREQUIREMENT_OID)
/

CREATE INDEX ISHFT_CPRQ_LNK_SHFT_CPRQRMNT_D ON DCEREPORT_SHIFT_CAPREQ_LINK(SHIFT_CAPREQUIREMENT_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CAPREQUIREMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CAPREQUIREMENTS
(
  OID                  NUMBER(19) NOT NULL,
  PLANNINGCELL_OID     NUMBER(19),
  SKILL_OID            NUMBER(19),
  SKILL_LEVEL          NUMBER(10),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  QTYREQUIRED          NUMBER,
  PROCESSRESOURCE_OID  NUMBER(19),
  REFERENCE_OID        NUMBER(19),
  TYPE                 VARCHAR2(16 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_CAPREQUIREMENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_CAPRQRMNTS_PLNNNGCLL_D ON DCEREPORT_CAPREQUIREMENTS(PLANNINGCELL_OID)
/

CREATE INDEX IREPORT_CAPREQUIREMENTS_SKLL_D ON DCEREPORT_CAPREQUIREMENTS(SKILL_OID)
/

CREATE INDEX IREPORT_CAPRQRMNTS_PRCSSRSRC_D ON DCEREPORT_CAPREQUIREMENTS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_CAPREQUIREMNTS_RFRNC_D ON DCEREPORT_CAPREQUIREMENTS(REFERENCE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFT_CAPACITIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFT_CAPACITIES
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DTS                  DATE,
  SHIFT_TYPE_OID       NUMBER(19),
  SHIFT_DTSSTART       DATE,
  SHIFT_DTSSTOP        DATE,
  QTYAVAILABLE         NUMBER,
  QTYREMAINING         NUMBER,
  QTYALLOCATED         NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SHIFT_CAPACITIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_SHIFT_CAPACITIS_MPLY_D ON DCEREPORT_SHIFT_CAPACITIES(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_SHIFT_CPCTS_SHFT_TYP_D ON DCEREPORT_SHIFT_CAPACITIES(SHIFT_TYPE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFT_CAP_ANOMALIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFT_CAP_ANOMALIES
(
  OID                  NUMBER(19) NOT NULL,
  SHIFT_CAPREQUIREMENT_OID NUMBER(19),
  CAP_ANOMALY_REASON_OID NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_SHIFT_CAP_ANOMALIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX I_SHFT_CP_NMLS_SHFT_CPRQRMNT_D ON DCEREPORT_SHIFT_CAP_ANOMALIES(SHIFT_CAPREQUIREMENT_OID)
/

CREATE INDEX IRT_SHFT_CP_NMLS_CP_NMLY_RSN_D ON DCEREPORT_SHIFT_CAP_ANOMALIES(CAP_ANOMALY_REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFT_CAP_LINK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFT_CAP_LINK
(
  OID                  NUMBER(19) NOT NULL,
  SHIFT_CAPACITY_OID   NUMBER(19),
  CAPACITY_OID         NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SHIFT_CAP_LINK
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRPRT_SHFT_CP_LNK_SHFT_CPCTY_D ON DCEREPORT_SHIFT_CAP_LINK(SHIFT_CAPACITY_OID)
/

CREATE INDEX IREPORT_SHIFT_CAP_LINK_CPCTY_D ON DCEREPORT_SHIFT_CAP_LINK(CAPACITY_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CAPACITIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CAPACITIES
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  REFERENCE_OID        NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_CAPACITIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_CAPACITIES_EMPLOYEE_OD ON DCEREPORT_CAPACITIES(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_CAPACITIES_REFERENCE_D ON DCEREPORT_CAPACITIES(REFERENCE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CAP_ANOMALY_REASONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CAP_ANOMALY_REASONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  TYPE                 VARCHAR2(7 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_CAP_ANOMALY_REASONS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PLANNINGCELLS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PLANNINGCELLS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  COSTCENTER_OID       NUMBER(19),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_PLANNINGCELLS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_PLANNINGCLLS_CSTCNTR_D ON DCEREPORT_PLANNINGCELLS(COSTCENTER_OID)
/

