BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_REPORT_CAPACTYLLCTNS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS ADD CONSTRAINT FK_REPORT_CAPACTYLLCTNS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT F_RPRT_CPCTYLLCTNS_PLNNNGCLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS ADD CONSTRAINT F_RPRT_CPCTYLLCTNS_PLNNNGCLL_D FOREIGN KEY (PLANNINGCELL_OID) REFERENCES DCEREPORT_PLANNINGCELLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_RPRT_CPCTYLLCTNS_SHFT_TYP_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS ADD CONSTRAINT FK_RPRT_CPCTYLLCTNS_SHFT_TYP_D FOREIGN KEY (SHIFT_TYPE_OID) REFERENCES DCEREPORT_SHIFT_TYPES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_REPORT_CAPACTYLLCTNS_SKLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS ADD CONSTRAINT FK_REPORT_CAPACTYLLCTNS_SKLL_D FOREIGN KEY (SKILL_OID) REFERENCES DCEREPORT_SKILLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES DROP CONSTRAINT FRPRT_CPLLC_NMLS_CP_NMLY_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES ADD CONSTRAINT FRPRT_CPLLC_NMLS_CP_NMLY_RSN_D FOREIGN KEY (CAP_ANOMALY_REASON_OID) REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES DROP CONSTRAINT FRPRT_CPLLC_NMLS_CPCTY_LLCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES ADD CONSTRAINT FRPRT_CPLLC_NMLS_CPCTY_LLCTN_D FOREIGN KEY (CAPACITY_ALLOCATION_OID) REFERENCES DCEREPORT_CAPACITYALLOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FPRT_SHFTCPRQRMNTS_PLNNNGCLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS ADD CONSTRAINT FPRT_SHFTCPRQRMNTS_PLNNNGCLL_D FOREIGN KEY (PLANNINGCELL_OID) REFERENCES DCEREPORT_PLANNINGCELLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FRPRT_SHFTCPRQRMNTS_SHFT_TYP_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS ADD CONSTRAINT FRPRT_SHFTCPRQRMNTS_SHFT_TYP_D FOREIGN KEY (SHIFT_TYPE_OID) REFERENCES DCEREPORT_SHIFT_TYPES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FK_REPORT_SHFTCPRQRMNTS_SKLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS ADD CONSTRAINT FK_REPORT_SHFTCPRQRMNTS_SKLL_D FOREIGN KEY (SKILL_OID) REFERENCES DCEREPORT_SKILLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES DROP CONSTRAINT FT_SHFTCPRQ_NMLS_CP_NMLY_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES ADD CONSTRAINT FT_SHFTCPRQ_NMLS_CP_NMLY_RSN_D FOREIGN KEY (CAP_ANOMALY_REASON_OID) REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES DROP CONSTRAINT FSHFTCPRQ_NMLS_SHFT_CPRQRMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES ADD CONSTRAINT FSHFTCPRQ_NMLS_SHFT_CPRQRMNT_D FOREIGN KEY (SHIFT_CAPREQUIREMENT_OID) REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK DROP CONSTRAINT FT_SHFT_CPRQ_LNK_CPCTYRQRMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK ADD CONSTRAINT FT_SHFT_CPRQ_LNK_CPCTYRQRMNT_D FOREIGN KEY (CAPACITYREQUIREMENT_OID) REFERENCES DCEREPORT_CAPREQUIREMENTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK DROP CONSTRAINT FSHFT_CPRQ_LNK_SHFT_CPRQRMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK ADD CONSTRAINT FSHFT_CPRQ_LNK_SHFT_CPRQRMNT_D FOREIGN KEY (SHIFT_CAPREQUIREMENT_OID) REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_REPRT_CPRQRMNTS_PLNNNGCLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPREQUIREMENTS ADD CONSTRAINT FK_REPRT_CPRQRMNTS_PLNNNGCLL_D FOREIGN KEY (PLANNINGCELL_OID) REFERENCES DCEREPORT_PLANNINGCELLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_REPRT_CPRQRMNTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPREQUIREMENTS ADD CONSTRAINT FK_REPRT_CPRQRMNTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_REPORT_CAPREQUIRMNTS_SKLL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPREQUIREMENTS ADD CONSTRAINT FK_REPORT_CAPREQUIRMNTS_SKLL_D FOREIGN KEY (SKILL_OID) REFERENCES DCEREPORT_SKILLS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAPACITIES DROP CONSTRAINT FK_REPORT_SHIFT_CAPACTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAPACITIES ADD CONSTRAINT FK_REPORT_SHIFT_CAPACTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAPACITIES DROP CONSTRAINT FK_REPRT_SHFT_CPCTS_SHFT_TYP_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAPACITIES ADD CONSTRAINT FK_REPRT_SHFT_CPCTS_SHFT_TYP_D FOREIGN KEY (SHIFT_TYPE_OID) REFERENCES DCEREPORT_SHIFT_TYPES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES DROP CONSTRAINT FRT_SHFT_CP_NMLS_CP_NMLY_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES ADD CONSTRAINT FRT_SHFT_CP_NMLS_CP_NMLY_RSN_D FOREIGN KEY (CAP_ANOMALY_REASON_OID) REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES DROP CONSTRAINT F_SHFT_CP_NMLS_SHFT_CPRQRMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES ADD CONSTRAINT F_SHFT_CP_NMLS_SHFT_CPRQRMNT_D FOREIGN KEY (SHIFT_CAPREQUIREMENT_OID) REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAP_LINK DROP CONSTRAINT FK_REPORT_SHIFT_CP_LNK_CPCTY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAP_LINK ADD CONSTRAINT FK_REPORT_SHIFT_CP_LNK_CPCTY_D FOREIGN KEY (CAPACITY_OID) REFERENCES DCEREPORT_CAPACITIES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIFT_CAP_LINK DROP CONSTRAINT FRPRT_SHFT_CP_LNK_SHFT_CPCTY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIFT_CAP_LINK ADD CONSTRAINT FRPRT_SHFT_CP_LNK_SHFT_CPCTY_D FOREIGN KEY (SHIFT_CAPACITY_OID) REFERENCES DCEREPORT_SHIFT_CAPACITIES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CAPACITIES DROP CONSTRAINT FK_REPORT_CAPACITIES_EMPLOYE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CAPACITIES ADD CONSTRAINT FK_REPORT_CAPACITIES_EMPLOYE_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PLANNINGCELLS DROP CONSTRAINT FK_REPORT_PLNNNGCLLS_CSTCNTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PLANNINGCELLS ADD CONSTRAINT FK_REPORT_PLNNNGCLLS_CSTCNTR_D FOREIGN KEY (COSTCENTER_OID) REFERENCES DCEREPORT_COSTCENTERS(OID) DISABLE NOVALIDATE
/

