BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_TOOLS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_TOOLS
(
  OID                  NUMBER(19) NOT NULL,
  UOM_OID              NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  UOM                  VARCHAR2(32 CHAR),
  ID                   VARCHAR2(32 CHAR),
  CATEGORY             VARCHAR2(64 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_TOOLS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IDCEREPORT_TOOLS_UOM_OID ON DCEREPORT_TOOLS(UOM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_EQUIPMENTMODULES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_EQUIPMENTMODULES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  CATEGORY             VARCHAR2(64 CHAR),
  PROCESSRESOURCE_OID  NUMBER(19),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_EQUIPMENTMODULES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_EQPMNTMDLS_PRCSSRSRC_D ON DCEREPORT_EQUIPMENTMODULES(PROCESSRESOURCE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_RESOURCETRAINS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_RESOURCETRAINS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_RESOURCETRAINS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_RESOURCETRAIN_RESRCS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_RESOURCETRAIN_RESRCS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  PROCESSRESOURCE_OID  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_NAME VARCHAR2(64 CHAR),
  PROCESSRESOURCE_DESCRIPTION VARCHAR2(255 CHAR),
  PROCESSRESOURCE_TYPE VARCHAR2(10 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_RESOURCETRAIN_RESRCS
  PRIMARY KEY (OID, PROCESSRESOURCE_OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DEPARTMENT_CHILDDEP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DEPARTMENT_CHILDDEP
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  CHILDDEPARTMENT_OID  NUMBER(19) NOT NULL,
  CHILDDEPARTMENT_NAME VARCHAR2(64 CHAR),
  CHILDDEPARTMENT_DESCRIPTION VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_DEPARTMENT_CHILDDEP
  PRIMARY KEY (OID, CHILDDEPARTMENT_OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DEPARTMENT_RESRCS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DEPARTMENT_RESRCS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  PROCESSRESOURCE_OID  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_NAME VARCHAR2(64 CHAR),
  PROCESSRESOURCE_DESCRIPTION VARCHAR2(255 CHAR),
  PROCESSRESOURCE_TYPE VARCHAR2(10 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DEPARTMENT_RESRCS
  PRIMARY KEY (OID, PROCESSRESOURCE_OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PRODUCTIONOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PRODUCTIONOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  PRODUCTIONORDER_OID  NUMBER(19),
  DTSPLANNEDSTART      DATE,
  DTSPLANNEDSTOP       DATE,
  DTSSCHEDULEDSTART    DATE,
  DTSSCHEDULEDSTOP     DATE,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  PROCESSRESOURCE_OID  NUMBER(19),
  ITEM_OID             NUMBER(19),
  QTYPLANNED           NUMBER,
  QTYFACTOR            NUMBER,
  QTYUNIT              NUMBER,
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRDTS6              DATE,
  USRDTS7              DATE,
  USRDTS8              DATE,
  USRDTS9              DATE,
  USRDTS10             DATE,
  USRDTS11             DATE,
  USRDTS12             DATE,
  USRDTS13             DATE,
  USRDTS14             DATE,
  USRDTS15             DATE,
  USRDTS16             DATE,
  USRDTS17             DATE,
  USRDTS18             DATE,
  USRDTS19             DATE,
  USRDTS20             DATE,
  USRDTS21             DATE,
  USRDTS22             DATE,
  USRDTS23             DATE,
  USRDTS24             DATE,
  USRDTS25             DATE,
  USRDTS26             DATE,
  USRDTS27             DATE,
  USRDTS28             DATE,
  USRDTS29             DATE,
  USRDTS30             DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRFLG6              CHAR(1),
  USRFLG7              CHAR(1),
  USRFLG8              CHAR(1),
  USRFLG9              CHAR(1),
  USRFLG10             CHAR(1),
  USRFLG11             CHAR(1),
  USRFLG12             CHAR(1),
  USRFLG13             CHAR(1),
  USRFLG14             CHAR(1),
  USRFLG15             CHAR(1),
  USRFLG16             CHAR(1),
  USRFLG17             CHAR(1),
  USRFLG18             CHAR(1),
  USRFLG19             CHAR(1),
  USRFLG20             CHAR(1),
  USRFLG21             CHAR(1),
  USRFLG22             CHAR(1),
  USRFLG23             CHAR(1),
  USRFLG24             CHAR(1),
  USRFLG25             CHAR(1),
  USRFLG26             CHAR(1),
  USRFLG27             CHAR(1),
  USRFLG28             CHAR(1),
  USRFLG29             CHAR(1),
  USRFLG30             CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRNUM6              NUMBER,
  USRNUM7              NUMBER,
  USRNUM8              NUMBER,
  USRNUM9              NUMBER,
  USRNUM10             NUMBER,
  USRNUM11             NUMBER,
  USRNUM12             NUMBER,
  USRNUM13             NUMBER,
  USRNUM14             NUMBER,
  USRNUM15             NUMBER,
  USRNUM16             NUMBER,
  USRNUM17             NUMBER,
  USRNUM18             NUMBER,
  USRNUM19             NUMBER,
  USRNUM20             NUMBER,
  USRNUM21             NUMBER,
  USRNUM22             NUMBER,
  USRNUM23             NUMBER,
  USRNUM24             NUMBER,
  USRNUM25             NUMBER,
  USRNUM26             NUMBER,
  USRNUM27             NUMBER,
  USRNUM28             NUMBER,
  USRNUM29             NUMBER,
  USRNUM30             NUMBER,
  USRNUM31             NUMBER,
  USRNUM32             NUMBER,
  USRNUM33             NUMBER,
  USRNUM34             NUMBER,
  USRNUM35             NUMBER,
  USRNUM36             NUMBER,
  USRNUM37             NUMBER,
  USRNUM38             NUMBER,
  USRNUM39             NUMBER,
  USRNUM40             NUMBER,
  USRNUM41             NUMBER,
  USRNUM42             NUMBER,
  USRNUM43             NUMBER,
  USRNUM44             NUMBER,
  USRNUM45             NUMBER,
  USRNUM46             NUMBER,
  USRNUM47             NUMBER,
  USRNUM48             NUMBER,
  USRNUM49             NUMBER,
  USRNUM50             NUMBER,
  USRNUM51             NUMBER,
  USRNUM52             NUMBER,
  USRNUM53             NUMBER,
  USRNUM54             NUMBER,
  USRNUM55             NUMBER,
  USRNUM56             NUMBER,
  USRNUM57             NUMBER,
  USRNUM58             NUMBER,
  USRNUM59             NUMBER,
  USRNUM60             NUMBER,
  USRNUM61             NUMBER,
  USRNUM62             NUMBER,
  USRNUM63             NUMBER,
  USRNUM64             NUMBER,
  USRNUM65             NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  USRTXT6              VARCHAR2(255 CHAR),
  USRTXT7              VARCHAR2(255 CHAR),
  USRTXT8              VARCHAR2(255 CHAR),
  USRTXT9              VARCHAR2(255 CHAR),
  USRTXT10             VARCHAR2(255 CHAR),
  USRTXT11             VARCHAR2(255 CHAR),
  USRTXT12             VARCHAR2(255 CHAR),
  USRTXT13             VARCHAR2(255 CHAR),
  USRTXT14             VARCHAR2(255 CHAR),
  USRTXT15             VARCHAR2(255 CHAR),
  USRTXT16             VARCHAR2(255 CHAR),
  USRTXT17             VARCHAR2(255 CHAR),
  USRTXT18             VARCHAR2(255 CHAR),
  USRTXT19             VARCHAR2(255 CHAR),
  USRTXT20             VARCHAR2(255 CHAR),
  USRTXT21             VARCHAR2(255 CHAR),
  USRTXT22             VARCHAR2(255 CHAR),
  USRTXT23             VARCHAR2(255 CHAR),
  USRTXT24             VARCHAR2(255 CHAR),
  USRTXT25             VARCHAR2(255 CHAR),
  USRTXT26             VARCHAR2(255 CHAR),
  USRTXT27             VARCHAR2(255 CHAR),
  USRTXT28             VARCHAR2(255 CHAR),
  USRTXT29             VARCHAR2(255 CHAR),
  USRTXT30             VARCHAR2(255 CHAR),
  USRTXT31             VARCHAR2(255 CHAR),
  USRTXT32             VARCHAR2(255 CHAR),
  USRTXT33             VARCHAR2(255 CHAR),
  USRTXT34             VARCHAR2(255 CHAR),
  USRTXT35             VARCHAR2(255 CHAR),
  USRTXT36             VARCHAR2(255 CHAR),
  USRTXT37             VARCHAR2(255 CHAR),
  USRTXT38             VARCHAR2(255 CHAR),
  USRTXT39             VARCHAR2(255 CHAR),
  USRTXT40             VARCHAR2(255 CHAR),
  USRTXT41             VARCHAR2(255 CHAR),
  USRTXT42             VARCHAR2(255 CHAR),
  USRTXT43             VARCHAR2(255 CHAR),
  USRTXT44             VARCHAR2(255 CHAR),
  USRTXT45             VARCHAR2(255 CHAR),
  USRTXT46             VARCHAR2(255 CHAR),
  USRTXT47             VARCHAR2(255 CHAR),
  USRTXT48             VARCHAR2(255 CHAR),
  USRTXT49             VARCHAR2(255 CHAR),
  USRTXT50             VARCHAR2(255 CHAR),
  USRTXT51             VARCHAR2(255 CHAR),
  USRTXT52             VARCHAR2(255 CHAR),
  USRTXT53             VARCHAR2(255 CHAR),
  USRTXT54             VARCHAR2(255 CHAR),
  USRTXT55             VARCHAR2(255 CHAR),
  USRTXT56             VARCHAR2(255 CHAR),
  USRTXT57             VARCHAR2(255 CHAR),
  USRTXT58             VARCHAR2(255 CHAR),
  USRTXT59             VARCHAR2(255 CHAR),
  USRTXT60             VARCHAR2(255 CHAR),
  USRTXT61             VARCHAR2(255 CHAR),
  USRTXT62             VARCHAR2(255 CHAR),
  USRTXT63             VARCHAR2(255 CHAR),
  USRTXT64             VARCHAR2(255 CHAR),
  USRTXT65             VARCHAR2(255 CHAR),
  CONSTRAINT PK_REPORT_PRODUCTIONOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPRT_PRDCTNPRTNS_PRDCTNRDR_D ON DCEREPORT_PRODUCTIONOPERATIONS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPRT_PRDCTNPRTNS_PRCSSRSRC_D ON DCEREPORT_PRODUCTIONOPERATIONS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_PRODUCTIONOPERTNS_TM_D ON DCEREPORT_PRODUCTIONOPERATIONS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PRODUCTIONOP_QTIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PRODUCTIONOP_QTIES
(
  OID                  NUMBER(19) NOT NULL,
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  ITEM_OID             NUMBER(19),
  TYPE                 VARCHAR2(16 CHAR),
  QTYPLANNED           NUMBER,
  QTYFACTOR            NUMBER,
  QTYUNIT              NUMBER,
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_PRODUCTIONOP_QTIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRPRT_PRDCTNP_QTS_PRDCTNPRTN_D ON DCEREPORT_PRODUCTIONOP_QTIES(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPRT_PRDCTNP_QTS_PRDCTNRDR_D ON DCEREPORT_PRODUCTIONOP_QTIES(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_PRODUCTIONOP_QTIS_TM_D ON DCEREPORT_PRODUCTIONOP_QTIES(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PRODUCTIONORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PRODUCTIONORDERS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  ID                   VARCHAR2(32 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSPLANNEDSTART      DATE,
  DTSPLANNEDSTOP       DATE,
  DTSSCHEDULEDSTART    DATE,
  DTSSCHEDULEDSTOP     DATE,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  DTSDUEBEFORE         DATE,
  ITEM_OID             NUMBER(19),
  CUSTOMER_OID         NUMBER(19),
  RECIPE_OID           NUMBER(19),
  RECIPE_NAME          VARCHAR2(64 CHAR),
  RECIPE_VARIANT       VARCHAR2(64 CHAR),
  RECIPE_VERSION       NUMBER(19),
  QTYPLANNED           NUMBER,
  QTYYIELD             NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRDTS6              DATE,
  USRDTS7              DATE,
  USRDTS8              DATE,
  USRDTS9              DATE,
  USRDTS10             DATE,
  USRDTS11             DATE,
  USRDTS12             DATE,
  USRDTS13             DATE,
  USRDTS14             DATE,
  USRDTS15             DATE,
  USRDTS16             DATE,
  USRDTS17             DATE,
  USRDTS18             DATE,
  USRDTS19             DATE,
  USRDTS20             DATE,
  USRDTS21             DATE,
  USRDTS22             DATE,
  USRDTS23             DATE,
  USRDTS24             DATE,
  USRDTS25             DATE,
  USRDTS26             DATE,
  USRDTS27             DATE,
  USRDTS28             DATE,
  USRDTS29             DATE,
  USRDTS30             DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRFLG6              CHAR(1),
  USRFLG7              CHAR(1),
  USRFLG8              CHAR(1),
  USRFLG9              CHAR(1),
  USRFLG10             CHAR(1),
  USRFLG11             CHAR(1),
  USRFLG12             CHAR(1),
  USRFLG13             CHAR(1),
  USRFLG14             CHAR(1),
  USRFLG15             CHAR(1),
  USRFLG16             CHAR(1),
  USRFLG17             CHAR(1),
  USRFLG18             CHAR(1),
  USRFLG19             CHAR(1),
  USRFLG20             CHAR(1),
  USRFLG21             CHAR(1),
  USRFLG22             CHAR(1),
  USRFLG23             CHAR(1),
  USRFLG24             CHAR(1),
  USRFLG25             CHAR(1),
  USRFLG26             CHAR(1),
  USRFLG27             CHAR(1),
  USRFLG28             CHAR(1),
  USRFLG29             CHAR(1),
  USRFLG30             CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRNUM6              NUMBER,
  USRNUM7              NUMBER,
  USRNUM8              NUMBER,
  USRNUM9              NUMBER,
  USRNUM10             NUMBER,
  USRNUM11             NUMBER,
  USRNUM12             NUMBER,
  USRNUM13             NUMBER,
  USRNUM14             NUMBER,
  USRNUM15             NUMBER,
  USRNUM16             NUMBER,
  USRNUM17             NUMBER,
  USRNUM18             NUMBER,
  USRNUM19             NUMBER,
  USRNUM20             NUMBER,
  USRNUM21             NUMBER,
  USRNUM22             NUMBER,
  USRNUM23             NUMBER,
  USRNUM24             NUMBER,
  USRNUM25             NUMBER,
  USRNUM26             NUMBER,
  USRNUM27             NUMBER,
  USRNUM28             NUMBER,
  USRNUM29             NUMBER,
  USRNUM30             NUMBER,
  USRNUM31             NUMBER,
  USRNUM32             NUMBER,
  USRNUM33             NUMBER,
  USRNUM34             NUMBER,
  USRNUM35             NUMBER,
  USRNUM36             NUMBER,
  USRNUM37             NUMBER,
  USRNUM38             NUMBER,
  USRNUM39             NUMBER,
  USRNUM40             NUMBER,
  USRNUM41             NUMBER,
  USRNUM42             NUMBER,
  USRNUM43             NUMBER,
  USRNUM44             NUMBER,
  USRNUM45             NUMBER,
  USRNUM46             NUMBER,
  USRNUM47             NUMBER,
  USRNUM48             NUMBER,
  USRNUM49             NUMBER,
  USRNUM50             NUMBER,
  USRNUM51             NUMBER,
  USRNUM52             NUMBER,
  USRNUM53             NUMBER,
  USRNUM54             NUMBER,
  USRNUM55             NUMBER,
  USRNUM56             NUMBER,
  USRNUM57             NUMBER,
  USRNUM58             NUMBER,
  USRNUM59             NUMBER,
  USRNUM60             NUMBER,
  USRNUM61             NUMBER,
  USRNUM62             NUMBER,
  USRNUM63             NUMBER,
  USRNUM64             NUMBER,
  USRNUM65             NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  USRTXT6              VARCHAR2(255 CHAR),
  USRTXT7              VARCHAR2(255 CHAR),
  USRTXT8              VARCHAR2(255 CHAR),
  USRTXT9              VARCHAR2(255 CHAR),
  USRTXT10             VARCHAR2(255 CHAR),
  USRTXT11             VARCHAR2(255 CHAR),
  USRTXT12             VARCHAR2(255 CHAR),
  USRTXT13             VARCHAR2(255 CHAR),
  USRTXT14             VARCHAR2(255 CHAR),
  USRTXT15             VARCHAR2(255 CHAR),
  USRTXT16             VARCHAR2(255 CHAR),
  USRTXT17             VARCHAR2(255 CHAR),
  USRTXT18             VARCHAR2(255 CHAR),
  USRTXT19             VARCHAR2(255 CHAR),
  USRTXT20             VARCHAR2(255 CHAR),
  USRTXT21             VARCHAR2(255 CHAR),
  USRTXT22             VARCHAR2(255 CHAR),
  USRTXT23             VARCHAR2(255 CHAR),
  USRTXT24             VARCHAR2(255 CHAR),
  USRTXT25             VARCHAR2(255 CHAR),
  USRTXT26             VARCHAR2(255 CHAR),
  USRTXT27             VARCHAR2(255 CHAR),
  USRTXT28             VARCHAR2(255 CHAR),
  USRTXT29             VARCHAR2(255 CHAR),
  USRTXT30             VARCHAR2(255 CHAR),
  USRTXT31             VARCHAR2(255 CHAR),
  USRTXT32             VARCHAR2(255 CHAR),
  USRTXT33             VARCHAR2(255 CHAR),
  USRTXT34             VARCHAR2(255 CHAR),
  USRTXT35             VARCHAR2(255 CHAR),
  USRTXT36             VARCHAR2(255 CHAR),
  USRTXT37             VARCHAR2(255 CHAR),
  USRTXT38             VARCHAR2(255 CHAR),
  USRTXT39             VARCHAR2(255 CHAR),
  USRTXT40             VARCHAR2(255 CHAR),
  USRTXT41             VARCHAR2(255 CHAR),
  USRTXT42             VARCHAR2(255 CHAR),
  USRTXT43             VARCHAR2(255 CHAR),
  USRTXT44             VARCHAR2(255 CHAR),
  USRTXT45             VARCHAR2(255 CHAR),
  USRTXT46             VARCHAR2(255 CHAR),
  USRTXT47             VARCHAR2(255 CHAR),
  USRTXT48             VARCHAR2(255 CHAR),
  USRTXT49             VARCHAR2(255 CHAR),
  USRTXT50             VARCHAR2(255 CHAR),
  USRTXT51             VARCHAR2(255 CHAR),
  USRTXT52             VARCHAR2(255 CHAR),
  USRTXT53             VARCHAR2(255 CHAR),
  USRTXT54             VARCHAR2(255 CHAR),
  USRTXT55             VARCHAR2(255 CHAR),
  USRTXT56             VARCHAR2(255 CHAR),
  USRTXT57             VARCHAR2(255 CHAR),
  USRTXT58             VARCHAR2(255 CHAR),
  USRTXT59             VARCHAR2(255 CHAR),
  USRTXT60             VARCHAR2(255 CHAR),
  USRTXT61             VARCHAR2(255 CHAR),
  USRTXT62             VARCHAR2(255 CHAR),
  USRTXT63             VARCHAR2(255 CHAR),
  USRTXT64             VARCHAR2(255 CHAR),
  USRTXT65             VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_PRODUCTIONORDERS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_PRODUCTIONORDERS_ITM_D ON DCEREPORT_PRODUCTIONORDERS(ITEM_OID)
/

CREATE INDEX IREPORT_PRODUCTIONRDRS_CSTMR_D ON DCEREPORT_PRODUCTIONORDERS(CUSTOMER_OID)
/

CREATE INDEX IREPORT_PRODUCTIONORDERS_RCP_D ON DCEREPORT_PRODUCTIONORDERS(RECIPE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MACHINEOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MACHINEOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  DTSPLANNEDSTART      DATE,
  DTSPLANNEDSTOP       DATE,
  DTSSCHEDULEDSTART    DATE,
  DTSSCHEDULEDSTOP     DATE,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  INSTRUCTIONSTATUS    NUMBER(10),
  PROCESSRESOURCE_OID  NUMBER(19),
  ITEM_OID             NUMBER(19),
  QTYPLANNED           NUMBER,
  QTYFACTOR            NUMBER,
  QTYUNIT              NUMBER,
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MACHINEOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_MCHNPRTNS_PRDCTNPRTN_D ON DCEREPORT_MACHINEOPERATIONS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_MACHNPRTNS_PRDCTNRDR_D ON DCEREPORT_MACHINEOPERATIONS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_MACHNPRTNS_PRCSSRSRC_D ON DCEREPORT_MACHINEOPERATIONS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_MACHINEOPERATIONS_TM_D ON DCEREPORT_MACHINEOPERATIONS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MACHINEOP_SEGMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MACHINEOP_SEGMENTS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSPLANNEDSTART      DATE,
  DTSPLANNEDSTOP       DATE,
  TARGETDURATION       NUMBER,
  EFFICIENCY           NUMBER,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_MACHINEOP_SEGMENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRPRT_MCHNP_SGMNTS_PRCSSRSRC_D ON DCEREPORT_MACHINEOP_SEGMENTS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPRT_MCHNP_SGMNTS_MCHNPRTN_D ON DCEREPORT_MACHINEOP_SEGMENTS(MACHINEOPERATION_OID)
/

CREATE INDEX IPRT_MCHNP_SGMNTS_PRDCTNPRTN_D ON DCEREPORT_MACHINEOP_SEGMENTS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IRPRT_MCHNP_SGMNTS_PRDCTNRDR_D ON DCEREPORT_MACHINEOP_SEGMENTS(PRODUCTIONORDER_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MACHINEOP_QTIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MACHINEOP_QTIES
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  PRODUCTIONORDER_ID   VARCHAR2(32 CHAR),
  SHIFT_OID            NUMBER(19),
  ITEM_OID             NUMBER(19),
  TYPE                 VARCHAR2(16 CHAR),
  QTYPLANNED           NUMBER,
  QTYFACTOR            NUMBER,
  QTYUNIT              NUMBER,
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTY_SETUP            NUMBER,
  QTY_LOAD             NUMBER,
  QTY_RUN              NUMBER,
  QTY_UNLOAD           NUMBER,
  QTY_RESET            NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREJECTED_SETUP    NUMBER,
  QTYREJECTED_LOAD     NUMBER,
  QTYREJECTED_RUN      NUMBER,
  QTYREJECTED_UNLOAD   NUMBER,
  QTYREJECTED_RESET    NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  WIP_TYPE             VARCHAR2(10 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MACHINEOP_QTIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_MACHNP_QTS_PRCSSRSRC_D ON DCEREPORT_MACHINEOP_QTIES(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_MACHINP_QTS_MCHNPRTN_D ON DCEREPORT_MACHINEOP_QTIES(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_MCHNP_QTS_PRDCTNPRTN_D ON DCEREPORT_MACHINEOP_QTIES(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_MACHNP_QTS_PRDCTNRDR_D ON DCEREPORT_MACHINEOP_QTIES(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_MACHINEOP_QTIES_SHFT_D ON DCEREPORT_MACHINEOP_QTIES(SHIFT_OID)
/

CREATE INDEX IREPORT_MACHINEOP_QTIES_ITEM_D ON DCEREPORT_MACHINEOP_QTIES(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHIFTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHIFTS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(32 CHAR),
  DESCRIPTION          VARCHAR2(64 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  ISPRODUCTIVE         CHAR(1),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SHIFTS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DIRECT_TASKS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DIRECT_TASKS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  ALLOCATION           NUMBER,
  FTE                  NUMBER,
  PRODUCTIONORDER_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  ACTIVITY_OID         NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  QTYDIRECTREWORK      NUMBER,
  QTYINDIRECTREWORK    NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DIRECT_TASKS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_DIRCT_TSKS_PRDCTNRDR_D ON DCEREPORT_DIRECT_TASKS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_DIRECT_TSKS_MCHNPRTN_D ON DCEREPORT_DIRECT_TASKS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_DRCT_TSKS_PRDCTNPRTN_D ON DCEREPORT_DIRECT_TASKS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_DIRCT_TSKS_PRCSSRSRC_D ON DCEREPORT_DIRECT_TASKS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_DIRECT_TASKS_ACTIVTY_D ON DCEREPORT_DIRECT_TASKS(ACTIVITY_OID)
/

CREATE INDEX IREPORT_DIRECT_TASKS_EMPLOYE_D ON DCEREPORT_DIRECT_TASKS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_DIRECT_TASKS_ITEM_OID ON DCEREPORT_DIRECT_TASKS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DIRECT_TASK_SEGMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DIRECT_TASK_SEGMENTS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  WORKCENTER_OID       NUMBER(19),
  DIRECT_TASK_OID      NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  ITEM_OID             NUMBER(19),
  QTY                  NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_DIRECT_TASK_SEGMENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IPRT_DRCT_TSK_SGMNTS_WRKCNTR_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(WORKCENTER_OID)
/

CREATE INDEX IRT_DRCT_TSK_SGMNTS_DRCT_TSK_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(DIRECT_TASK_OID)
/

CREATE INDEX IRT_DRCT_TSK_SGMNTS_MCHNPRTN_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(MACHINEOPERATION_OID)
/

CREATE INDEX I_DRCT_TSK_SGMNTS_PRDCTNPRTN_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IT_DRCT_TSK_SGMNTS_PRDCTNRDR_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_DIRECT_TSK_SGMNTS_TM_D ON DCEREPORT_DIRECT_TASK_SEGMENTS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DIRECT_TASK_QTIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DIRECT_TASK_QTIES
(
  OID                  NUMBER(19) NOT NULL,
  DIRECT_TASK_OID      NUMBER(19),
  WORKCENTER_OID       NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  SHIFT_OID            NUMBER(19),
  ITEM_OID             NUMBER(19),
  TYPE                 VARCHAR2(16 CHAR),
  QTYPLANNED           NUMBER,
  QTYFACTOR            NUMBER,
  QTYUNIT              NUMBER,
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTY_SETUP            NUMBER,
  QTY_LOAD             NUMBER,
  QTY_RUN              NUMBER,
  QTY_UNLOAD           NUMBER,
  QTY_RESET            NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREJECTED_SETUP    NUMBER,
  QTYREJECTED_LOAD     NUMBER,
  QTYREJECTED_RUN      NUMBER,
  QTYREJECTED_UNLOAD   NUMBER,
  QTYREJECTED_RESET    NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  QTYDIRECTREWORK      NUMBER,
  QTYINDIRECTREWORK    NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DIRECT_TASK_QTIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPRT_DRCT_TSK_QTS_DRCT_TSK_D ON DCEREPORT_DIRECT_TASK_QTIES(DIRECT_TASK_OID)
/

CREATE INDEX IREPORT_DRCT_TSK_QTS_WRKCNTR_D ON DCEREPORT_DIRECT_TASK_QTIES(WORKCENTER_OID)
/

CREATE INDEX IREPRT_DRCT_TSK_QTS_MCHNPRTN_D ON DCEREPORT_DIRECT_TASK_QTIES(MACHINEOPERATION_OID)
/

CREATE INDEX IPRT_DRCT_TSK_QTS_PRDCTNPRTN_D ON DCEREPORT_DIRECT_TASK_QTIES(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IRPRT_DRCT_TSK_QTS_PRDCTNRDR_D ON DCEREPORT_DIRECT_TASK_QTIES(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_DIRECT_TASK_QTS_SHFT_D ON DCEREPORT_DIRECT_TASK_QTIES(SHIFT_OID)
/

CREATE INDEX IREPORT_DIRECT_TASK_QTIES_TM_D ON DCEREPORT_DIRECT_TASK_QTIES(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACTIVITIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACTIVITIES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  ID                   VARCHAR2(32 CHAR),
  PRIORITY             NUMBER(10),
  PRODUCTIVE           CHAR(1),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ACTIVITIES
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INDIRECT_TASKS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INDIRECT_TASKS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  ALLOCATION           NUMBER,
  FTE                  NUMBER,
  MANUALOPERATION_OID  NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INDIRECT_TASKS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INDIRCT_TSKS_MNLPRTN_D ON DCEREPORT_INDIRECT_TASKS(MANUALOPERATION_OID)
/

CREATE INDEX IREPORT_NDRCT_TSKS_PRCSSRSRC_D ON DCEREPORT_INDIRECT_TASKS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_INDIRECT_TASKS_EMPLY_D ON DCEREPORT_INDIRECT_TASKS(EMPLOYEE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MANUALOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MANUALOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  PRIORITY             NUMBER(10),
  GROUP_NAME           VARCHAR2(64 CHAR),
  GROUP_DESCRIPTION    VARCHAR2(255 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MANUALOPERATIONS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ALLOCATIONDETAILS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ALLOCATIONDETAILS
(
  OID                  NUMBER(19) NOT NULL,
  TASK_OID             NUMBER(19),
  RESOURCEALLOCATION   NUMBER,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ALLOCATIONDETAILS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_ALLOCATIONDETALS_TSK_D ON DCEREPORT_ALLOCATIONDETAILS(TASK_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MAINTENANCE_TASKS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MAINTENANCE_TASKS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  ALLOCATION           NUMBER,
  FTE                  NUMBER,
  MAINTENANCEORDER_OID NUMBER(19),
  MAINTENANCEORDER_ID  VARCHAR2(32 CHAR),
  MAINTENANCEOPERATION_OID NUMBER(19),
  MAINTENANCEOPERATION_NAME VARCHAR2(64 CHAR),
  PROCESSRESOURCE_OID  NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MAINTENANCE_TASKS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPRT_MNTNNC_TSKS_MNTNNCRDR_D ON DCEREPORT_MAINTENANCE_TASKS(MAINTENANCEORDER_OID)
/

CREATE INDEX IRPRT_MNTNNC_TSKS_MNTNNCPRTN_D ON DCEREPORT_MAINTENANCE_TASKS(MAINTENANCEOPERATION_OID)
/

CREATE INDEX IREPRT_MNTNNC_TSKS_PRCSSRSRC_D ON DCEREPORT_MAINTENANCE_TASKS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_MAINTENANC_TSKS_MPLY_D ON DCEREPORT_MAINTENANCE_TASKS(EMPLOYEE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_REJECTOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_REJECTOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  TYPE                 NUMBER(10),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  DIRECT_TASK_OID      NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  REASON_OID           NUMBER(19),
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREJECTED_SETUP    NUMBER,
  QTYREJECTED_LOAD     NUMBER,
  QTYREJECTED_RUN      NUMBER,
  QTYREJECTED_UNLOAD   NUMBER,
  QTYREJECTED_RESET    NUMBER,
  QTYREWORKED          NUMBER,
  QTYREWORKABLE        NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_REJECTOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_REJCTPRTNS_PRCSSRSRC_D ON DCEREPORT_REJECTOPERATIONS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_REJECTPRTNS_MCHNPRTN_D ON DCEREPORT_REJECTOPERATIONS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_REJECTPRTNS_DRCT_TSK_D ON DCEREPORT_REJECTOPERATIONS(DIRECT_TASK_OID)
/

CREATE INDEX IREPORT_RJCTPRTNS_PRDCTNPRTN_D ON DCEREPORT_REJECTOPERATIONS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_REJECTOPERATINS_MPLY_D ON DCEREPORT_REJECTOPERATIONS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_REJECTOPERATIONS_ITM_D ON DCEREPORT_REJECTOPERATIONS(ITEM_OID)
/

CREATE INDEX IREPORT_REJECTOPERATIONS_RSN_D ON DCEREPORT_REJECTOPERATIONS(REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_REWORKOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_REWORKOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  REJECTOPERATION_OID  NUMBER(19),
  DIRECT_TASK_OID      NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  REASON_OID           NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  QTYREWORKED          NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_REWORKOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_REWORKPRTNS_RJCTPRTN_D ON DCEREPORT_REWORKOPERATIONS(REJECTOPERATION_OID)
/

CREATE INDEX IREPORT_REWORKPRTNS_DRCT_TSK_D ON DCEREPORT_REWORKOPERATIONS(DIRECT_TASK_OID)
/

CREATE INDEX IREPORT_REWORKOPERATINS_MPLY_D ON DCEREPORT_REWORKOPERATIONS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_REWORKOPERATIONS_ITM_D ON DCEREPORT_REWORKOPERATIONS(ITEM_OID)
/

CREATE INDEX IREPORT_REWORKOPERATIONS_RSN_D ON DCEREPORT_REWORKOPERATIONS(REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_REJECTREASONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_REJECTREASONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  CATEGORY             VARCHAR2(64 CHAR),
  REASONGROUP_NAME     VARCHAR2(64 CHAR),
  REASONGROUP_DESCRIPTION VARCHAR2(255 CHAR),
  REASONGROUP_TYPE     NUMBER(10),
  REASONGROUP_CATEGORY VARCHAR2(64 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_REJECTREASONS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ALARMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ALARMS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  SEVERITY             NUMBER(10),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  PROCESSRESOURCE_OID  NUMBER(19),
  EQUIPMENTMODULE_OID  NUMBER(19),
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_ALARMS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_ALARMS_PROCESSRESORC_D ON DCEREPORT_ALARMS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_ALARMS_EQUIPMENTMODL_D ON DCEREPORT_ALARMS(EQUIPMENTMODULE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INTERRUPTOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INTERRUPTOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  REASON_OID           NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  ALARM_OID            NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_INTERRUPTOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INTERRUPTOPERTNS_RSN_D ON DCEREPORT_INTERRUPTOPERATIONS(REASON_OID)
/

CREATE INDEX IREPRT_NTRRPTPRTNS_PRCSSRSRC_D ON DCEREPORT_INTERRUPTOPERATIONS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_NTRRPTPRTNS_MCHNPRTN_D ON DCEREPORT_INTERRUPTOPERATIONS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_INTERRUPTOPERTNS_LRM_D ON DCEREPORT_INTERRUPTOPERATIONS(ALARM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INTERRUPTREASONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INTERRUPTREASONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  OEECATEGORY          VARCHAR2(64 CHAR),
  SEVERITY             NUMBER(10),
  REASONGROUP_NAME     VARCHAR2(64 CHAR),
  REASONGROUP_DESCRIPTION VARCHAR2(255 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  USRDTS1              DATE,
  USRDTS2              DATE,
  USRDTS3              DATE,
  USRDTS4              DATE,
  USRDTS5              DATE,
  USRFLG1              CHAR(1),
  USRFLG2              CHAR(1),
  USRFLG3              CHAR(1),
  USRFLG4              CHAR(1),
  USRFLG5              CHAR(1),
  USRNUM1              NUMBER,
  USRNUM2              NUMBER,
  USRNUM3              NUMBER,
  USRNUM4              NUMBER,
  USRNUM5              NUMBER,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  CONSTRAINT PK_DCEREPORT_INTERRUPTREASONS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ISPRESENTOPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ISPRESENTOPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  EMPLOYEE_OID         NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_ISPRESENTOPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_ISPRESENTOPRTNS_MPLY_D ON DCEREPORT_ISPRESENTOPERATIONS(EMPLOYEE_OID)
/

CREATE INDEX IREPRT_SPRSNTPRTNS_PRCSSRSRC_D ON DCEREPORT_ISPRESENTOPERATIONS(PROCESSRESOURCE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MES_EVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MES_EVENTS
(
  OID                  NUMBER(19) NOT NULL,
  TYPE                 NUMBER(10),
  DTS                  DATE,
  CATEGORY             VARCHAR2(255 CHAR),
  DESCRIPTION          VARCHAR2(1000 CHAR),
  VALUE                VARCHAR2(255 CHAR),
  PREVIOUS_VALUE       VARCHAR2(255 CHAR),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  ITEM_OID             NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MES_EVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_MES_EVENTS_EMPLOYEE_OD ON DCEREPORT_MES_EVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_MES_EVENTS_DEVICE_OID ON DCEREPORT_MES_EVENTS(DEVICE_OID)
/

CREATE INDEX IREPORT_MES_EVENTS_PRDCTNRDR_D ON DCEREPORT_MES_EVENTS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_MES_EVNTS_PRDCTNPRTN_D ON DCEREPORT_MES_EVENTS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_MES_EVENTS_PRCSSRSRC_D ON DCEREPORT_MES_EVENTS(PROCESSRESOURCE_OID)
/

CREATE INDEX IDCEREPORT_MES_EVENTS_ITEM_OID ON DCEREPORT_MES_EVENTS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_OEEOPERATIONREPORTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_OEEOPERATIONREPORTS
(
  OID                  NUMBER(19) NOT NULL,
  OEEREPORT_OID        NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  SHIFT_NAME           VARCHAR2(32 CHAR),
  SHIFT_DESCRIPTION    VARCHAR2(64 CHAR),
  SHIFT_ISPRODUCTIVE   CHAR(1),
  SHIFT_START          DATE,
  SHIFT_STOP           DATE,
  STATUS               NUMBER(10),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  OEE                  NUMBER,
  AVAILABILITY         NUMBER,
  PRODUCTIVITY         NUMBER,
  QUALITY              NUMBER,
  CAPACITY             NUMBER,
  FTR                  NUMBER,
  OEETARGET            NUMBER,
  AVAILABILITYTARGET   NUMBER,
  PRODUCTIVITYTARGET   NUMBER,
  QUALITYTARGET        NUMBER,
  CAPACITYTARGET       NUMBER,
  DURATION_TOTAL       NUMBER(19),
  DURATION_UNAVAILABLE_OEE1 NUMBER(19),
  NO_PLANNING_OEE1A    NUMBER(19),
  PLANNED_INTERRUPTS_OEE1B NUMBER(19),
  DURATION_PLANNED     NUMBER(19),
  AVAILABILITY_LOSSES_OEE2 NUMBER(19),
  SETUPS_OEE2A         NUMBER(19),
  BREAKDOWNS_OEE2B     NUMBER(19),
  DURATION_OPERATIONAL NUMBER(19),
  PRODUCTIVITY_LOSSES_OEE3 NUMBER(19),
  SPEED_LOSSES_OEE3A   NUMBER(19),
  MICROSTOPS_OEE3B     NUMBER(19),
  DURATION_NET_OPERATIONAL NUMBER(19),
  QUALITY_LOSSES_OEE4  NUMBER(19),
  QTY                  NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  DURATION_EFF_OPERATIONAL NUMBER(19),
  AVERAGE_RESOURCE_ALLOCATION NUMBER,
  TOTAL_LABOUR_DURATION NUMBER(19),
  PRODUCTIVE_LABOUR_DURATION NUMBER(19),
  TARGET_SPEED         VARCHAR2(255 CHAR),
  ACTUAL_SPEED         VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_OEEOPERATIONREPORTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_OEEOPERATNRPRTS_RPRT_D ON DCEREPORT_OEEOPERATIONREPORTS(OEEREPORT_OID)
/

CREATE INDEX IREPORT_OPRTNRPRTS_PRCSSRSRC_D ON DCEREPORT_OEEOPERATIONREPORTS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_OEPRTNRPRTS_MCHNPRTN_D ON DCEREPORT_OEEOPERATIONREPORTS(MACHINEOPERATION_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_OEEREPORTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_OEEREPORTS
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  SHIFT_NAME           VARCHAR2(32 CHAR),
  SHIFT_DESCRIPTION    VARCHAR2(64 CHAR),
  SHIFT_ISPRODUCTIVE   CHAR(1),
  SHIFT_START          DATE,
  SHIFT_STOP           DATE,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  STATUS               NUMBER(10),
  OEE                  NUMBER,
  AVAILABILITY         NUMBER,
  PRODUCTIVITY         NUMBER,
  QUALITY              NUMBER,
  CAPACITY             NUMBER,
  FTR                  NUMBER,
  OEETARGET            NUMBER,
  AVAILABILITYTARGET   NUMBER,
  PRODUCTIVITYTARGET   NUMBER,
  QUALITYTARGET        NUMBER,
  CAPACITYTARGET       NUMBER,
  DURATION_TOTAL       NUMBER(19),
  DURATION_UNAVAILABLE_OEE1 NUMBER(19),
  NO_PLANNING_OEE1A    NUMBER(19),
  PLANNED_INTERRUPTS_OEE1B NUMBER(19),
  DURATION_PLANNED     NUMBER(19),
  AVAILABILITY_LOSSES_OEE2 NUMBER(19),
  SETUPS_OEE2A         NUMBER(19),
  BREAKDOWNS_OEE2B     NUMBER(19),
  DURATION_OPERATIONAL NUMBER(19),
  PRODUCTIVITY_LOSSES_OEE3 NUMBER(19),
  SPEED_LOSSES_OEE3A   NUMBER(19),
  MICROSTOPS_OEE3B     NUMBER(19),
  DURATION_NET_OPERATIONAL NUMBER(19),
  QUALITY_LOSSES_OEE4  NUMBER(19),
  DURATION_EFF_OPERATIONAL NUMBER(19),
  AVERAGE_RESOURCE_ALLOCATION NUMBER,
  TOTAL_LABOUR_DURATION NUMBER(19),
  PRODUCTIVE_LABOUR_DURATION NUMBER(19),
  QTYPRODUCED          NUMBER,
  QTYINCOMPLETE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREJECT            NUMBER,
  QTYREJECTED          NUMBER,
  QTYREWORKED          NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_OEEREPORTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_OEEREPORTS_PRCSSRSRC_D ON DCEREPORT_OEEREPORTS(PROCESSRESOURCE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SETUPINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SETUPINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  SETUPPARAMETER_OID   NUMBER(19) NOT NULL,
  SETUPPARAMETER_TYPE  VARCHAR2(7 CHAR),
  SETUPPARAMETER_NAME  VARCHAR2(32 CHAR),
  SETUPPARAMETER_DESCRIPTION VARCHAR2(255 CHAR),
  STANDARDTEXTVALUE    VARCHAR2(255 CHAR),
  TEXTVALUE            VARCHAR2(255 CHAR),
  QTYSTANDARD          NUMBER,
  QTYTARGET            NUMBER,
  TARGETEDITABLE       CHAR(1),
  UPPER_SETUP_LIMIT    NUMBER,
  LOWER_SETUP_LIMIT    NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SETUPINSTR
  PRIMARY KEY (OID, SETUPPARAMETER_OID)
)
/

CREATE INDEX IREPORT_SETUPINSTR_PRCSSRSRC_D ON DCEREPORT_SETUPINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_SETUPINSTR_MACHNPRTN_D ON DCEREPORT_SETUPINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_SETUPNSTR_PRDCTNPRTN_D ON DCEREPORT_SETUPINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_SETUPINSTR_PRDCTNRDR_D ON DCEREPORT_SETUPINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_SETUPNSTR_NSTRCTNSHT_D ON DCEREPORT_SETUPINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SETUPEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SETUPEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  SETUPINSTRUCTION_OID NUMBER(19),
  SETUPPARAMETER_OID   NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  VALUE                VARCHAR2(255 CHAR),
  UOM                  VARCHAR2(32 CHAR),
  DTS                  DATE,
  DESCRIPTION          VARCHAR2(1000 CHAR),
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SETUPEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_SETUPVNTS_STPNSTRCTN_D ON DCEREPORT_SETUPEVENTS(SETUPINSTRUCTION_OID)
/

CREATE INDEX IREPORT_SETUPEVENTS_STPPRMTR_D ON DCEREPORT_SETUPEVENTS(SETUPPARAMETER_OID)
/

CREATE INDEX IREPORT_SETUPEVENTS_EMPLOYEE_D ON DCEREPORT_SETUPEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_SETUPEVENTS_DEVICE_OID ON DCEREPORT_SETUPEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DATACOLLECTIONINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DATACOLLECTIONINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  PROCESSPARAMETER_OID NUMBER(19) NOT NULL,
  PROCESSPARAMETER_NAME VARCHAR2(32 CHAR),
  PROCESSPARAMETER_DESCRIPTION VARCHAR2(255 CHAR),
  QTYSTANDARD          NUMBER,
  QTYTARGET            NUMBER,
  UPPER_WARNING_LIMIT  NUMBER,
  LOWER_WARNING_LIMIT  NUMBER,
  UPPER_ERROR_LIMIT    NUMBER,
  LOWER_ERROR_LIMIT    NUMBER,
  QTYACTUAL            NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_DATACOLLECTIONINSTR
  PRIMARY KEY (OID, PROCESSPARAMETER_OID)
)
/

CREATE INDEX IRPRT_DTCLLCTNNSTR_PRCSSRSRC_D ON DCEREPORT_DATACOLLECTIONINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPRT_DTCLLCTNNSTR_MCHNPRTN_D ON DCEREPORT_DATACOLLECTIONINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IPRT_DTCLLCTNNSTR_PRDCTNPRTN_D ON DCEREPORT_DATACOLLECTIONINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IRPRT_DTCLLCTNNSTR_PRDCTNRDR_D ON DCEREPORT_DATACOLLECTIONINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IPRT_DTCLLCTNNSTR_NSTRCTNSHT_D ON DCEREPORT_DATACOLLECTIONINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DATACOLLECTIONEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DATACOLLECTIONEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  DATACOLLECTIONINSTRUCTION_OID NUMBER(19),
  PROCESSPARAMETER_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  VALUE                VARCHAR2(255 CHAR),
  UOM                  VARCHAR2(32 CHAR),
  CATEGORY             VARCHAR2(255 CHAR),
  DTS                  DATE,
  DESCRIPTION          VARCHAR2(1000 CHAR),
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_DATACOLLECTIONEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX ITCLLCTNVNTS_DTCLLCTNNSTRCTN_D ON DCEREPORT_DATACOLLECTIONEVENTS(DATACOLLECTIONINSTRUCTION_OID)
/

CREATE INDEX IPRT_DTCLLCTNVNTS_PRCSSPRMTR_D ON DCEREPORT_DATACOLLECTIONEVENTS(PROCESSPARAMETER_OID)
/

CREATE INDEX IREPORT_DATACOLLCTNVNTS_MPLY_D ON DCEREPORT_DATACOLLECTIONEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_DATACOLLECTNVNTS_DVC_D ON DCEREPORT_DATACOLLECTIONEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MEASUREMENTINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MEASUREMENTINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  MEASUREMENT_OID      NUMBER(19) NOT NULL,
  MEASUREMENT_NAME     VARCHAR2(32 CHAR),
  MEASUREMENT_DESCRIPTION VARCHAR2(255 CHAR),
  QTYSTANDARD          NUMBER,
  UCL                  NUMBER,
  LCL                  NUMBER,
  USL                  NUMBER,
  LSL                  NUMBER,
  AVERAGE              NUMBER,
  VALUERANGE           NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MEASUREMENTINSTR
  PRIMARY KEY (OID, MEASUREMENT_OID)
)
/

CREATE INDEX IREPORT_MSRMNTNSTR_PRCSSRSRC_D ON DCEREPORT_MEASUREMENTINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_MESRMNTNSTR_MCHNPRTN_D ON DCEREPORT_MEASUREMENTINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IREPRT_MSRMNTNSTR_PRDCTNPRTN_D ON DCEREPORT_MEASUREMENTINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_MSRMNTNSTR_PRDCTNRDR_D ON DCEREPORT_MEASUREMENTINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPRT_MSRMNTNSTR_NSTRCTNSHT_D ON DCEREPORT_MEASUREMENTINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_MEASUREMENTEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_MEASUREMENTEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  MEASUREMENTINSTRUCTION_OID NUMBER(19),
  MEASUREMENT_OID      NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  VALUE                VARCHAR2(255 CHAR),
  UOM                  VARCHAR2(32 CHAR),
  DTS                  DATE,
  DESCRIPTION          VARCHAR2(1000 CHAR),
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_MEASUREMENTEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRT_MSRMNTVNTS_MSRMNTNSTRCTN_D ON DCEREPORT_MEASUREMENTEVENTS(MEASUREMENTINSTRUCTION_OID)
/

CREATE INDEX IREPORT_MEASURMNTVNTS_MSRMNT_D ON DCEREPORT_MEASUREMENTEVENTS(MEASUREMENT_OID)
/

CREATE INDEX IREPORT_MEASUREMENTVNTS_MPLY_D ON DCEREPORT_MEASUREMENTEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_MEASUREMENTEVNTS_DVC_D ON DCEREPORT_MEASUREMENTEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INPUTINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INPUTINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  VALUE                VARCHAR2(255 CHAR),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INPUTINSTR
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INPUTINSTR_PRCSSRSRC_D ON DCEREPORT_INPUTINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_INPUTINSTR_MACHNPRTN_D ON DCEREPORT_INPUTINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_INPUTNSTR_PRDCTNPRTN_D ON DCEREPORT_INPUTINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_INPUTINSTR_PRDCTNRDR_D ON DCEREPORT_INPUTINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_INPUTNSTR_NSTRCTNSHT_D ON DCEREPORT_INPUTINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INPUTEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INPUTEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  INPUTINSTRUCTION_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  VALUE                VARCHAR2(255 CHAR),
  COMMENTS             VARCHAR2(1000 CHAR),
  DTS                  DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INPUTEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INPUTVNTS_NPTNSTRCTN_D ON DCEREPORT_INPUTEVENTS(INPUTINSTRUCTION_OID)
/

CREATE INDEX IREPORT_INPUTEVENTS_EMPLOYEE_D ON DCEREPORT_INPUTEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_INPUTEVENTS_DEVICE_OID ON DCEREPORT_INPUTEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CHECKINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CHECKINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  VALUE                NUMBER,
  INPUTTYPE            NUMBER(10),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_CHECKINSTR
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_CHECKINSTR_PRCSSRSRC_D ON DCEREPORT_CHECKINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_CHECKINSTR_MACHNPRTN_D ON DCEREPORT_CHECKINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_CHECKNSTR_PRDCTNPRTN_D ON DCEREPORT_CHECKINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_CHECKINSTR_PRDCTNRDR_D ON DCEREPORT_CHECKINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_CHECKNSTR_NSTRCTNSHT_D ON DCEREPORT_CHECKINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_CHECKEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_CHECKEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  CHECKINSTRUCTION_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  VALUE                VARCHAR2(255 CHAR),
  COMMENTS             VARCHAR2(1000 CHAR),
  DTS                  DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_CHECKEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_CHCKVNTS_CHCKNSTRCTN_D ON DCEREPORT_CHECKEVENTS(CHECKINSTRUCTION_OID)
/

CREATE INDEX IREPORT_CHECKEVENTS_EMPLOYEE_D ON DCEREPORT_CHECKEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_CHECKEVENTS_DEVICE_OID ON DCEREPORT_CHECKEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PRINTINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PRINTINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  DOCUMENT_NAME        VARCHAR2(64 CHAR),
  DOCUMENT_DESCRIPTION VARCHAR2(255 CHAR),
  COPIES               NUMBER(10),
  COPIESFIXED          CHAR(1),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_PRINTINSTR
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_PRINTINSTR_PRCSSRSRC_D ON DCEREPORT_PRINTINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_PRINTINSTR_MACHNPRTN_D ON DCEREPORT_PRINTINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_PRINTNSTR_PRDCTNPRTN_D ON DCEREPORT_PRINTINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_PRINTINSTR_PRDCTNRDR_D ON DCEREPORT_PRINTINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_PRINTNSTR_NSTRCTNSHT_D ON DCEREPORT_PRINTINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PRINTEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PRINTEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  PRINTINSTRUCTION_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  COMMENTS             VARCHAR2(1000 CHAR),
  DTS                  DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_PRINTEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_PRNTVNTS_PRNTNSTRCTN_D ON DCEREPORT_PRINTEVENTS(PRINTINSTRUCTION_OID)
/

CREATE INDEX IREPORT_PRINTEVENTS_EMPLOYEE_D ON DCEREPORT_PRINTEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_PRINTEVENTS_DEVICE_OID ON DCEREPORT_PRINTEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_INSPECTIONINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_INSPECTIONINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  INSPECTIONTYPE       VARCHAR2(64 CHAR),
  INSPECTIONSHEETOID   NUMBER(19),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_INSPECTIONINSTR
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTRP_NSPCTNNSTR_PRCSSRSRC_D ON OBJTREP_INSPECTIONINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IOBJTREP_NSPCTNNSTR_MCHNPRTN_D ON OBJTREP_INSPECTIONINSTR(MACHINEOPERATION_OID)
/

CREATE INDEX IBJTRP_NSPCTNNSTR_PRDCTNPRTN_D ON OBJTREP_INSPECTIONINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IOBJTRP_NSPCTNNSTR_PRDCTNRDR_D ON OBJTREP_INSPECTIONINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IBJTRP_NSPCTNNSTR_NSTRCTNSHT_D ON OBJTREP_INSPECTIONINSTR(INSTRUCTIONSHEET_OID)
/

CREATE INDEX IOBJTREP_NSPCTNNSTR_NSPCTNSHTD ON OBJTREP_INSPECTIONINSTR(INSPECTIONSHEETOID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_INSPECTIONEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_INSPECTIONEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  INSPECTIONINSTRUCTION_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  COMMENTS             VARCHAR2(1000 CHAR),
  DTS                  DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_INSPECTIONEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IRP_NSPCTNVNTS_NSPCTNNSTRCTN_D ON OBJTREP_INSPECTIONEVENTS(INSPECTIONINSTRUCTION_OID)
/

CREATE INDEX IOBJTREP_INSPECTIONVNTS_MPLY_D ON OBJTREP_INSPECTIONEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_INSPECTIONEVNTS_DVC_D ON OBJTREP_INSPECTIONEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DOCUMENTEDINSTR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DOCUMENTEDINSTR
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19) NOT NULL,
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  INSTRUCTIONSHEET_OID NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  INFO                 VARCHAR2(1024 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DOCUMENTEDINSTR
  PRIMARY KEY (OID, MACHINEOPERATION_OID)
)
/

CREATE INDEX IREPORT_DCMNTDNSTR_PRCSSRSRC_D ON DCEREPORT_DOCUMENTEDINSTR(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPRT_DCMNTDNSTR_PRDCTNPRTN_D ON DCEREPORT_DOCUMENTEDINSTR(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_DCMNTDNSTR_PRDCTNRDR_D ON DCEREPORT_DOCUMENTEDINSTR(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPRT_DCMNTDNSTR_NSTRCTNSHT_D ON DCEREPORT_DOCUMENTEDINSTR(INSTRUCTIONSHEET_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INSTRUCTIONDOCS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INSTRUCTIONDOCS
(
  OID                  NUMBER(19) NOT NULL,
  INSTRUCTION_OID      NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  TYPE                 VARCHAR2(10 CHAR),
  REFERENCE            VARCHAR2(255 CHAR),
  TEXT                 VARCHAR2(1024 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INSTRUCTIONDOCS
  PRIMARY KEY (OID, INSTRUCTION_OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DOCUMENTEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DOCUMENTEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  INSTRUCTION_OID      NUMBER(19),
  DOCUMENT_OID         NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  CATEGORY             VARCHAR2(255 CHAR),
  DTS                  DATE,
  COMMENTS             VARCHAR2(1000 CHAR),
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DOCUMENTEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_DOCUMENTVNTS_NSTRCTN_D ON DCEREPORT_DOCUMENTEVENTS(INSTRUCTION_OID)
/

CREATE INDEX IREPORT_DOCUMENTEVENTS_DCMNT_D ON DCEREPORT_DOCUMENTEVENTS(DOCUMENT_OID)
/

CREATE INDEX IREPORT_DOCUMENTEVENTS_EMPLY_D ON DCEREPORT_DOCUMENTEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_DOCUMENTEVENTS_DEVIC_D ON DCEREPORT_DOCUMENTEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INSTRUCTIONSHEETS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INSTRUCTIONSHEETS
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(1024 CHAR),
  ID                   VARCHAR2(64 CHAR),
  STATUS               VARCHAR2(8 CHAR),
  QUALITYSHEET         CHAR(1),
  DOUBLESIGNOFF        CHAR(1),
  TAKEOFFSHEET         CHAR(1),
  DTSLASTEXECUTED      DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INSTRUCTIONSHEETS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPRT_NSTRCTNSHTS_PRCSSRSRC_D ON DCEREPORT_INSTRUCTIONSHEETS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_NSTRCTNSHTS_MCHNPRTN_D ON DCEREPORT_INSTRUCTIONSHEETS(MACHINEOPERATION_OID)
/

CREATE INDEX IRPRT_NSTRCTNSHTS_PRDCTNPRTN_D ON DCEREPORT_INSTRUCTIONSHEETS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPRT_NSTRCTNSHTS_PRDCTNRDR_D ON DCEREPORT_INSTRUCTIONSHEETS(PRODUCTIONORDER_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_SHEETEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_SHEETEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  INSTRUCTIONSHEET_OID NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  CATEGORY             VARCHAR2(255 CHAR),
  COMMENTS             VARCHAR2(1000 CHAR),
  DTS                  DATE,
  RESULT               NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_SHEETEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_SHEETVNTS_NSTRCTNSHT_D ON DCEREPORT_SHEETEVENTS(INSTRUCTIONSHEET_OID)
/

CREATE INDEX IREPORT_SHEETEVENTS_EMPLOYEE_D ON DCEREPORT_SHEETEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_SHEETEVENTS_DEVICE_OID ON DCEREPORT_SHEETEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INPUT_TARGETS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INPUT_TARGETS
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  LOCATION_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  LOT                  VARCHAR2(32 CHAR),
  SUBLOT               VARCHAR2(32 CHAR),
  TARGET               NUMBER,
  QTY                  NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INPUT_TARGETS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INPT_TRGTS_PRCSSRSRC_D ON DCEREPORT_INPUT_TARGETS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_INPUT_TRGTS_MCHNPRTN_D ON DCEREPORT_INPUT_TARGETS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_NPT_TRGTS_PRDCTNPRTN_D ON DCEREPORT_INPUT_TARGETS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_INPT_TRGTS_PRDCTNRDR_D ON DCEREPORT_INPUT_TARGETS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_INPUT_TARGETS_LOCATN_D ON DCEREPORT_INPUT_TARGETS(LOCATION_OID)
/

CREATE INDEX IREPORT_INPUT_TARGETS_ITEM_OID ON DCEREPORT_INPUT_TARGETS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INPUT_ACTUALS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INPUT_ACTUALS
(
  OID                  NUMBER(19) NOT NULL,
  INPUT_TARGET_OID     NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  STATUS               NUMBER(10),
  LOCATION_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  LOT_OID              NUMBER(19),
  LOT                  VARCHAR2(32 CHAR),
  SUBLOT               VARCHAR2(32 CHAR),
  INVENTORY_CODE_1     VARCHAR2(64 CHAR),
  INVENTORY_CODE_2     VARCHAR2(64 CHAR),
  INVENTORY_CODE_3     VARCHAR2(64 CHAR),
  INVENTORY_CODE_4     VARCHAR2(64 CHAR),
  INVENTORY_CODE_5     VARCHAR2(64 CHAR),
  QTY                  NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  CONTAINER_OID        NUMBER(19),
  NEST_CONTAINER_OID   NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INPUT_ACTUALS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INPUT_ACTLS_NPT_TRGT_D ON DCEREPORT_INPUT_ACTUALS(INPUT_TARGET_OID)
/

CREATE INDEX IREPORT_INPUT_CTLS_PRCSSRSRC_D ON DCEREPORT_INPUT_ACTUALS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_INPUT_ACTLS_MCHNPRTN_D ON DCEREPORT_INPUT_ACTUALS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_INPT_CTLS_PRDCTNPRTN_D ON DCEREPORT_INPUT_ACTUALS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_INPUT_CTLS_PRDCTNRDR_D ON DCEREPORT_INPUT_ACTUALS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_LOCATN_D ON DCEREPORT_INPUT_ACTUALS(LOCATION_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_ITEM_OID ON DCEREPORT_INPUT_ACTUALS(ITEM_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_LOT_OID ON DCEREPORT_INPUT_ACTUALS(LOT_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_CONTNR_D ON DCEREPORT_INPUT_ACTUALS(CONTAINER_OID)
/

CREATE INDEX IREPORT_INPUT_CTLS_NST_CNTNR_D ON DCEREPORT_INPUT_ACTUALS(NEST_CONTAINER_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_EMPLOY_D ON DCEREPORT_INPUT_ACTUALS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_INPUT_ACTUALS_DEVICE_D ON DCEREPORT_INPUT_ACTUALS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_OUTPUT_TARGETS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_OUTPUT_TARGETS
(
  OID                  NUMBER(19) NOT NULL,
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  LOCATION_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  LOT                  VARCHAR2(32 CHAR),
  SUBLOT               VARCHAR2(32 CHAR),
  QTY                  NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_OUTPUT_TARGETS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_OTPT_TRGTS_PRCSSRSRC_D ON DCEREPORT_OUTPUT_TARGETS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_OUTPT_TRGTS_MCHNPRTN_D ON DCEREPORT_OUTPUT_TARGETS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_TPT_TRGTS_PRDCTNPRTN_D ON DCEREPORT_OUTPUT_TARGETS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_OTPT_TRGTS_PRDCTNRDR_D ON DCEREPORT_OUTPUT_TARGETS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_OUTPUT_TARGETS_LOCTN_D ON DCEREPORT_OUTPUT_TARGETS(LOCATION_OID)
/

CREATE INDEX IREPORT_OUTPUT_TARGETS_ITEM_OD ON DCEREPORT_OUTPUT_TARGETS(ITEM_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_OUTPUT_ACTUALS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_OUTPUT_ACTUALS
(
  OID                  NUMBER(19) NOT NULL,
  OUTPUT_TARGET_OID    NUMBER(19),
  PROCESSRESOURCE_OID  NUMBER(19),
  MACHINEOPERATION_OID NUMBER(19),
  PRODUCTIONOPERATION_OID NUMBER(19),
  PRODUCTIONORDER_OID  NUMBER(19),
  STATUS               NUMBER(10),
  LOCATION_OID         NUMBER(19),
  ITEM_OID             NUMBER(19),
  LOT_OID              NUMBER(19),
  LOT                  VARCHAR2(32 CHAR),
  SUBLOT               VARCHAR2(32 CHAR),
  INVENTORY_CODE_1     VARCHAR2(64 CHAR),
  INVENTORY_CODE_2     VARCHAR2(64 CHAR),
  INVENTORY_CODE_3     VARCHAR2(64 CHAR),
  INVENTORY_CODE_4     VARCHAR2(64 CHAR),
  INVENTORY_CODE_5     VARCHAR2(64 CHAR),
  QTY                  NUMBER,
  UOM                  VARCHAR2(32 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  CONTAINER_OID        NUMBER(19),
  NEST_CONTAINER_OID   NUMBER(19),
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  QTYREWORKABLE        NUMBER,
  QTYNRFT              NUMBER,
  QTYREWORKED          NUMBER,
  QTYADJUSTED          NUMBER,
  QTYREJECTED          NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_OUTPUT_ACTUALS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_OUTPUT_CTLS_TPT_TRGT_D ON DCEREPORT_OUTPUT_ACTUALS(OUTPUT_TARGET_OID)
/

CREATE INDEX IREPORT_OUTPT_CTLS_PRCSSRSRC_D ON DCEREPORT_OUTPUT_ACTUALS(PROCESSRESOURCE_OID)
/

CREATE INDEX IREPORT_OUTPUT_CTLS_MCHNPRTN_D ON DCEREPORT_OUTPUT_ACTUALS(MACHINEOPERATION_OID)
/

CREATE INDEX IREPORT_OTPT_CTLS_PRDCTNPRTN_D ON DCEREPORT_OUTPUT_ACTUALS(PRODUCTIONOPERATION_OID)
/

CREATE INDEX IREPORT_OUTPT_CTLS_PRDCTNRDR_D ON DCEREPORT_OUTPUT_ACTUALS(PRODUCTIONORDER_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_LOCTN_D ON DCEREPORT_OUTPUT_ACTUALS(LOCATION_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_ITEM_OD ON DCEREPORT_OUTPUT_ACTUALS(ITEM_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_LOT_OID ON DCEREPORT_OUTPUT_ACTUALS(LOT_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_CNTNR_D ON DCEREPORT_OUTPUT_ACTUALS(CONTAINER_OID)
/

CREATE INDEX IREPORT_OUTPT_CTLS_NST_CNTNR_D ON DCEREPORT_OUTPUT_ACTUALS(NEST_CONTAINER_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_EMPLY_D ON DCEREPORT_OUTPUT_ACTUALS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_OUTPUT_ACTUALS_DEVIC_D ON DCEREPORT_OUTPUT_ACTUALS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_INSTRUCTIONTASKS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_INSTRUCTIONTASKS
(
  OID                  NUMBER(19) NOT NULL,
  TYPE                 NUMBER(10),
  STATUS               NUMBER(10),
  INSTRUCTION_OID      NUMBER(19),
  INSTRUCTION_TYPE     VARCHAR2(25 CHAR),
  DTSSCHEDULEDSTART    DATE,
  DTSSCHEDULEDSTOP     DATE,
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_INSTRUCTIONTASKS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_INSTRCTNTSKS_NSTRCTN_D ON DCEREPORT_INSTRUCTIONTASKS(INSTRUCTION_OID)
/

