BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DEVICE_LOGINS DROP CONSTRAINT FK_REPORT_DEVICE_LOGINS_DEVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DEVICE_LOGINS ADD CONSTRAINT FK_REPORT_DEVICE_LOGINS_DEVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DEVICE_LOGINS DROP CONSTRAINT FK_REPORT_DEVICE_LOGINS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DEVICE_LOGINS ADD CONSTRAINT FK_REPORT_DEVICE_LOGINS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDORDERS DROP CONSTRAINT FK_REPORT_INBOUNDORDERS_CRRR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDORDERS ADD CONSTRAINT FK_REPORT_INBOUNDORDERS_CRRR_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDORDERS DROP CONSTRAINT FK_REPORT_INBOUNDORDRS_CSTMR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDORDERS ADD CONSTRAINT FK_REPORT_INBOUNDORDRS_CSTMR_D FOREIGN KEY (CUSTOMER_OID) REFERENCES DCEREPORT_CUSTOMERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDORDERS DROP CONSTRAINT FK_REPORT_INBOUNDORDRS_SPPLR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDORDERS ADD CONSTRAINT FK_REPORT_INBOUNDORDRS_SPPLR_D FOREIGN KEY (SUPPLIER_OID) REFERENCES DCEREPORT_SUPPLIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDORDERS DROP CONSTRAINT FK_REPORT_INBOUNDRDRS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDORDERS ADD CONSTRAINT FK_REPORT_INBOUNDRDRS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDLINES DROP CONSTRAINT FK_REPORT_INBOUNDLNS_NBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDLINES ADD CONSTRAINT FK_REPORT_INBOUNDLNS_NBNDRDR_D FOREIGN KEY (INBOUNDORDER_OID) REFERENCES DCEREPORT_INBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUNDLINES DROP CONSTRAINT FK_REPORT_INBOUNDLINES_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUNDLINES ADD CONSTRAINT FK_REPORT_INBOUNDLINES_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOUND_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOUND_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOUND_ACTULS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOUND_ACTULS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOUND_ACTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOUND_ACTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOND_CTLS_NBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOND_CTLS_NBNDLN_D FOREIGN KEY (INBOUNDLINE_OID) REFERENCES DCEREPORT_INBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBND_CTLS_NBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBND_CTLS_NBNDRDR_D FOREIGN KEY (INBOUNDORDER_OID) REFERENCES DCEREPORT_INBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOUND_ACTUALS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOUND_ACTUALS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOUND_ACTUALS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOUND_ACTUALS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_INBOND_CTLS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_INBOND_CTLS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRERCPT_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRERCPT_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRERECEPT_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRERECEPT_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRERECPT_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRERECPT_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRRCPT_CTLS_NBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRRCPT_CTLS_NBNDLN_D FOREIGN KEY (INBOUNDLINE_OID) REFERENCES DCEREPORT_INBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPRT_PRRCPT_CTLS_NBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPRT_PRRCPT_CTLS_NBNDRDR_D FOREIGN KEY (INBOUNDORDER_OID) REFERENCES DCEREPORT_INBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRERECEIPT_CTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRERECEIPT_CTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS DROP CONSTRAINT FK_REPORT_PRERECEIPT_CTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRERECEIPT_ACTUALS ADD CONSTRAINT FK_REPORT_PRERECEIPT_CTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUTLINES DROP CONSTRAINT FK_DCEREPORT_PUTLINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUTLINES ADD CONSTRAINT FK_DCEREPORT_PUTLINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUTLINES DROP CONSTRAINT FK_REPORT_PUTLINES_PUTORDER_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUTLINES ADD CONSTRAINT FK_REPORT_PUTLINES_PUTORDER_OD FOREIGN KEY (PUTORDER_OID) REFERENCES DCEREPORT_PUTORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT F_RPRT_PT_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT F_RPRT_PT_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_PUTLIN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_PUTLIN_D FOREIGN KEY (PUTLINE_OID) REFERENCES DCEREPORT_PUTLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_PUTRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_PUTRDR_D FOREIGN KEY (PUTORDER_OID) REFERENCES DCEREPORT_PUTORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTULS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTULS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPORT_PUT_ACTUALS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPORT_PUT_ACTUALS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PUT_ACTUALS DROP CONSTRAINT FK_REPRT_PT_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PUT_ACTUALS ADD CONSTRAINT FK_REPRT_PT_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CROSSDOCK_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CROSSDOCK_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CROSSDCK_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CROSSDCK_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FRPRT_CRSSDCK_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FRPRT_CRSSDCK_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT F_RPRT_CRSSDCK_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT F_RPRT_CRSSDCK_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT F_CRSSDCK_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT F_CRSSDCK_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CROSSDOCK_ACTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CROSSDOCK_ACTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CROSSDOCK_ACTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CROSSDOCK_ACTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CROSSDCK_CTLS_PTLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CROSSDCK_CTLS_PTLN_D FOREIGN KEY (PUTLINE_OID) REFERENCES DCEREPORT_PUTLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPORT_CRSSDCK_CTLS_PTRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPORT_CRSSDCK_CTLS_PTRDR_D FOREIGN KEY (PUTORDER_OID) REFERENCES DCEREPORT_PUTORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_RPRT_CRSSDCK_CTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_RPRT_CRSSDCK_CTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FK_REPRT_CRSSDCK_CTLS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FK_REPRT_CRSSDCK_CTLS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS DROP CONSTRAINT FRT_CRSSDCK_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CROSSDOCK_ACTUALS ADD CONSTRAINT FRT_CRSSDCK_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUNDORDERS DROP CONSTRAINT FK_REPORT_OUTBOUNDORDRS_CRRR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUNDORDERS ADD CONSTRAINT FK_REPORT_OUTBOUNDORDRS_CRRR_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUNDORDERS DROP CONSTRAINT FK_REPORT_OUTBOUNDRDRS_CSTMR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUNDORDERS ADD CONSTRAINT FK_REPORT_OUTBOUNDRDRS_CSTMR_D FOREIGN KEY (CUSTOMER_OID) REFERENCES DCEREPORT_CUSTOMERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUNDLINES DROP CONSTRAINT FK_REPORT_OUTBOUNDLINES_ITEM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUNDLINES ADD CONSTRAINT FK_REPORT_OUTBOUNDLINES_ITEM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUNDLINES DROP CONSTRAINT FK_REPORT_OUTBOUNDLINES_LOT_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUNDLINES ADD CONSTRAINT FK_REPORT_OUTBOUNDLINES_LOT_OD FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUNDLINES DROP CONSTRAINT FK_REPORT_OUTBONDLNS_TBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUNDLINES ADD CONSTRAINT FK_REPORT_OUTBONDLNS_TBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBOND_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBOND_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBOUND_ACTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBOUND_ACTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBOUND_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBOUND_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBOUND_ACTULS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBOUND_ACTULS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBOUND_ACTULS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBOUND_ACTULS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBND_CTLS_TBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBND_CTLS_TBNDLN_D FOREIGN KEY (OUTBOUNDLINE_OID) REFERENCES DCEREPORT_OUTBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OTBND_CTLS_TBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OTBND_CTLS_TBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS DROP CONSTRAINT FK_REPORT_OUTBND_CTLS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTBOUND_ACTUALS ADD CONSTRAINT FK_REPORT_OUTBND_CTLS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICKLINES DROP CONSTRAINT FK_REPORT_PICKLINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICKLINES ADD CONSTRAINT FK_REPORT_PICKLINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICKLINES DROP CONSTRAINT FK_DCEREPORT_PICKLINES_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICKLINES ADD CONSTRAINT FK_DCEREPORT_PICKLINES_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICKLINES DROP CONSTRAINT FK_REPRT_PCKLNS_PCKRDR_D_RDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICKLINES ADD CONSTRAINT FK_REPRT_PCKLNS_PCKRDR_D_RDR_D FOREIGN KEY (PICKORDER_OID, ORDER_OID) REFERENCES DCEREPORT_PICKORDERS(OID, ORDER_OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICKLINES DROP CONSTRAINT FK_REPORT_PICKLINES_QCSTATUS_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICKLINES ADD CONSTRAINT FK_REPORT_PICKLINES_QCSTATUS_D FOREIGN KEY (QCSTATUS_OID) REFERENCES DCEREPORT_QCSTATUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTUALS_DEVIC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTUALS_DEVIC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTUALS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTUALS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PCK_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PCK_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FRPRT_PCK_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FRPRT_PCK_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTUALS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTUALS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_REPORT_PICK_ACTULS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_REPORT_PICK_ACTULS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PICK_ACTUALS DROP CONSTRAINT FK_RPRT_PCK_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PICK_ACTUALS ADD CONSTRAINT FK_RPRT_PCK_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPORT_TRANSFER_ACTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPORT_TRANSFER_ACTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPORT_TRANSFER_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPORT_TRANSFER_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT F_RPRT_TRNSFR_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT F_RPRT_TRNSFR_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_RPRT_TRNSFR_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_RPRT_TRNSFR_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FT_TRNSFR_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FT_TRNSFR_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPORT_TRANSFER_ACTULS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPORT_TRANSFER_ACTULS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPORT_TRANSFER_ACTULS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPORT_TRANSFER_ACTULS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPRT_TRNSFR_CTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPRT_TRNSFR_CTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FK_REPORT_TRNSFR_CTLS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FK_REPORT_TRNSFR_CTLS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TRANSFER_ACTUALS DROP CONSTRAINT FPRT_TRNSFR_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TRANSFER_ACTUALS ADD CONSTRAINT FPRT_TRNSFR_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_BACKORDERLINES DROP CONSTRAINT FK_REPORT_BACKORDERLINES_ITM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_BACKORDERLINES ADD CONSTRAINT FK_REPORT_BACKORDERLINES_ITM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_BACKORDERLINES DROP CONSTRAINT FK_REPORT_BACKORDERLINES_LOT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_BACKORDERLINES ADD CONSTRAINT FK_REPORT_BACKORDERLINES_LOT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_BACKORDERLINES DROP CONSTRAINT FK_REPORT_BACKORDRLNS_QCSTTS_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_BACKORDERLINES ADD CONSTRAINT FK_REPORT_BACKORDRLNS_QCSTTS_D FOREIGN KEY (QCSTATUS_OID) REFERENCES DCEREPORT_QCSTATUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKORDERS DROP CONSTRAINT FK_REPORT_PACKORDERS_TBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKORDERS ADD CONSTRAINT FK_REPORT_PACKORDERS_TBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKORDERS DROP CONSTRAINT FK_REPORT_PACKRDRS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKORDERS ADD CONSTRAINT FK_REPORT_PACKRDRS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKLINES DROP CONSTRAINT FK_REPORT_PACKLINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKLINES ADD CONSTRAINT FK_REPORT_PACKLINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKLINES DROP CONSTRAINT FK_DCEREPORT_PACKLINES_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKLINES ADD CONSTRAINT FK_DCEREPORT_PACKLINES_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKLINES DROP CONSTRAINT FK_REPORT_PACKLINES_OUTBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKLINES ADD CONSTRAINT FK_REPORT_PACKLINES_OUTBNDLN_D FOREIGN KEY (OUTBOUNDLINE_OID) REFERENCES DCEREPORT_OUTBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKLINES DROP CONSTRAINT FK_REPORT_PACKLINES_OTBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKLINES ADD CONSTRAINT FK_REPORT_PACKLINES_OTBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACKLINES DROP CONSTRAINT FK_REPORT_PACKLINES_PACKORDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACKLINES ADD CONSTRAINT FK_REPORT_PACKLINES_PACKORDR_D FOREIGN KEY (PACKORDER_OID) REFERENCES DCEREPORT_PACKORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTUALS_DEVIC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTUALS_DEVIC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTUALS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTUALS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PCK_CTLS_FRM_CNTNR_0'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PCK_CTLS_FRM_CNTNR_0 FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FRPRT_PCK_CTLS_FRM_NST_CNTNR_0'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FRPRT_PCK_CTLS_FRM_NST_CNTNR_0 FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTUALS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTUALS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTUALS_PCKLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTUALS_PCKLN_D FOREIGN KEY (PACKLINE_OID) REFERENCES DCEREPORT_PACKLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTULS_PCKRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTULS_PCKRDR_D FOREIGN KEY (PACKORDER_OID) REFERENCES DCEREPORT_PACKORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_REPORT_PACK_ACTULS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_REPORT_PACK_ACTULS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PACK_ACTUALS DROP CONSTRAINT FK_RPRT_PCK_CTLS_T_NST_CNTNR_0'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PACK_ACTUALS ADD CONSTRAINT FK_RPRT_PCK_CTLS_T_NST_CNTNR_0 FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DELIVERYORDERS DROP CONSTRAINT FK_REPORT_DELIVERYORDRS_CRRR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DELIVERYORDERS ADD CONSTRAINT FK_REPORT_DELIVERYORDRS_CRRR_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPORDERS DROP CONSTRAINT FK_REPORT_SHIPORDERS_CARRIER_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPORDERS ADD CONSTRAINT FK_REPORT_SHIPORDERS_CARRIER_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPORDERS DROP CONSTRAINT FK_REPORT_SHIPORDRS_DLVRYRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPORDERS ADD CONSTRAINT FK_REPORT_SHIPORDRS_DLVRYRDR_D FOREIGN KEY (DELIVERYORDER_OID) REFERENCES DCEREPORT_DELIVERYORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPORDERS DROP CONSTRAINT FK_REPORT_SHIPORDERS_TO_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPORDERS ADD CONSTRAINT FK_REPORT_SHIPORDERS_TO_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPLINES DROP CONSTRAINT FK_REPORT_SHIPLINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPLINES ADD CONSTRAINT FK_REPORT_SHIPLINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPLINES DROP CONSTRAINT FK_REPORT_SHIPLINES_OUTBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPLINES ADD CONSTRAINT FK_REPORT_SHIPLINES_OUTBNDLN_D FOREIGN KEY (OUTBOUNDLINE_OID) REFERENCES DCEREPORT_OUTBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPLINES DROP CONSTRAINT FK_REPORT_SHIPLINES_OTBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPLINES ADD CONSTRAINT FK_REPORT_SHIPLINES_OTBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIPLINES DROP CONSTRAINT FK_REPORT_SHIPLINES_SHIPORDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIPLINES ADD CONSTRAINT FK_REPORT_SHIPLINES_SHIPORDR_D FOREIGN KEY (SHIPORDER_OID) REFERENCES DCEREPORT_SHIPORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_DEVIC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_DEVIC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTULS_TBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTULS_TBNDLN_D FOREIGN KEY (OUTBOUNDLINE_OID) REFERENCES DCEREPORT_OUTBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTLS_TBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTLS_TBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTUALS_SHPLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTUALS_SHPLN_D FOREIGN KEY (SHIPLINE_OID) REFERENCES DCEREPORT_SHIPLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTULS_SHPRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTULS_SHPRDR_D FOREIGN KEY (SHIPORDER_OID) REFERENCES DCEREPORT_SHIPORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHIP_ACTUALS DROP CONSTRAINT FK_REPORT_SHIP_ACTULS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHIP_ACTUALS ADD CONSTRAINT FK_REPORT_SHIP_ACTULS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPORT_REPLENISH_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPORT_REPLENISH_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPORT_REPLENSH_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPORT_REPLENSH_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT F_RPRT_RPLNSH_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT F_RPRT_RPLNSH_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_RPRT_RPLNSH_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_RPRT_RPLNSH_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FT_RPLNSH_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FT_RPLNSH_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPORT_REPLENISH_ACTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPORT_REPLENISH_ACTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPORT_REPLENISH_ACTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPORT_REPLENISH_ACTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPRT_RPLNSH_CTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPRT_RPLNSH_CTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FK_REPORT_RPLNSH_CTLS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FK_REPORT_RPLNSH_CTLS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REPLENISH_ACTUALS DROP CONSTRAINT FPRT_RPLNSH_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REPLENISH_ACTUALS ADD CONSTRAINT FPRT_RPLNSH_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_REPORT_TASKS_CONTAINER_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_REPORT_TASKS_CONTAINER_OID FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_DCEREPORT_TASKS_DEVICE_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_DCEREPORT_TASKS_DEVICE_OID FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_REPORT_TASKS_EMPLOYEE_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_REPORT_TASKS_EMPLOYEE_OID FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_REPORT_TASKS_FROM_LOCATIN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_REPORT_TASKS_FROM_LOCATIN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_DCEREPORT_TASKS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_DCEREPORT_TASKS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_DCEREPORT_TASKS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_DCEREPORT_TASKS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_DCEREPORT_TASKS_REASON_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_DCEREPORT_TASKS_REASON_OID FOREIGN KEY (REASON_OID) REFERENCES DCEREPORT_TASKREASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_REPORT_TASKS_TO_LOCATION_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_REPORT_TASKS_TO_LOCATION_OD FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TASKS DROP CONSTRAINT FK_REPORT_TASKS_WORKZONE_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TASKS ADD CONSTRAINT FK_REPORT_TASKS_WORKZONE_OID FOREIGN KEY (WORKZONE_OID) REFERENCES DCEREPORT_WORKZONES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_LOCATIONS DROP CONSTRAINT FK_REPORT_LOCATIONS_WAREHOUS_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_LOCATIONS ADD CONSTRAINT FK_REPORT_LOCATIONS_WAREHOUS_D FOREIGN KEY (WAREHOUSE_OID) REFERENCES DCEREPORT_WAREHOUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTUALS_DEVIC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTUALS_DEVIC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTUALS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTUALS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOV_CTLS_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOV_CTLS_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT F_RPRT_MV_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT F_RPRT_MV_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTUALS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTUALS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTLS_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTLS_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPORT_MOVE_ACTULS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPORT_MOVE_ACTULS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MOVE_ACTUALS DROP CONSTRAINT FK_REPRT_MV_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MOVE_ACTUALS ADD CONSTRAINT FK_REPRT_MV_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTUALS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTUALS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTUALS_DEVIC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTUALS_DEVIC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTUALS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTUALS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_CTLS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_CTLS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FRPRT_NST_CTLS_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FRPRT_NST_CTLS_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTUALS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTUALS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTUALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTUALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_REPORT_NEST_ACTULS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_REPORT_NEST_ACTULS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_NEST_ACTUALS DROP CONSTRAINT FK_RPRT_NST_CTLS_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_NEST_ACTUALS ADD CONSTRAINT FK_RPRT_NST_CTLS_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPORT_NVNTRY_DJSTS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPORT_NVNTRY_DJSTS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPORT_INVENTRY_DJSTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPORT_INVENTRY_DJSTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPORT_INVNTRY_DJSTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPORT_INVNTRY_DJSTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT F_RPRT_NVNTRY_DJSTS_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT F_RPRT_NVNTRY_DJSTS_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPORT_INVENTORY_DJSTS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPORT_INVENTORY_DJSTS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPORT_INVENTORY_DJSTS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPORT_INVENTORY_DJSTS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FRPRT_NVNTRY_DJSTS_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FRPRT_NVNTRY_DJSTS_NST_CNTNR_D FOREIGN KEY (NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS DROP CONSTRAINT FK_REPRT_NVNTRY_DJSTS_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INVENTORY_ADJUSTS ADD CONSTRAINT FK_REPRT_NVNTRY_DJSTS_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACES_CARRIR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACES_CARRIR_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSTTRCS_CNTNR_TYP_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSTTRCS_CNTNR_TYP_D FOREIGN KEY (CONTAINER_TYPE_OID) REFERENCES DCEREPORT_CONTAINER_TYPES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACES_CUSTMR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACES_CUSTMR_D FOREIGN KEY (CUSTOMER_OID) REFERENCES DCEREPORT_CUSTOMERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACES_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACES_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACS_NBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACS_NBNDRDR_D FOREIGN KEY (INBOUNDORDER_OID) REFERENCES DCEREPORT_INBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACES_SHPRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACES_SHPRDR_D FOREIGN KEY (SHIPORDER_OID) REFERENCES DCEREPORT_SHIPORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ASSETTRACES DROP CONSTRAINT FK_REPORT_ASSETTRACES_SUPPLR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ASSETTRACES ADD CONSTRAINT FK_REPORT_ASSETTRACES_SUPPLR_D FOREIGN KEY (SUPPLIER_OID) REFERENCES DCEREPORT_SUPPLIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_ORDERS DROP CONSTRAINT FK_REPORT_MTO_ORDERS_TBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_ORDERS ADD CONSTRAINT FK_REPORT_MTO_ORDERS_TBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_ORDERS DROP CONSTRAINT FK_REPORT_MTO_RDRS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_ORDERS ADD CONSTRAINT FK_REPORT_MTO_RDRS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_ORDERS DROP CONSTRAINT FK_REPORT_MTS_RDRS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_ORDERS ADD CONSTRAINT FK_REPORT_MTS_RDRS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_LINES DROP CONSTRAINT FK_REPORT_MTO_LINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_LINES ADD CONSTRAINT FK_REPORT_MTO_LINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_LINES DROP CONSTRAINT FK_DCEREPORT_MTO_LINES_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_LINES ADD CONSTRAINT FK_DCEREPORT_MTO_LINES_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_LINES DROP CONSTRAINT FK_REPORT_MTO_LINES_MTO_ORDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_LINES ADD CONSTRAINT FK_REPORT_MTO_LINES_MTO_ORDR_D FOREIGN KEY (MTO_ORDER_OID) REFERENCES DCEREPORT_MTO_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_LINES DROP CONSTRAINT FK_REPORT_MTO_LINES_OUTBNDLN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_LINES ADD CONSTRAINT FK_REPORT_MTO_LINES_OUTBNDLN_D FOREIGN KEY (OUTBOUNDLINE_OID) REFERENCES DCEREPORT_OUTBOUNDLINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_LINES DROP CONSTRAINT FK_REPORT_MTO_LINES_OTBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_LINES ADD CONSTRAINT FK_REPORT_MTO_LINES_OTBNDRDR_D FOREIGN KEY (OUTBOUNDORDER_OID) REFERENCES DCEREPORT_OUTBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_LINES DROP CONSTRAINT FK_REPORT_MTS_LINES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_LINES ADD CONSTRAINT FK_REPORT_MTS_LINES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_LINES DROP CONSTRAINT FK_DCEREPORT_MTS_LINES_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_LINES ADD CONSTRAINT FK_DCEREPORT_MTS_LINES_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_LINES DROP CONSTRAINT FK_REPORT_MTS_LINES_MTS_ORDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_LINES ADD CONSTRAINT FK_REPORT_MTS_LINES_MTS_ORDR_D FOREIGN KEY (MTS_ORDER_OID) REFERENCES DCEREPORT_MTS_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_NPT_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_NPT_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_INPUT_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_INPUT_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_INPT_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_INPT_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_INPUT_ACTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_INPUT_ACTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_INPT_CTLS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_INPT_CTLS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_INPUT_ACTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_INPUT_ACTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_NPT_CTLS_MT_LN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_NPT_CTLS_MT_LN_D FOREIGN KEY (MTO_LINE_OID) REFERENCES DCEREPORT_MTO_LINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MT_NPT_CTLS_MT_RDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MT_NPT_CTLS_MT_RDR_D FOREIGN KEY (MTO_ORDER_OID) REFERENCES DCEREPORT_MTO_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS DROP CONSTRAINT F_RPRT_MT_NPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_INPUT_ACTUALS ADD CONSTRAINT F_RPRT_MT_NPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_NPT_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_NPT_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_INPUT_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_INPUT_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_INPT_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_INPT_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_INPUT_ACTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_INPUT_ACTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_INPT_CTLS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_INPT_CTLS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_INPUT_ACTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_INPUT_ACTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_REPRT_MTS_NPT_CTLS_MTS_LN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_REPRT_MTS_NPT_CTLS_MTS_LN_D FOREIGN KEY (MTS_LINE_OID) REFERENCES DCEREPORT_MTS_LINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FK_RPRT_MTS_NPT_CTLS_MTS_RDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FK_RPRT_MTS_NPT_CTLS_MTS_RDR_D FOREIGN KEY (MTS_ORDER_OID) REFERENCES DCEREPORT_MTS_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS DROP CONSTRAINT FRPRT_MTS_NPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_INPUT_ACTUALS ADD CONSTRAINT FRPRT_MTS_NPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_TPT_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_TPT_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_OUTPT_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_OUTPT_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_OTPT_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_OTPT_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_OUTPUT_CTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_OUTPUT_CTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_OTPT_CTLS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_OTPT_CTLS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_OUTPUT_CTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_OUTPUT_CTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTO_TPT_CTLS_MT_LN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTO_TPT_CTLS_MT_LN_D FOREIGN KEY (MTO_LINE_OID) REFERENCES DCEREPORT_MTO_LINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MT_TPT_CTLS_MT_RDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MT_TPT_CTLS_MT_RDR_D FOREIGN KEY (MTO_ORDER_OID) REFERENCES DCEREPORT_MTO_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS DROP CONSTRAINT F_RPRT_MT_TPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTO_OUTPUT_ACTUALS ADD CONSTRAINT F_RPRT_MT_TPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_TPT_CTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_TPT_CTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_OUTPT_CTLS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_OUTPT_CTLS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_OTPT_CTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_OTPT_CTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_OUTPUT_CTLS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_OUTPUT_CTLS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_OTPT_CTLS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_OTPT_CTLS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_MTS_OUTPUT_CTLS_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_MTS_OUTPUT_CTLS_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPRT_MTS_TPT_CTLS_MTS_LN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPRT_MTS_TPT_CTLS_MTS_LN_D FOREIGN KEY (MTS_LINE_OID) REFERENCES DCEREPORT_MTS_LINES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FK_RPRT_MTS_TPT_CTLS_MTS_RDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FK_RPRT_MTS_TPT_CTLS_MTS_RDR_D FOREIGN KEY (MTS_ORDER_OID) REFERENCES DCEREPORT_MTS_ORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS DROP CONSTRAINT FRPRT_MTS_TPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MTS_OUTPUT_ACTUALS ADD CONSTRAINT FRPRT_MTS_TPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_CARRIR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_CARRIR_D FOREIGN KEY (CARRIER_OID) REFERENCES DCEREPORT_CARRIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_CONTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_CONTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_CUSTMR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_CUSTMR_D FOREIGN KEY (CUSTOMER_OID) REFERENCES DCEREPORT_CUSTOMERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTIN_NBNDRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTIN_NBNDRDR_D FOREIGN KEY (INBOUNDORDER_OID) REFERENCES DCEREPORT_INBOUNDORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTN_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTN_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_NSPCTN_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_NSPCTN_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPCTN_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPCTN_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT F_BJTRP_NSPCTN_QLTYCNTRLSTTS_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT F_BJTRP_NSPCTN_QLTYCNTRLSTTS_D FOREIGN KEY (QUALITYCONTROLSTATUS_OID) REFERENCES DCEREPORT_QCSTATUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTION DROP CONSTRAINT FK_OBJTREP_INSPECTION_SUPPLR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTION ADD CONSTRAINT FK_OBJTREP_INSPECTION_SUPPLR_D FOREIGN KEY (SUPPLIER_OID) REFERENCES DCEREPORT_SUPPLIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_CHECKINSTR DROP CONSTRAINT F_BJTRP_NSPC_CHCKNSTR_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_CHECKINSTR ADD CONSTRAINT F_BJTRP_NSPC_CHCKNSTR_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INPUTINSTR DROP CONSTRAINT FK_BJTRP_NSPC_NPTNSTR_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INPUTINSTR ADD CONSTRAINT FK_BJTRP_NSPC_NPTNSTR_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INPUTINSTR DROP CONSTRAINT FK_OBJTREP_INSPEC_INPTNSTR_M_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INPUTINSTR ADD CONSTRAINT FK_OBJTREP_INSPEC_INPTNSTR_M_D FOREIGN KEY (UOM_OID) REFERENCES DCEREPORT_UOMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEININSTR DROP CONSTRAINT FBJTRP_NSPC_SMPLNNSTR_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEININSTR ADD CONSTRAINT FBJTRP_NSPC_SMPLNNSTR_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT DROP CONSTRAINT FK_OBJTRP_NSPC_NSPCTNVNT_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT ADD CONSTRAINT FK_OBJTRP_NSPC_NSPCTNVNT_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT DROP CONSTRAINT FK_BJTRP_NSPC_NSPCTNVNT_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT ADD CONSTRAINT FK_BJTRP_NSPC_NSPCTNVNT_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT DROP CONSTRAINT FBJTRP_NSPC_NSPCTNVNT_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT ADD CONSTRAINT FBJTRP_NSPC_NSPCTNVNT_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT DROP CONSTRAINT FJTRP_NSPC_NSPCTNVNT_NSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT ADD CONSTRAINT FJTRP_NSPC_NSPCTNVNT_NSTRCTN_D FOREIGN KEY (INSTRUCTION_OID) REFERENCES OBJTREP_INSPECTIONINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT DROP CONSTRAINT FK_BJTRP_NSPC_NSPCTNVNT_RSLT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPECTIONEVENT ADD CONSTRAINT FK_BJTRP_NSPC_NSPCTNVNT_RSLT_D FOREIGN KEY (RESULT_OID) REFERENCES OBJTREP_INSPEC_INSPRESULT(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FK_OBJTREP_INSPC_SMPLVNT_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FK_OBJTREP_INSPC_SMPLVNT_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FK_OBJTREP_NSPC_SMPLVNT_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FK_OBJTREP_NSPC_SMPLVNT_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FJTRP_NSPC_SMPLVNT_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FJTRP_NSPC_SMPLVNT_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FK_BJTRP_NSPC_SMPLVNT_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FK_BJTRP_NSPC_SMPLVNT_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FJTRP_NSPC_SMPLVNT_NSPCTNVNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FJTRP_NSPC_SMPLVNT_NSPCTNVNT_D FOREIGN KEY (INSPECTIONEVENT_OID) REFERENCES OBJTREP_INSPEC_INSPECTIONEVENT(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT F_BJTRP_NSPC_SMPLVNT_NSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT F_BJTRP_NSPC_SMPLVNT_NSTRCTN_D FOREIGN KEY (INSTRUCTION_OID) REFERENCES OBJTREP_INSPECTIONINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FK_OBJTREP_NSPC_SMPLVNT_SMPL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FK_OBJTREP_NSPC_SMPLVNT_SMPL_D FOREIGN KEY (SAMPLE_OID) REFERENCES OBJTREP_SAMPLES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT F_BJTRP_NSPC_SMPLVNT_SRCLCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT F_BJTRP_NSPC_SMPLVNT_SRCLCTN_D FOREIGN KEY (SOURCELOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT DROP CONSTRAINT FBJTRP_NSPC_SMPLVNT_TRGTLCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_SAMPLEEVENT ADD CONSTRAINT FBJTRP_NSPC_SMPLVNT_TRGTLCTN_D FOREIGN KEY (TARGETLOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_INSPRESULT DROP CONSTRAINT F_BJTRP_NSPC_NSPRSLT_NSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_INSPRESULT ADD CONSTRAINT F_BJTRP_NSPC_NSPRSLT_NSTRCTN_D FOREIGN KEY (INSTRUCTION_OID) REFERENCES OBJTREP_INSPECTIONINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SAMPLES DROP CONSTRAINT FK_OBJTREP_SAMPLES_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SAMPLES ADD CONSTRAINT FK_OBJTREP_SAMPLES_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SAMPLES DROP CONSTRAINT FK_OBJTREP_SAMPLES_LOCATION_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SAMPLES ADD CONSTRAINT FK_OBJTREP_SAMPLES_LOCATION_OD FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SAMPLES DROP CONSTRAINT FK_OBJTREP_SAMPLES_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SAMPLES ADD CONSTRAINT FK_OBJTREP_SAMPLES_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SAMPLES DROP CONSTRAINT FK_OBJTREP_SAMPLES_SAMPLNSTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SAMPLES ADD CONSTRAINT FK_OBJTREP_SAMPLES_SAMPLNSTR_D FOREIGN KEY (SAMPLEINSTR_OID) REFERENCES OBJTREP_INSPEC_SAMPLEININSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_MEASUREMNTINSTR DROP CONSTRAINT FJTRP_NSPC_MSRMNTNSTR_NSPCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_MEASUREMNTINSTR ADD CONSTRAINT FJTRP_NSPC_MSRMNTNSTR_NSPCTN_D FOREIGN KEY (INSPECTION_OID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPEC_MEASUREMNTINSTR DROP CONSTRAINT FK_OBJTREP_NSPC_MSRMNTNSTR_M_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPEC_MEASUREMNTINSTR ADD CONSTRAINT FK_OBJTREP_NSPC_MSRMNTNSTR_M_D FOREIGN KEY (UOM_OID) REFERENCES DCEREPORT_UOMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_CONTAINER_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_CONTAINER_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_LOCATION_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_LOCATION_OD FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_QCSTATUS_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_QCSTATUS_OD FOREIGN KEY (QCSTATUS_OID) REFERENCES DCEREPORT_QCSTATUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALS DROP CONSTRAINT FK_OBJTREP_SERIALS_WAREHOUSE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALS ADD CONSTRAINT FK_OBJTREP_SERIALS_WAREHOUSE_D FOREIGN KEY (WAREHOUSE_OID) REFERENCES DCEREPORT_WAREHOUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_INVENTORYTRAC_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_INVENTORYTRAC_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_INVENTORYTRC_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_INVENTORYTRC_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_BJTRP_NVNTRYTRC_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_BJTRP_NVNTRYTRC_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTRP_NVNTRYTRC_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTRP_NVNTRYTRC_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FTRP_NVNTRYTRC_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FTRP_NVNTRYTRC_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_INVENTORYTRACE_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_INVENTORYTRACE_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_INVENTORYTRACE_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_INVENTORYTRACE_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_NVNTRYTRC_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_NVNTRYTRC_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_INVNTRYTRC_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_INVNTRYTRC_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INVENTORYTRACE DROP CONSTRAINT FBJTRP_NVNTRYTRC_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INVENTORYTRACE ADD CONSTRAINT FBJTRP_NVNTRYTRC_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_SERLNVNTRYTRC_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_SERLNVNTRYTRC_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_SRLNVNTRYTRC_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_SRLNVNTRYTRC_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FJTRP_SRLNVNTRYTRC_FRM_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FJTRP_SRLNVNTRYTRC_FRM_CNTNR_D FOREIGN KEY (FROM_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FBJTRP_SRLNVNTRYTRC_FRM_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FBJTRP_SRLNVNTRYTRC_FRM_LCTN_D FOREIGN KEY (FROM_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT F_SRLNVNTRYTRC_FRM_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT F_SRLNVNTRYTRC_FRM_NST_CNTNR_D FOREIGN KEY (FROM_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FJTRP_SRLNVNTRYTRC_NVNTRYTRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FJTRP_SRLNVNTRYTRC_NVNTRYTRC_D FOREIGN KEY (INVENTORYTRACE_OID) REFERENCES OBJTREP_INVENTORYTRACE(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_SERILNVNTRYTRC_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_SERILNVNTRYTRC_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_SERILNVNTRYTRC_LT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_SERILNVNTRYTRC_LT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_OBJTREP_SERLNVNTRYTRC_SRL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_OBJTREP_SERLNVNTRYTRC_SRL_D FOREIGN KEY (SERIAL_OID) REFERENCES OBJTREP_SERIALS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT F_BJTRP_SRLNVNTRYTRC_T_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT F_BJTRP_SRLNVNTRYTRC_T_CNTNR_D FOREIGN KEY (TO_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FK_BJTRP_SRLNVNTRYTRC_T_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FK_BJTRP_SRLNVNTRYTRC_T_LCTN_D FOREIGN KEY (TO_LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_SERIALINVENTORYTRACE DROP CONSTRAINT FRP_SRLNVNTRYTRC_T_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_SERIALINVENTORYTRACE ADD CONSTRAINT FRP_SRLNVNTRYTRC_T_NST_CNTNR_D FOREIGN KEY (TO_NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_PURCHASEORDERS DROP CONSTRAINT FK_OBJTREP_PURCHASRDRS_SPPLR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_PURCHASEORDERS ADD CONSTRAINT FK_OBJTREP_PURCHASRDRS_SPPLR_D FOREIGN KEY (SUPPLIER_OID) REFERENCES DCEREPORT_SUPPLIERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_PURCHASEORDERLINES DROP CONSTRAINT FK_OBJTREP_PURCHASERDRLNS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_PURCHASEORDERLINES ADD CONSTRAINT FK_OBJTREP_PURCHASERDRLNS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_PURCHASEORDERLINES DROP CONSTRAINT F_BJTRP_PRCHSRDRLNS_PRCHSRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_PURCHASEORDERLINES ADD CONSTRAINT F_BJTRP_PRCHSRDRLNS_PRCHSRDR_D FOREIGN KEY (PURCHASEORDER_OID) REFERENCES OBJTREP_PURCHASEORDERS(OID) DISABLE NOVALIDATE
/

