BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_EMPLOYEE_GROUPS DROP CONSTRAINT FK_REPORT_EMPLOYEE_GRPS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_EMPLOYEE_GROUPS ADD CONSTRAINT FK_REPORT_EMPLOYEE_GRPS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ITEMS DROP CONSTRAINT FK_DCEREPORT_ITEMS_UOM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ITEMS ADD CONSTRAINT FK_DCEREPORT_ITEMS_UOM_OID FOREIGN KEY (UOM_OID) REFERENCES DCEREPORT_UOMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_LOTS DROP CONSTRAINT FK_DCEREPORT_LOTS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_LOTS ADD CONSTRAINT FK_DCEREPORT_LOTS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_LOTS DROP CONSTRAINT FK_DCEREPORT_LOTS_QCSTATUS_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_LOTS ADD CONSTRAINT FK_DCEREPORT_LOTS_QCSTATUS_OID FOREIGN KEY (QCSTATUS_OID) REFERENCES DCEREPORT_QCSTATUSES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CONTAINERS DROP CONSTRAINT FK_REPORT_CONTANRS_CNTNR_TYP_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CONTAINERS ADD CONSTRAINT FK_REPORT_CONTANRS_CNTNR_TYP_D FOREIGN KEY (CONTAINER_TYPE_OID) REFERENCES DCEREPORT_CONTAINER_TYPES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CONTAINERS DROP CONSTRAINT FK_REPORT_CONTANRS_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CONTAINERS ADD CONSTRAINT FK_REPORT_CONTANRS_NST_CNTNR_D FOREIGN KEY (NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_COMMENTS DROP CONSTRAINT FK_REPORT_COMMENTS_EMPLOYEE_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_COMMENTS ADD CONSTRAINT FK_REPORT_COMMENTS_EMPLOYEE_OD FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ITEMPARAMETERS DROP CONSTRAINT FK_DCEREPORT_ITEMPARAMETERS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_LOTPARAMETERS DROP CONSTRAINT FK_DCEREPORT_LOTPARAMETERS_LOT_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ITEMPARAMETERS ADD CONSTRAINT FK_DCEREPORT_ITEMPARAMETERS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/
ALTER TABLE DCEREPORT_LOTPARAMETERS ADD CONSTRAINT FK_DCEREPORT_LOTPARAMETERS_LOT_OID FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/