BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_DEPT_EMPLOYEES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_DEPT_EMPLOYEES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  EMPLOYEE_OID         NUMBER(19),
  EMPLOYEE_NAME        VARCHAR2(64 CHAR),
  EMPLOYEE_FIRSTNAME   VARCHAR2(64 CHAR),
  EMP_DEP_LINK_DTSVALIDFROM DATE,
  EMP_DEP_LINK_DTSVALIDUNTIL DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_DEPT_EMPLOYEES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_DEPT_EMPLOYEES_MPLY_D ON OBJTREP_DEPT_EMPLOYEES(EMPLOYEE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_COSTCENTERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_COSTCENTERS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  ID                   VARCHAR2(64 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_COSTCENTERS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_PLANNED_ATTENDANCES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_PLANNED_ATTENDANCES
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  CATEGORY             VARCHAR2(64 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DAY_CODE_OID         NUMBER(19),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_PLANNED_ATTENDANCES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_PLANNED_TTNDNCS_MPLY_D ON DCEREPORT_PLANNED_ATTENDANCES(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_PLANND_TTNDNCS_DY_CD_D ON DCEREPORT_PLANNED_ATTENDANCES(DAY_CODE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_DAY_CODES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_DAY_CODES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(255 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  ID                   VARCHAR2(255 CHAR),
  UNIT                 VARCHAR2(3 CHAR),
  TYPE                 VARCHAR2(10 CHAR),
  BALANCE_CODE_OID     NUMBER(19),
  TRANSFER_FACTOR      NUMBER,
  TRANSFER_TYPE        VARCHAR2(9 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_DAY_CODES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_DAY_CODES_BALANCE_CD_D ON DCEREPORT_DAY_CODES(BALANCE_CODE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_BALANCE_CODES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_BALANCE_CODES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(255 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  ID                   VARCHAR2(255 CHAR),
  UNIT                 VARCHAR2(3 CHAR),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_BALANCE_CODES
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_DAY_COUNTERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_DAY_COUNTERS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DAY_CODE_OID         NUMBER(19),
  DTS                  DATE,
  DURATION             NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_DAY_COUNTERS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_DAY_COUNTERS_EMPLOY_D ON OBJTREP_DAY_COUNTERS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_DAY_COUNTERS_DAY_CD_D ON OBJTREP_DAY_COUNTERS(DAY_CODE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_DAYATTCNTRCOSTDTLS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_DAYATTCNTRCOSTDTLS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DAY_CODE_OID         NUMBER(19),
  COSTCENTER_OID       NUMBER(19),
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  DTS                  DATE,
  DURATION             NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_DAYATTCNTRCOSTDTLS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTRP_DYTTCNTRCSTDTLS_MPLY_D ON OBJTREP_DAYATTCNTRCOSTDTLS(EMPLOYEE_OID)
/

CREATE INDEX IBJTRP_DYTTCNTRCSTDTLS_DY_CD_D ON OBJTREP_DAYATTCNTRCOSTDTLS(DAY_CODE_OID)
/

CREATE INDEX ITRP_DYTTCNTRCSTDTLS_CSTCNTR_D ON OBJTREP_DAYATTCNTRCOSTDTLS(COSTCENTER_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_ANOMALYREASONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_ANOMALYREASONS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  TYPE                 NUMBER(10),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_ANOMALYREASONS
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_CLOCKINGEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_CLOCKINGEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  DTS                  DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_CLOCKINGEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_CLOCKINGEVENTS_MPLY_D ON OBJTREP_CLOCKINGEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_CLOCKINGEVENTS_DEVC_D ON OBJTREP_CLOCKINGEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_INFOEVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_INFOEVENTS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  DTS                  DATE,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_INFOEVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_INFOEVENTS_EMPLOYEE_D ON OBJTREP_INFOEVENTS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_INFOEVENTS_DEVICE_OID ON OBJTREP_INFOEVENTS(DEVICE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_COSTCENTEREVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_COSTCENTEREVENTS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DEVICE_OID           NUMBER(19),
  COSTCENTER_OID       NUMBER(19),
  DTS                  DATE,
  USRTXT1              VARCHAR2(255 CHAR),
  USRTXT2              VARCHAR2(255 CHAR),
  USRTXT3              VARCHAR2(255 CHAR),
  USRTXT4              VARCHAR2(255 CHAR),
  USRTXT5              VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_COSTCENTEREVENTS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_COSTCENTERVNTS_MPLY_D ON OBJTREP_COSTCENTEREVENTS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_COSTCENTEREVNTS_DVC_D ON OBJTREP_COSTCENTEREVENTS(DEVICE_OID)
/

CREATE INDEX IOBJTREP_CSTCNTRVNTS_CSTCNTR_D ON OBJTREP_COSTCENTEREVENTS(COSTCENTER_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_ACTUAL_ATTENDANCES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_ACTUAL_ATTENDANCES
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  CATEGORY             VARCHAR2(64 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DAY_CODE_OID         NUMBER(19),
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_ACTUAL_ATTENDANCES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_ACTUAL_TTNDNCS_MPLY_D ON OBJTREP_ACTUAL_ATTENDANCES(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_ACTUL_TTNDNCS_DY_CD_D ON OBJTREP_ACTUAL_ATTENDANCES(DAY_CODE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_ATTENDANCEPERIODS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_ATTENDANCEPERIODS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_ATTENDANCEPERIODS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_ATTENDANCEPRDS_MPLY_D ON OBJTREP_ATTENDANCEPERIODS(EMPLOYEE_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_BALANCE_COUNTERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_BALANCE_COUNTERS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  BALANCE_CODE_OID     NUMBER(19),
  PERIOD_OID           NUMBER(19),
  START_VALUE          NUMBER,
  END_VALUE            NUMBER,
  PLANNED_VALUE        NUMBER,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_BALANCE_COUNTERS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_BALANCE_CONTRS_MPLY_D ON OBJTREP_BALANCE_COUNTERS(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_BALNC_CNTRS_BLNC_CD_D ON OBJTREP_BALANCE_COUNTERS(BALANCE_CODE_OID)
/

CREATE INDEX IOBJTREP_BALANCE_COUNTRS_PRD_D ON OBJTREP_BALANCE_COUNTERS(PERIOD_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE OBJTREP_ANOMALIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE OBJTREP_ANOMALIES
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  REASON_OID           NUMBER(19),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTS                  DATE,
  DTSVALIDUNTIL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_OBJTREP_ANOMALIES
  PRIMARY KEY (OID)
)
/

CREATE INDEX IOBJTREP_ANOMALIES_EMPLOYEE_OD ON OBJTREP_ANOMALIES(EMPLOYEE_OID)
/

CREATE INDEX IOBJTREP_ANOMALIES_REASON_OID ON OBJTREP_ANOMALIES(REASON_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACCESS_OPERATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACCESS_OPERATIONS
(
  OID                  NUMBER(19) NOT NULL,
  EMPLOYEE_OID         NUMBER(19),
  ACCESSBADGE_OID      NUMBER(19),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSVALIDFROM         DATE,
  DTSVALIDUNTIL        DATE,
  STATUS               NUMBER(10),
  ACCESSREADERDEVICE_OID NUMBER(19),
  ACCESSGATE_OID       NUMBER(19),
  ACCESSAREA_OID       NUMBER(19),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ACCESS_OPERATIONS
  PRIMARY KEY (OID)
)
/

CREATE INDEX IREPORT_ACCESS_OPERATNS_MPLY_D ON DCEREPORT_ACCESS_OPERATIONS(EMPLOYEE_OID)
/

CREATE INDEX IREPORT_ACCESS_PRTNS_CCSSBDG_D ON DCEREPORT_ACCESS_OPERATIONS(ACCESSBADGE_OID)
/

CREATE INDEX IREPRT_CCSS_PRTNS_CCSSRDRDVC_D ON DCEREPORT_ACCESS_OPERATIONS(ACCESSREADERDEVICE_OID)
/

CREATE INDEX IREPORT_ACCESS_OPRTNS_CCSSGT_D ON DCEREPORT_ACCESS_OPERATIONS(ACCESSGATE_OID)
/

CREATE INDEX IREPORT_ACCESS_OPERTNS_CCSSR_D ON DCEREPORT_ACCESS_OPERATIONS(ACCESSAREA_OID)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACCESS_BADGES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACCESS_BADGES
(
  OID                  NUMBER(19) NOT NULL,
  ID                   VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  STATUS               VARCHAR2(7 CHAR),
  DTSSTART             DATE,
  DTSSTOP              DATE,
  DTSVALIDFROM         DATE,
  DTSVALIDUNITL        DATE,
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ACCESS_BADGES
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACCESS_READERDEVICES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACCESS_READERDEVICES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  ACCESSTYPE           VARCHAR2(3 CHAR),
  DEVICEADDRESS        VARCHAR2(64 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_REPORT_ACCESS_READERDEVICES
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACCESS_GATES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACCESS_GATES
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ACCESS_GATES
  PRIMARY KEY (OID)
)
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DCEREPORT_ACCESS_AREAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DCEREPORT_ACCESS_AREAS
(
  OID                  NUMBER(19) NOT NULL,
  NAME                 VARCHAR2(64 CHAR),
  DESCRIPTION          VARCHAR2(255 CHAR),
  EVACUATIONZONE       VARCHAR2(32 CHAR),
  DTSUPDATE            DATE,
  CONSTRAINT PK_DCEREPORT_ACCESS_AREAS
  PRIMARY KEY (OID)
)
/

