BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_TOOLS DROP CONSTRAINT FK_DCEREPORT_TOOLS_UOM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_TOOLS ADD CONSTRAINT FK_DCEREPORT_TOOLS_UOM_OID FOREIGN KEY (UOM_OID) REFERENCES DCEREPORT_UOMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_EQUIPMENTMODULES DROP CONSTRAINT FK_REPRT_QPMNTMDLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_EQUIPMENTMODULES ADD CONSTRAINT FK_REPRT_QPMNTMDLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_RESOURCETRAIN_RESRCS DROP CONSTRAINT FPRT_RSRCTRN_RSRCS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_RESOURCETRAIN_RESRCS ADD CONSTRAINT FPRT_RSRCTRN_RSRCS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DEPARTMENT_CHILDDEP DROP CONSTRAINT F_DPRTMNT_CHLDDP_CHLDDPRTMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DEPARTMENT_CHILDDEP ADD CONSTRAINT F_DPRTMNT_CHLDDP_CHLDDPRTMNT_D FOREIGN KEY (CHILDDEPARTMENT_OID) REFERENCES DCEREPORT_DEPARTMENTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DEPARTMENT_RESRCS DROP CONSTRAINT FPRT_DPRTMNT_RSRCS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DEPARTMENT_RESRCS ADD CONSTRAINT FPRT_DPRTMNT_RSRCS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS DROP CONSTRAINT FK_REPORT_PRODUCTIONPRTNS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS ADD CONSTRAINT FK_REPORT_PRODUCTIONPRTNS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS DROP CONSTRAINT F_RPRT_PRDCTNPRTNS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS ADD CONSTRAINT F_RPRT_PRDCTNPRTNS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS DROP CONSTRAINT F_RPRT_PRDCTNPRTNS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOPERATIONS ADD CONSTRAINT F_RPRT_PRDCTNPRTNS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES DROP CONSTRAINT FK_REPORT_PRODUCTIONP_QTS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES ADD CONSTRAINT FK_REPORT_PRODUCTIONP_QTS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES DROP CONSTRAINT FRPRT_PRDCTNP_QTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES ADD CONSTRAINT FRPRT_PRDCTNP_QTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES DROP CONSTRAINT F_RPRT_PRDCTNP_QTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONOP_QTIES ADD CONSTRAINT F_RPRT_PRDCTNP_QTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONORDERS DROP CONSTRAINT FK_REPORT_PRODUCTNRDRS_CSTMR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONORDERS ADD CONSTRAINT FK_REPORT_PRODUCTNRDRS_CSTMR_D FOREIGN KEY (CUSTOMER_OID) REFERENCES DCEREPORT_CUSTOMERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRODUCTIONORDERS DROP CONSTRAINT FK_REPORT_PRODUCTIONORDRS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRODUCTIONORDERS ADD CONSTRAINT FK_REPORT_PRODUCTIONORDRS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOPERATIONS DROP CONSTRAINT FK_REPORT_MACHINEOPERATNS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOPERATIONS ADD CONSTRAINT FK_REPORT_MACHINEOPERATNS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOPERATIONS DROP CONSTRAINT FK_REPRT_MCHNPRTNS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOPERATIONS ADD CONSTRAINT FK_REPRT_MCHNPRTNS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOPERATIONS DROP CONSTRAINT FK_RPRT_MCHNPRTNS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOPERATIONS ADD CONSTRAINT FK_RPRT_MCHNPRTNS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOPERATIONS DROP CONSTRAINT FK_REPRT_MCHNPRTNS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOPERATIONS ADD CONSTRAINT FK_REPRT_MCHNPRTNS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS DROP CONSTRAINT F_RPRT_MCHNP_SGMNTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS ADD CONSTRAINT F_RPRT_MCHNP_SGMNTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS DROP CONSTRAINT FRPRT_MCHNP_SGMNTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS ADD CONSTRAINT FRPRT_MCHNP_SGMNTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS DROP CONSTRAINT FPRT_MCHNP_SGMNTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS ADD CONSTRAINT FPRT_MCHNP_SGMNTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS DROP CONSTRAINT FRPRT_MCHNP_SGMNTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_SEGMENTS ADD CONSTRAINT FRPRT_MCHNP_SGMNTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_REPORT_MACHINEOP_QTIES_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_REPORT_MACHINEOP_QTIES_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_REPORT_MCHNP_QTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_REPORT_MCHNP_QTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_REPRT_MCHNP_QTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_REPRT_MCHNP_QTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_RPRT_MCHNP_QTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_RPRT_MCHNP_QTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_REPRT_MCHNP_QTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_REPRT_MCHNP_QTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MACHINEOP_QTIES DROP CONSTRAINT FK_REPORT_MACHINEOP_QTS_SHFT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MACHINEOP_QTIES ADD CONSTRAINT FK_REPORT_MACHINEOP_QTS_SHFT_D FOREIGN KEY (SHIFT_OID) REFERENCES DCEREPORT_SHIFTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPORT_DIRECT_TASKS_CTVTY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPORT_DIRECT_TASKS_CTVTY_D FOREIGN KEY (ACTIVITY_OID) REFERENCES DCEREPORT_ACTIVITIES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPORT_DIRECT_TASKS_EMPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPORT_DIRECT_TASKS_EMPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPORT_DIRECT_TASKS_ITEM_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPORT_DIRECT_TASKS_ITEM_OD FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPORT_DRCT_TSKS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPORT_DRCT_TSKS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPRT_DRCT_TSKS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPRT_DRCT_TSKS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_RPRT_DRCT_TSKS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_RPRT_DRCT_TSKS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASKS DROP CONSTRAINT FK_REPRT_DRCT_TSKS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASKS ADD CONSTRAINT FK_REPRT_DRCT_TSKS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT FRT_DRCT_TSK_SGMNTS_DRCT_TSK_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT FRT_DRCT_TSK_SGMNTS_DRCT_TSK_D FOREIGN KEY (DIRECT_TASK_OID) REFERENCES DCEREPORT_DIRECT_TASKS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT FK_REPORT_DRCT_TSK_SGMNTS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT FK_REPORT_DRCT_TSK_SGMNTS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT FRT_DRCT_TSK_SGMNTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT FRT_DRCT_TSK_SGMNTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT F_DRCT_TSK_SGMNTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT F_DRCT_TSK_SGMNTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT FT_DRCT_TSK_SGMNTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT FT_DRCT_TSK_SGMNTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS DROP CONSTRAINT FPRT_DRCT_TSK_SGMNTS_WRKCNTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_SEGMENTS ADD CONSTRAINT FPRT_DRCT_TSK_SGMNTS_WRKCNTR_D FOREIGN KEY (WORKCENTER_OID) REFERENCES DCEREPORT_WORKCENTERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT F_RPRT_DRCT_TSK_QTS_DRCT_TSK_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT F_RPRT_DRCT_TSK_QTS_DRCT_TSK_D FOREIGN KEY (DIRECT_TASK_OID) REFERENCES DCEREPORT_DIRECT_TASKS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT FK_REPORT_DIRECT_TASK_QTS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT FK_REPORT_DIRECT_TASK_QTS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT F_RPRT_DRCT_TSK_QTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT F_RPRT_DRCT_TSK_QTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT FPRT_DRCT_TSK_QTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT FPRT_DRCT_TSK_QTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT FRPRT_DRCT_TSK_QTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT FRPRT_DRCT_TSK_QTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT FK_REPORT_DIRCT_TSK_QTS_SHFT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT FK_REPORT_DIRCT_TSK_QTS_SHFT_D FOREIGN KEY (SHIFT_OID) REFERENCES DCEREPORT_SHIFTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES DROP CONSTRAINT FK_RPRT_DRCT_TSK_QTS_WRKCNTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DIRECT_TASK_QTIES ADD CONSTRAINT FK_RPRT_DRCT_TSK_QTS_WRKCNTR_D FOREIGN KEY (WORKCENTER_OID) REFERENCES DCEREPORT_WORKCENTERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INDIRECT_TASKS DROP CONSTRAINT FK_REPORT_INDIRECT_TSKS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INDIRECT_TASKS ADD CONSTRAINT FK_REPORT_INDIRECT_TSKS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INDIRECT_TASKS DROP CONSTRAINT FK_REPORT_NDRCT_TSKS_MNLPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INDIRECT_TASKS ADD CONSTRAINT FK_REPORT_NDRCT_TSKS_MNLPRTN_D FOREIGN KEY (MANUALOPERATION_OID) REFERENCES DCEREPORT_MANUALOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INDIRECT_TASKS DROP CONSTRAINT FK_RPRT_NDRCT_TSKS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INDIRECT_TASKS ADD CONSTRAINT FK_RPRT_NDRCT_TSKS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ALLOCATIONDETAILS DROP CONSTRAINT FK_REPORT_ALLOCATIONDTLS_TSK_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ALLOCATIONDETAILS ADD CONSTRAINT FK_REPORT_ALLOCATIONDTLS_TSK_D FOREIGN KEY (TASK_OID) REFERENCES DCEREPORT_TASKS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MAINTENANCE_TASKS DROP CONSTRAINT FK_REPORT_MAINTNNC_TSKS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MAINTENANCE_TASKS ADD CONSTRAINT FK_REPORT_MAINTNNC_TSKS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MAINTENANCE_TASKS DROP CONSTRAINT F_RPRT_MNTNNC_TSKS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MAINTENANCE_TASKS ADD CONSTRAINT F_RPRT_MNTNNC_TSKS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPORT_RJCTPRTNS_DRCT_TSK_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPORT_RJCTPRTNS_DRCT_TSK_D FOREIGN KEY (DIRECT_TASK_OID) REFERENCES DCEREPORT_DIRECT_TASKS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPORT_REJECTOPERTNS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPORT_REJECTOPERTNS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPORT_REJECTOPERATINS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPORT_REJECTOPERATINS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPORT_RJCTPRTNS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPORT_RJCTPRTNS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPRT_RJCTPRTNS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPRT_RJCTPRTNS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_RPRT_RJCTPRTNS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_RPRT_RJCTPRTNS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REJECTOPERATIONS DROP CONSTRAINT FK_REPORT_REJECTOPERATNS_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REJECTOPERATIONS ADD CONSTRAINT FK_REPORT_REJECTOPERATNS_RSN_D FOREIGN KEY (REASON_OID) REFERENCES DCEREPORT_REJECTREASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REWORKOPERATIONS DROP CONSTRAINT FK_REPORT_RWRKPRTNS_DRCT_TSK_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REWORKOPERATIONS ADD CONSTRAINT FK_REPORT_RWRKPRTNS_DRCT_TSK_D FOREIGN KEY (DIRECT_TASK_OID) REFERENCES DCEREPORT_DIRECT_TASKS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REWORKOPERATIONS DROP CONSTRAINT FK_REPORT_REWORKOPERTNS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REWORKOPERATIONS ADD CONSTRAINT FK_REPORT_REWORKOPERTNS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REWORKOPERATIONS DROP CONSTRAINT FK_REPORT_REWORKOPERATINS_TM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REWORKOPERATIONS ADD CONSTRAINT FK_REPORT_REWORKOPERATINS_TM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REWORKOPERATIONS DROP CONSTRAINT FK_REPORT_REWORKOPERATNS_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REWORKOPERATIONS ADD CONSTRAINT FK_REPORT_REWORKOPERATNS_RSN_D FOREIGN KEY (REASON_OID) REFERENCES DCEREPORT_REJECTREASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_REWORKOPERATIONS DROP CONSTRAINT FK_REPORT_RWRKPRTNS_RJCTPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_REWORKOPERATIONS ADD CONSTRAINT FK_REPORT_RWRKPRTNS_RJCTPRTN_D FOREIGN KEY (REJECTOPERATION_OID) REFERENCES DCEREPORT_REJECTOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ALARMS DROP CONSTRAINT FK_REPORT_ALARMS_EQUIPMNTMDL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ALARMS ADD CONSTRAINT FK_REPORT_ALARMS_EQUIPMNTMDL_D FOREIGN KEY (EQUIPMENTMODULE_OID) REFERENCES DCEREPORT_EQUIPMENTMODULES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ALARMS DROP CONSTRAINT FK_REPORT_ALARMS_PROCESSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ALARMS ADD CONSTRAINT FK_REPORT_ALARMS_PROCESSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS DROP CONSTRAINT FK_REPORT_INTERRUPTPRTNS_LRM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS ADD CONSTRAINT FK_REPORT_INTERRUPTPRTNS_LRM_D FOREIGN KEY (ALARM_OID) REFERENCES DCEREPORT_ALARMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS DROP CONSTRAINT FK_RPRT_NTRRPTPRTNS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS ADD CONSTRAINT FK_RPRT_NTRRPTPRTNS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS DROP CONSTRAINT F_RPRT_NTRRPTPRTNS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS ADD CONSTRAINT F_RPRT_NTRRPTPRTNS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS DROP CONSTRAINT FK_REPORT_INTERRUPTPRTNS_RSN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INTERRUPTOPERATIONS ADD CONSTRAINT FK_REPORT_INTERRUPTPRTNS_RSN_D FOREIGN KEY (REASON_OID) REFERENCES DCEREPORT_INTERRUPTREASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ISPRESENTOPERATIONS DROP CONSTRAINT FK_REPORT_ISPRESNTPRTNS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ISPRESENTOPERATIONS ADD CONSTRAINT FK_REPORT_ISPRESNTPRTNS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ISPRESENTOPERATIONS DROP CONSTRAINT F_RPRT_SPRSNTPRTNS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ISPRESENTOPERATIONS ADD CONSTRAINT F_RPRT_SPRSNTPRTNS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MES_EVENTS_DEVICE_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MES_EVENTS_DEVICE_OD FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MES_EVENTS_EMPLOYE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MES_EVENTS_EMPLOYE_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MES_EVENTS_ITEM_OID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MES_EVENTS_ITEM_OID FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MES_VNTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MES_VNTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MS_VNTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MS_VNTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MES_EVENTS DROP CONSTRAINT FK_REPORT_MES_VNTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MES_EVENTS ADD CONSTRAINT FK_REPORT_MES_VNTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS DROP CONSTRAINT FK_REPORT_PRTNRPRTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS ADD CONSTRAINT FK_REPORT_PRTNRPRTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS DROP CONSTRAINT FK_REPORT_OEEOPRTNRPRTS_RPRT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS ADD CONSTRAINT FK_REPORT_OEEOPRTNRPRTS_RPRT_D FOREIGN KEY (OEEREPORT_OID) REFERENCES DCEREPORT_OEEREPORTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS DROP CONSTRAINT FK_REPRT_PRTNRPRTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OEEOPERATIONREPORTS ADD CONSTRAINT FK_REPRT_PRTNRPRTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OEEREPORTS DROP CONSTRAINT FK_REPORT_OEERPRTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OEEREPORTS ADD CONSTRAINT FK_REPORT_OEERPRTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPINSTR DROP CONSTRAINT FK_REPORT_STPNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPINSTR ADD CONSTRAINT FK_REPORT_STPNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPINSTR DROP CONSTRAINT FK_REPORT_SETUPNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPINSTR ADD CONSTRAINT FK_REPORT_SETUPNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPINSTR DROP CONSTRAINT FK_REPORT_SETPNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPINSTR ADD CONSTRAINT FK_REPORT_SETPNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPINSTR DROP CONSTRAINT FK_REPORT_STPNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPINSTR ADD CONSTRAINT FK_REPORT_STPNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPINSTR DROP CONSTRAINT FK_REPORT_SETPNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPINSTR ADD CONSTRAINT FK_REPORT_SETPNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPEVENTS DROP CONSTRAINT FK_REPORT_SETUPEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPEVENTS ADD CONSTRAINT FK_REPORT_SETUPEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPEVENTS DROP CONSTRAINT FK_REPORT_SETUPEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPEVENTS ADD CONSTRAINT FK_REPORT_SETUPEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SETUPEVENTS DROP CONSTRAINT FPVNTS_STPNSTRCTN_D_STPPRMTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SETUPEVENTS ADD CONSTRAINT FPVNTS_STPNSTRCTN_D_STPPRMTR_D FOREIGN KEY (SETUPINSTRUCTION_OID, SETUPPARAMETER_OID) REFERENCES DCEREPORT_SETUPINSTR(OID, SETUPPARAMETER_OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR DROP CONSTRAINT FPRT_DTCLLCTNNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR ADD CONSTRAINT FPRT_DTCLLCTNNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR DROP CONSTRAINT F_RPRT_DTCLLCTNNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR ADD CONSTRAINT F_RPRT_DTCLLCTNNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR DROP CONSTRAINT FRPRT_DTCLLCTNNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR ADD CONSTRAINT FRPRT_DTCLLCTNNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR DROP CONSTRAINT FPRT_DTCLLCTNNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR ADD CONSTRAINT FPRT_DTCLLCTNNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR DROP CONSTRAINT FRPRT_DTCLLCTNNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONINSTR ADD CONSTRAINT FRPRT_DTCLLCTNNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS DROP CONSTRAINT FTCLLCTNNSTRCTN_D_PRCSSPRMTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS ADD CONSTRAINT FTCLLCTNNSTRCTN_D_PRCSSPRMTR_D FOREIGN KEY (DATACOLLECTIONINSTRUCTION_OID, PROCESSPARAMETER_OID) REFERENCES DCEREPORT_DATACOLLECTIONINSTR(OID, PROCESSPARAMETER_OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS DROP CONSTRAINT FK_REPORT_DATACLLCTNVNTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS ADD CONSTRAINT FK_REPORT_DATACLLCTNVNTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS DROP CONSTRAINT FK_REPORT_DATCLLCTNVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DATACOLLECTIONEVENTS ADD CONSTRAINT FK_REPORT_DATCLLCTNVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTINSTR DROP CONSTRAINT F_RPRT_MSRMNTNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTINSTR ADD CONSTRAINT F_RPRT_MSRMNTNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTINSTR DROP CONSTRAINT FK_REPRT_MSRMNTNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTINSTR ADD CONSTRAINT FK_REPRT_MSRMNTNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTINSTR DROP CONSTRAINT FK_RPRT_MSRMNTNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTINSTR ADD CONSTRAINT FK_RPRT_MSRMNTNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTINSTR DROP CONSTRAINT F_RPRT_MSRMNTNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTINSTR ADD CONSTRAINT F_RPRT_MSRMNTNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTINSTR DROP CONSTRAINT FK_RPRT_MSRMNTNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTINSTR ADD CONSTRAINT FK_RPRT_MSRMNTNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTEVENTS DROP CONSTRAINT FK_REPORT_MEASUREMNTVNTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTEVENTS ADD CONSTRAINT FK_REPORT_MEASUREMNTVNTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTEVENTS DROP CONSTRAINT FK_REPORT_MEASURMNTVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTEVENTS ADD CONSTRAINT FK_REPORT_MEASURMNTVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_MEASUREMENTEVENTS DROP CONSTRAINT FVNTS_MSRMNTNSTRCTN_D_MSRMNT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_MEASUREMENTEVENTS ADD CONSTRAINT FVNTS_MSRMNTNSTRCTN_D_MSRMNT_D FOREIGN KEY (MEASUREMENTINSTRUCTION_OID, MEASUREMENT_OID) REFERENCES DCEREPORT_MEASUREMENTINSTR(OID, MEASUREMENT_OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTINSTR DROP CONSTRAINT FK_REPORT_NPTNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTINSTR ADD CONSTRAINT FK_REPORT_NPTNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTINSTR DROP CONSTRAINT FK_REPORT_INPUTNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTINSTR ADD CONSTRAINT FK_REPORT_INPUTNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTINSTR DROP CONSTRAINT FK_REPORT_INPTNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTINSTR ADD CONSTRAINT FK_REPORT_INPTNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTINSTR DROP CONSTRAINT FK_REPORT_NPTNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTINSTR ADD CONSTRAINT FK_REPORT_NPTNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTINSTR DROP CONSTRAINT FK_REPORT_INPTNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTINSTR ADD CONSTRAINT FK_REPORT_INPTNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTEVENTS DROP CONSTRAINT FK_REPORT_INPUTEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTEVENTS ADD CONSTRAINT FK_REPORT_INPUTEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTEVENTS DROP CONSTRAINT FK_REPORT_INPUTEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTEVENTS ADD CONSTRAINT FK_REPORT_INPUTEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUTEVENTS DROP CONSTRAINT FK_REPORT_NPTVNTS_NPTNSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUTEVENTS ADD CONSTRAINT FK_REPORT_NPTVNTS_NPTNSTRCTN_D FOREIGN KEY (INPUTINSTRUCTION_OID) REFERENCES DCEREPORT_INPUTINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKINSTR DROP CONSTRAINT FK_REPRT_CHCKNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKINSTR ADD CONSTRAINT FK_REPRT_CHCKNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKINSTR DROP CONSTRAINT FK_REPORT_CHECKNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKINSTR ADD CONSTRAINT FK_REPORT_CHECKNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKINSTR DROP CONSTRAINT FK_REPORT_CHCKNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKINSTR ADD CONSTRAINT FK_REPORT_CHCKNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKINSTR DROP CONSTRAINT FK_REPRT_CHCKNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKINSTR ADD CONSTRAINT FK_REPRT_CHCKNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKINSTR DROP CONSTRAINT FK_REPORT_CHCKNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKINSTR ADD CONSTRAINT FK_REPORT_CHCKNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKEVENTS DROP CONSTRAINT FK_RPRT_CHCKVNTS_CHCKNSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKEVENTS ADD CONSTRAINT FK_RPRT_CHCKVNTS_CHCKNSTRCTN_D FOREIGN KEY (CHECKINSTRUCTION_OID) REFERENCES OBJTREP_INSPEC_CHECKINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKEVENTS DROP CONSTRAINT FK_REPORT_CHECKEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKEVENTS ADD CONSTRAINT FK_REPORT_CHECKEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_CHECKEVENTS DROP CONSTRAINT FK_REPORT_CHECKEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_CHECKEVENTS ADD CONSTRAINT FK_REPORT_CHECKEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTINSTR DROP CONSTRAINT FK_REPRT_PRNTNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTINSTR ADD CONSTRAINT FK_REPRT_PRNTNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTINSTR DROP CONSTRAINT FK_REPORT_PRINTNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTINSTR ADD CONSTRAINT FK_REPORT_PRINTNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTINSTR DROP CONSTRAINT FK_REPORT_PRNTNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTINSTR ADD CONSTRAINT FK_REPORT_PRNTNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTINSTR DROP CONSTRAINT FK_REPRT_PRNTNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTINSTR ADD CONSTRAINT FK_REPRT_PRNTNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTINSTR DROP CONSTRAINT FK_REPORT_PRNTNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTINSTR ADD CONSTRAINT FK_REPORT_PRNTNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTEVENTS DROP CONSTRAINT FK_REPORT_PRINTEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTEVENTS ADD CONSTRAINT FK_REPORT_PRINTEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTEVENTS DROP CONSTRAINT FK_REPORT_PRINTEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTEVENTS ADD CONSTRAINT FK_REPORT_PRINTEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PRINTEVENTS DROP CONSTRAINT FK_RPRT_PRNTVNTS_PRNTNSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PRINTEVENTS ADD CONSTRAINT FK_RPRT_PRNTVNTS_PRNTNSTRCTN_D FOREIGN KEY (PRINTINSTRUCTION_OID) REFERENCES DCEREPORT_PRINTINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT FK_BJTRP_NSPCTNNSTR_NSPCTNSHTD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT FK_BJTRP_NSPCTNNSTR_NSPCTNSHTD FOREIGN KEY (INSPECTIONSHEETOID) REFERENCES OBJTREP_INSPECTION(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT FBJTRP_NSPCTNNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT FBJTRP_NSPCTNNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT FK_BJTRP_NSPCTNNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT FK_BJTRP_NSPCTNNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT F_BJTRP_NSPCTNNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT F_BJTRP_NSPCTNNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT FBJTRP_NSPCTNNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT FBJTRP_NSPCTNNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONINSTR DROP CONSTRAINT F_BJTRP_NSPCTNNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONINSTR ADD CONSTRAINT F_BJTRP_NSPCTNNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONEVENTS DROP CONSTRAINT FK_OBJTREP_INSPECTINVNTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONEVENTS ADD CONSTRAINT FK_OBJTREP_INSPECTINVNTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONEVENTS DROP CONSTRAINT FK_OBJTREP_INSPECTNVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONEVENTS ADD CONSTRAINT FK_OBJTREP_INSPECTNVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INSPECTIONEVENTS DROP CONSTRAINT FRP_NSPCTNVNTS_NSPCTNNSTRCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INSPECTIONEVENTS ADD CONSTRAINT FRP_NSPCTNVNTS_NSPCTNNSTRCTN_D FOREIGN KEY (INSPECTIONINSTRUCTION_OID) REFERENCES OBJTREP_INSPECTIONINSTR(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEDINSTR DROP CONSTRAINT F_RPRT_DCMNTDNSTR_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEDINSTR ADD CONSTRAINT F_RPRT_DCMNTDNSTR_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEDINSTR DROP CONSTRAINT FK_REPRT_DCMNTDNSTR_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEDINSTR ADD CONSTRAINT FK_REPRT_DCMNTDNSTR_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEDINSTR DROP CONSTRAINT FK_RPRT_DCMNTDNSTR_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEDINSTR ADD CONSTRAINT FK_RPRT_DCMNTDNSTR_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEDINSTR DROP CONSTRAINT F_RPRT_DCMNTDNSTR_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEDINSTR ADD CONSTRAINT F_RPRT_DCMNTDNSTR_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEDINSTR DROP CONSTRAINT FK_RPRT_DCMNTDNSTR_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEDINSTR ADD CONSTRAINT FK_RPRT_DCMNTDNSTR_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEVENTS DROP CONSTRAINT FK_REPORT_DOCUMENTEVENTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEVENTS ADD CONSTRAINT FK_REPORT_DOCUMENTEVENTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DOCUMENTEVENTS DROP CONSTRAINT FK_REPORT_DOCUMENTEVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DOCUMENTEVENTS ADD CONSTRAINT FK_REPORT_DOCUMENTEVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS DROP CONSTRAINT FK_RPRT_NSTRCTNSHTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS ADD CONSTRAINT FK_RPRT_NSTRCTNSHTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS DROP CONSTRAINT F_RPRT_NSTRCTNSHTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS ADD CONSTRAINT F_RPRT_NSTRCTNSHTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS DROP CONSTRAINT FRPRT_NSTRCTNSHTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS ADD CONSTRAINT FRPRT_NSTRCTNSHTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS DROP CONSTRAINT F_RPRT_NSTRCTNSHTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INSTRUCTIONSHEETS ADD CONSTRAINT F_RPRT_NSTRCTNSHTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHEETEVENTS DROP CONSTRAINT FK_REPORT_SHEETEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHEETEVENTS ADD CONSTRAINT FK_REPORT_SHEETEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHEETEVENTS DROP CONSTRAINT FK_REPORT_SHEETEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHEETEVENTS ADD CONSTRAINT FK_REPORT_SHEETEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_SHEETEVENTS DROP CONSTRAINT FK_REPORT_SHTVNTS_NSTRCTNSHT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_SHEETEVENTS ADD CONSTRAINT FK_REPORT_SHTVNTS_NSTRCTNSHT_D FOREIGN KEY (INSTRUCTIONSHEET_OID) REFERENCES DCEREPORT_INSTRUCTIONSHEETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_REPORT_INPUT_TARGETS_ITEM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_REPORT_INPUT_TARGETS_ITEM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_REPORT_INPUT_TARGETS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_REPORT_INPUT_TARGETS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_REPORT_NPT_TRGTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_REPORT_NPT_TRGTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_REPRT_NPT_TRGTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_REPRT_NPT_TRGTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_RPRT_NPT_TRGTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_RPRT_NPT_TRGTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_TARGETS DROP CONSTRAINT FK_REPRT_NPT_TRGTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_TARGETS ADD CONSTRAINT FK_REPRT_NPT_TRGTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTULS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTULS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTUALS_DEVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTUALS_DEVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTUALS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTUALS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPT_CTLS_NPT_TRGT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPT_CTLS_NPT_TRGT_D FOREIGN KEY (INPUT_TARGET_OID) REFERENCES DCEREPORT_INPUT_TARGETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTUALS_ITEM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTUALS_ITEM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTUALS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTUALS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPUT_ACTUALS_LOT_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPUT_ACTUALS_LOT_OD FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_INPT_CTLS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_INPT_CTLS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_NPT_CTLS_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_NPT_CTLS_NST_CNTNR_D FOREIGN KEY (NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_NPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_NPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPRT_NPT_CTLS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPRT_NPT_CTLS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_INPUT_ACTUALS DROP CONSTRAINT FK_REPORT_NPT_CTLS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_INPUT_ACTUALS ADD CONSTRAINT FK_REPORT_NPT_CTLS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_REPORT_OUTPUT_TARGETS_ITM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_REPORT_OUTPUT_TARGETS_ITM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_REPORT_OUTPUT_TARGTS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_REPORT_OUTPUT_TARGTS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_REPORT_TPT_TRGTS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_REPORT_TPT_TRGTS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_REPRT_TPT_TRGTS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_REPRT_TPT_TRGTS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_RPRT_TPT_TRGTS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_RPRT_TPT_TRGTS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_TARGETS DROP CONSTRAINT FK_REPRT_TPT_TRGTS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_TARGETS ADD CONSTRAINT FK_REPRT_TPT_TRGTS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTLS_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTLS_CNTNR_D FOREIGN KEY (CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTULS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTULS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_ITM_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_ITM_D FOREIGN KEY (ITEM_OID) REFERENCES DCEREPORT_ITEMS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTULS_LCTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTULS_LCTN_D FOREIGN KEY (LOCATION_OID) REFERENCES DCEREPORT_LOCATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_LOT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OUTPUT_ACTUALS_LOT_D FOREIGN KEY (LOT_OID) REFERENCES DCEREPORT_LOTS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OTPT_CTLS_MCHNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OTPT_CTLS_MCHNPRTN_D FOREIGN KEY (MACHINEOPERATION_OID) REFERENCES DCEREPORT_MACHINEOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_TPT_CTLS_NST_CNTNR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_TPT_CTLS_NST_CNTNR_D FOREIGN KEY (NEST_CONTAINER_OID) REFERENCES DCEREPORT_CONTAINERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_OTPT_CTLS_TPT_TRGT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_OTPT_CTLS_TPT_TRGT_D FOREIGN KEY (OUTPUT_TARGET_OID) REFERENCES DCEREPORT_OUTPUT_TARGETS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_TPT_CTLS_PRCSSRSRC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_TPT_CTLS_PRCSSRSRC_D FOREIGN KEY (PROCESSRESOURCE_OID) REFERENCES DCEREPORT_PROCESSRESOURCES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPRT_TPT_CTLS_PRDCTNPRTN_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPRT_TPT_CTLS_PRDCTNPRTN_D FOREIGN KEY (PRODUCTIONOPERATION_OID) REFERENCES DCEREPORT_PRODUCTIONOPERATIONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_OUTPUT_ACTUALS DROP CONSTRAINT FK_REPORT_TPT_CTLS_PRDCTNRDR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_OUTPUT_ACTUALS ADD CONSTRAINT FK_REPORT_TPT_CTLS_PRDCTNRDR_D FOREIGN KEY (PRODUCTIONORDER_OID) REFERENCES DCEREPORT_PRODUCTIONORDERS(OID) DISABLE NOVALIDATE
/

