BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DEPT_EMPLOYEES DROP CONSTRAINT FK_OBJTREP_DEPT_EMPLOYS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DEPT_EMPLOYEES ADD CONSTRAINT FK_OBJTREP_DEPT_EMPLOYS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES DROP CONSTRAINT FK_REPRT_PLNND_TTNDNCS_DY_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES ADD CONSTRAINT FK_REPRT_PLNND_TTNDNCS_DY_CD_D FOREIGN KEY (DAY_CODE_OID) REFERENCES DCEREPORT_DAY_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES DROP CONSTRAINT FK_REPORT_PLNND_TTNDNCS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES ADD CONSTRAINT FK_REPORT_PLNND_TTNDNCS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_DAY_CODES DROP CONSTRAINT FK_REPORT_DAY_CODES_BALNC_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_DAY_CODES ADD CONSTRAINT FK_REPORT_DAY_CODES_BALNC_CD_D FOREIGN KEY (BALANCE_CODE_OID) REFERENCES DCEREPORT_BALANCE_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DAY_COUNTERS DROP CONSTRAINT FK_OBJTREP_DAY_COUNTRS_DY_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DAY_COUNTERS ADD CONSTRAINT FK_OBJTREP_DAY_COUNTRS_DY_CD_D FOREIGN KEY (DAY_CODE_OID) REFERENCES DCEREPORT_DAY_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DAY_COUNTERS DROP CONSTRAINT FK_OBJTREP_DAY_COUNTERS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DAY_COUNTERS ADD CONSTRAINT FK_OBJTREP_DAY_COUNTERS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT FTRP_DYTTCNTRCSTDTLS_CSTCNTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS ADD CONSTRAINT FTRP_DYTTCNTRCSTDTLS_CSTCNTR_D FOREIGN KEY (COSTCENTER_OID) REFERENCES DCEREPORT_COSTCENTERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT FBJTRP_DYTTCNTRCSTDTLS_DY_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS ADD CONSTRAINT FBJTRP_DYTTCNTRCSTDTLS_DY_CD_D FOREIGN KEY (DAY_CODE_OID) REFERENCES DCEREPORT_DAY_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT F_BJTRP_DYTTCNTRCSTDTLS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS ADD CONSTRAINT F_BJTRP_DYTTCNTRCSTDTLS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_CLOCKINGEVENTS DROP CONSTRAINT FK_OBJTREP_CLOCKINGEVNTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_CLOCKINGEVENTS ADD CONSTRAINT FK_OBJTREP_CLOCKINGEVNTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_CLOCKINGEVENTS DROP CONSTRAINT FK_OBJTREP_CLOCKINGVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_CLOCKINGEVENTS ADD CONSTRAINT FK_OBJTREP_CLOCKINGVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INFOEVENTS DROP CONSTRAINT FK_OBJTREP_INFOEVENTS_DEVICE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INFOEVENTS ADD CONSTRAINT FK_OBJTREP_INFOEVENTS_DEVICE_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_INFOEVENTS DROP CONSTRAINT FK_OBJTREP_INFOEVENTS_EMPLOY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_INFOEVENTS ADD CONSTRAINT FK_OBJTREP_INFOEVENTS_EMPLOY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_BJTRP_CSTCNTRVNTS_CSTCNTR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_COSTCENTEREVENTS ADD CONSTRAINT FK_BJTRP_CSTCNTRVNTS_CSTCNTR_D FOREIGN KEY (COSTCENTER_OID) REFERENCES DCEREPORT_COSTCENTERS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_OBJTREP_COSTCENTRVNTS_DVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_COSTCENTEREVENTS ADD CONSTRAINT FK_OBJTREP_COSTCENTRVNTS_DVC_D FOREIGN KEY (DEVICE_OID) REFERENCES DCEREPORT_DEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_OBJTREP_COSTCNTRVNTS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_COSTCENTEREVENTS ADD CONSTRAINT FK_OBJTREP_COSTCNTRVNTS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES DROP CONSTRAINT FK_OBJTREP_CTL_TTNDNCS_DY_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES ADD CONSTRAINT FK_OBJTREP_CTL_TTNDNCS_DY_CD_D FOREIGN KEY (DAY_CODE_OID) REFERENCES DCEREPORT_DAY_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES DROP CONSTRAINT FK_OBJTREP_ACTL_TTNDNCS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES ADD CONSTRAINT FK_OBJTREP_ACTL_TTNDNCS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_ATTENDANCEPERIODS DROP CONSTRAINT FK_OBJTREP_ATTENDNCPRDS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_ATTENDANCEPERIODS ADD CONSTRAINT FK_OBJTREP_ATTENDNCPRDS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTRP_BLNC_CNTRS_BLNC_CD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_BALANCE_COUNTERS ADD CONSTRAINT FK_OBJTRP_BLNC_CNTRS_BLNC_CD_D FOREIGN KEY (BALANCE_CODE_OID) REFERENCES DCEREPORT_BALANCE_CODES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTREP_BALANC_CNTRS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_BALANCE_COUNTERS ADD CONSTRAINT FK_OBJTREP_BALANC_CNTRS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTREP_BALANCE_CNTRS_PRD_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_BALANCE_COUNTERS ADD CONSTRAINT FK_OBJTREP_BALANCE_CNTRS_PRD_D FOREIGN KEY (PERIOD_OID) REFERENCES OBJTREP_ATTENDANCEPERIODS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_ANOMALIES DROP CONSTRAINT FK_OBJTREP_ANOMALIES_EMPLOYE_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_ANOMALIES ADD CONSTRAINT FK_OBJTREP_ANOMALIES_EMPLOYE_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OBJTREP_ANOMALIES DROP CONSTRAINT FK_OBJTREP_ANOMALIES_REASON_OD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE OBJTREP_ANOMALIES ADD CONSTRAINT FK_OBJTREP_ANOMALIES_REASON_OD FOREIGN KEY (REASON_OID) REFERENCES OBJTREP_ANOMALYREASONS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_REPORT_ACCESS_PRTNS_CCSSR_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ACCESS_OPERATIONS ADD CONSTRAINT FK_REPORT_ACCESS_PRTNS_CCSSR_D FOREIGN KEY (ACCESSAREA_OID) REFERENCES DCEREPORT_ACCESS_AREAS(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_REPORT_CCSS_PRTNS_CCSSBDG_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ACCESS_OPERATIONS ADD CONSTRAINT FK_REPORT_CCSS_PRTNS_CCSSBDG_D FOREIGN KEY (ACCESSBADGE_OID) REFERENCES DCEREPORT_ACCESS_BADGES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_REPORT_ACCSS_PRTNS_CCSSGT_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ACCESS_OPERATIONS ADD CONSTRAINT FK_REPORT_ACCSS_PRTNS_CCSSGT_D FOREIGN KEY (ACCESSGATE_OID) REFERENCES DCEREPORT_ACCESS_GATES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT F_RPRT_CCSS_PRTNS_CCSSRDRDVC_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ACCESS_OPERATIONS ADD CONSTRAINT F_RPRT_CCSS_PRTNS_CCSSRDRDVC_D FOREIGN KEY (ACCESSREADERDEVICE_OID) REFERENCES DCEREPORT_ACCESS_READERDEVICES(OID) DISABLE NOVALIDATE
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_REPORT_ACCESS_OPRTNS_MPLY_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

ALTER TABLE DCEREPORT_ACCESS_OPERATIONS ADD CONSTRAINT FK_REPORT_ACCESS_OPRTNS_MPLY_D FOREIGN KEY (EMPLOYEE_OID) REFERENCES DCEREPORT_EMPLOYEES(OID) DISABLE NOVALIDATE
/

