CREATE ROLE OBJT_DEVELOPER;

GRANT CREATE SESSION TO OBJT_DEVELOPER;

GRANT CREATE ANY TABLE TO OBJT_DEVELOPER;
GRANT DROP ANY TABLE TO OBJT_DEVELOPER;
GRANT ALTER ANY TABLE TO OBJT_DEVELOPER;
GRANT SELECT ANY TABLE TO OBJT_DEVELOPER;
GRANT INSERT ANY TABLE TO OBJT_DEVELOPER;
GRANT DELETE ANY TABLE TO OBJT_DEVELOPER;
GRANT UPDATE ANY TABLE TO OBJT_DEVELOPER;
GRANT COMMENT ANY TABLE TO OBJT_DEVELOPER;
GRANT LOCK ANY TABLE TO OBJT_DEVELOPER;
GRANT BACKUP ANY TABLE TO OBJT_DEVELOPER;

GRANT CREATE ANY VIEW TO OBJT_DEVELOPER;
GRANT DROP ANY VIEW TO OBJT_DEVELOPER;

GRANT CREATE ANY SEQUENCE TO OBJT_DEVELOPER;
GRANT DROP ANY SEQUENCE TO OBJT_DEVELOPER;
GRANT ALTER ANY SEQUENCE TO OBJT_DEVELOPER;

GRANT CREATE PUBLIC SYNONYM TO OBJT_DEVELOPER;
GRANT DROP PUBLIC SYNONYM TO OBJT_DEVELOPER;

GRANT CREATE ANY PROCEDURE TO OBJT_DEVELOPER;
GRANT DROP ANY PROCEDURE TO OBJT_DEVELOPER;
GRANT EXECUTE ANY PROCEDURE TO OBJT_DEVELOPER;
