IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_EMPLOYEE_GROUPS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_EMPLOYEE_GROUPS'))  ALTER TABLE DCEREPORT_EMPLOYEE_GROUPS DROP CONSTRAINT FK_DCEREPORT_EMPLOYEE_GROUPS_EMPLOYEE_OID
ALTER TABLE DCEREPORT_EMPLOYEE_GROUPS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_EMPLOYEE_GROUPS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_EMPLOYEE_GROUPS NOCHECK CONSTRAINT FK_DCEREPORT_EMPLOYEE_GROUPS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ITEMS_UOM_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ITEMS'))  ALTER TABLE DCEREPORT_ITEMS DROP CONSTRAINT FK_DCEREPORT_ITEMS_UOM_OID
ALTER TABLE DCEREPORT_ITEMS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ITEMS_UOM_OID  FOREIGN KEY(UOM_OID)  REFERENCES DCEREPORT_UOMS(OID)
ALTER TABLE DCEREPORT_ITEMS NOCHECK CONSTRAINT FK_DCEREPORT_ITEMS_UOM_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_LOTS_ITEM_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_LOTS'))  ALTER TABLE DCEREPORT_LOTS DROP CONSTRAINT FK_DCEREPORT_LOTS_ITEM_OID
ALTER TABLE DCEREPORT_LOTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_LOTS_ITEM_OID  FOREIGN KEY(ITEM_OID)  REFERENCES DCEREPORT_ITEMS(OID)
ALTER TABLE DCEREPORT_LOTS NOCHECK CONSTRAINT FK_DCEREPORT_LOTS_ITEM_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_LOTS_QCSTATUS_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_LOTS'))  ALTER TABLE DCEREPORT_LOTS DROP CONSTRAINT FK_DCEREPORT_LOTS_QCSTATUS_OID
ALTER TABLE DCEREPORT_LOTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_LOTS_QCSTATUS_OID  FOREIGN KEY(QCSTATUS_OID)  REFERENCES DCEREPORT_QCSTATUSES(OID)
ALTER TABLE DCEREPORT_LOTS NOCHECK CONSTRAINT FK_DCEREPORT_LOTS_QCSTATUS_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CONTAINERS_CONTAINER_TYPE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CONTAINERS'))  ALTER TABLE DCEREPORT_CONTAINERS DROP CONSTRAINT FK_DCEREPORT_CONTAINERS_CONTAINER_TYPE_OID
ALTER TABLE DCEREPORT_CONTAINERS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CONTAINERS_CONTAINER_TYPE_OID  FOREIGN KEY(CONTAINER_TYPE_OID)  REFERENCES DCEREPORT_CONTAINER_TYPES(OID)
ALTER TABLE DCEREPORT_CONTAINERS NOCHECK CONSTRAINT FK_DCEREPORT_CONTAINERS_CONTAINER_TYPE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CONTAINERS_NEST_CONTAINER_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CONTAINERS'))  ALTER TABLE DCEREPORT_CONTAINERS DROP CONSTRAINT FK_DCEREPORT_CONTAINERS_NEST_CONTAINER_OID
ALTER TABLE DCEREPORT_CONTAINERS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CONTAINERS_NEST_CONTAINER_OID  FOREIGN KEY(NEST_CONTAINER_OID)  REFERENCES DCEREPORT_CONTAINERS(OID)
ALTER TABLE DCEREPORT_CONTAINERS NOCHECK CONSTRAINT FK_DCEREPORT_CONTAINERS_NEST_CONTAINER_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_COMMENTS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_COMMENTS'))  ALTER TABLE DCEREPORT_COMMENTS DROP CONSTRAINT FK_DCEREPORT_COMMENTS_EMPLOYEE_OID
ALTER TABLE DCEREPORT_COMMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_COMMENTS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_COMMENTS NOCHECK CONSTRAINT FK_DCEREPORT_COMMENTS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_LOTPARAMETERS_LOT_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_LOTPARAMETERS'))  ALTER TABLE DCEREPORT_LOTPARAMETERS DROP CONSTRAINT FK_DCEREPORT_LOTPARAMETERS_LOT_OID
ALTER TABLE DCEREPORT_LOTPARAMETERS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_LOTPARAMETERS_LOT_OID  FOREIGN KEY(LOT_OID)  REFERENCES DCEREPORT_LOTS(OID)
ALTER TABLE DCEREPORT_LOTPARAMETERS NOCHECK CONSTRAINT FK_DCEREPORT_LOTPARAMETERS_LOT_OID