IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DEPT_EMPLOYEES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DEPT_EMPLOYEES'))  ALTER TABLE OBJTREP_DEPT_EMPLOYEES DROP CONSTRAINT FK_OBJTREP_DEPT_EMPLOYEES_EMPLOYEE_OID
ALTER TABLE OBJTREP_DEPT_EMPLOYEES WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DEPT_EMPLOYEES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_DEPT_EMPLOYEES NOCHECK CONSTRAINT FK_OBJTREP_DEPT_EMPLOYEES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_PLANNED_ATTENDANCES_DAY_CODE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_PLANNED_ATTENDANCES'))  ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES DROP CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_DAY_CODE_OID
ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_DAY_CODE_OID  FOREIGN KEY(DAY_CODE_OID)  REFERENCES DCEREPORT_DAY_CODES(OID)
ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES NOCHECK CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_DAY_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_PLANNED_ATTENDANCES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_PLANNED_ATTENDANCES'))  ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES DROP CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_EMPLOYEE_OID
ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_PLANNED_ATTENDANCES NOCHECK CONSTRAINT FK_DCEREPORT_PLANNED_ATTENDANCES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_DAY_CODES_BALANCE_CODE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_DAY_CODES'))  ALTER TABLE DCEREPORT_DAY_CODES DROP CONSTRAINT FK_DCEREPORT_DAY_CODES_BALANCE_CODE_OID
ALTER TABLE DCEREPORT_DAY_CODES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_DAY_CODES_BALANCE_CODE_OID  FOREIGN KEY(BALANCE_CODE_OID)  REFERENCES DCEREPORT_BALANCE_CODES(OID)
ALTER TABLE DCEREPORT_DAY_CODES NOCHECK CONSTRAINT FK_DCEREPORT_DAY_CODES_BALANCE_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DAY_COUNTERS_DAY_CODE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DAY_COUNTERS'))  ALTER TABLE OBJTREP_DAY_COUNTERS DROP CONSTRAINT FK_OBJTREP_DAY_COUNTERS_DAY_CODE_OID
ALTER TABLE OBJTREP_DAY_COUNTERS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DAY_COUNTERS_DAY_CODE_OID  FOREIGN KEY(DAY_CODE_OID)  REFERENCES DCEREPORT_DAY_CODES(OID)
ALTER TABLE OBJTREP_DAY_COUNTERS NOCHECK CONSTRAINT FK_OBJTREP_DAY_COUNTERS_DAY_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DAY_COUNTERS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DAY_COUNTERS'))  ALTER TABLE OBJTREP_DAY_COUNTERS DROP CONSTRAINT FK_OBJTREP_DAY_COUNTERS_EMPLOYEE_OID
ALTER TABLE OBJTREP_DAY_COUNTERS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DAY_COUNTERS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_DAY_COUNTERS NOCHECK CONSTRAINT FK_OBJTREP_DAY_COUNTERS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DAYATTCNTRCOSTDTLS_COSTCENTER_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DAYATTCNTRCOSTDTLS'))  ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_COSTCENTER_OID
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_COSTCENTER_OID  FOREIGN KEY(COSTCENTER_OID)  REFERENCES DCEREPORT_COSTCENTERS(OID)
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS NOCHECK CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_COSTCENTER_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DAYATTCNTRCOSTDTLS_DAY_CODE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DAYATTCNTRCOSTDTLS'))  ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_DAY_CODE_OID
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_DAY_CODE_OID  FOREIGN KEY(DAY_CODE_OID)  REFERENCES DCEREPORT_DAY_CODES(OID)
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS NOCHECK CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_DAY_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_DAYATTCNTRCOSTDTLS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_DAYATTCNTRCOSTDTLS'))  ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS DROP CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_EMPLOYEE_OID
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_DAYATTCNTRCOSTDTLS NOCHECK CONSTRAINT FK_OBJTREP_DAYATTCNTRCOSTDTLS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_CLOCKINGEVENTS_DEVICE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_CLOCKINGEVENTS'))  ALTER TABLE OBJTREP_CLOCKINGEVENTS DROP CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_DEVICE_OID
ALTER TABLE OBJTREP_CLOCKINGEVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_DEVICE_OID  FOREIGN KEY(DEVICE_OID)  REFERENCES DCEREPORT_DEVICES(OID)
ALTER TABLE OBJTREP_CLOCKINGEVENTS NOCHECK CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_DEVICE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_CLOCKINGEVENTS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_CLOCKINGEVENTS'))  ALTER TABLE OBJTREP_CLOCKINGEVENTS DROP CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_EMPLOYEE_OID
ALTER TABLE OBJTREP_CLOCKINGEVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_CLOCKINGEVENTS NOCHECK CONSTRAINT FK_OBJTREP_CLOCKINGEVENTS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_INFOEVENTS_DEVICE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_INFOEVENTS'))  ALTER TABLE OBJTREP_INFOEVENTS DROP CONSTRAINT FK_OBJTREP_INFOEVENTS_DEVICE_OID
ALTER TABLE OBJTREP_INFOEVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_INFOEVENTS_DEVICE_OID  FOREIGN KEY(DEVICE_OID)  REFERENCES DCEREPORT_DEVICES(OID)
ALTER TABLE OBJTREP_INFOEVENTS NOCHECK CONSTRAINT FK_OBJTREP_INFOEVENTS_DEVICE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_INFOEVENTS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_INFOEVENTS'))  ALTER TABLE OBJTREP_INFOEVENTS DROP CONSTRAINT FK_OBJTREP_INFOEVENTS_EMPLOYEE_OID
ALTER TABLE OBJTREP_INFOEVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_INFOEVENTS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_INFOEVENTS NOCHECK CONSTRAINT FK_OBJTREP_INFOEVENTS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_COSTCENTEREVENTS_COSTCENTER_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_COSTCENTEREVENTS'))  ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_COSTCENTER_OID
ALTER TABLE OBJTREP_COSTCENTEREVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_COSTCENTER_OID  FOREIGN KEY(COSTCENTER_OID)  REFERENCES DCEREPORT_COSTCENTERS(OID)
ALTER TABLE OBJTREP_COSTCENTEREVENTS NOCHECK CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_COSTCENTER_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_COSTCENTEREVENTS_DEVICE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_COSTCENTEREVENTS'))  ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_DEVICE_OID
ALTER TABLE OBJTREP_COSTCENTEREVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_DEVICE_OID  FOREIGN KEY(DEVICE_OID)  REFERENCES DCEREPORT_DEVICES(OID)
ALTER TABLE OBJTREP_COSTCENTEREVENTS NOCHECK CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_DEVICE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_COSTCENTEREVENTS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_COSTCENTEREVENTS'))  ALTER TABLE OBJTREP_COSTCENTEREVENTS DROP CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_EMPLOYEE_OID
ALTER TABLE OBJTREP_COSTCENTEREVENTS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_COSTCENTEREVENTS NOCHECK CONSTRAINT FK_OBJTREP_COSTCENTEREVENTS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_ACTUAL_ATTENDANCES_DAY_CODE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_ACTUAL_ATTENDANCES'))  ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES DROP CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_DAY_CODE_OID
ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_DAY_CODE_OID  FOREIGN KEY(DAY_CODE_OID)  REFERENCES DCEREPORT_DAY_CODES(OID)
ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES NOCHECK CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_DAY_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_ACTUAL_ATTENDANCES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_ACTUAL_ATTENDANCES'))  ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES DROP CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_EMPLOYEE_OID
ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_ACTUAL_ATTENDANCES NOCHECK CONSTRAINT FK_OBJTREP_ACTUAL_ATTENDANCES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_ATTENDANCEPERIODS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_ATTENDANCEPERIODS'))  ALTER TABLE OBJTREP_ATTENDANCEPERIODS DROP CONSTRAINT FK_OBJTREP_ATTENDANCEPERIODS_EMPLOYEE_OID
ALTER TABLE OBJTREP_ATTENDANCEPERIODS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_ATTENDANCEPERIODS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_ATTENDANCEPERIODS NOCHECK CONSTRAINT FK_OBJTREP_ATTENDANCEPERIODS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_BALANCE_COUNTERS_BALANCE_CODE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_BALANCE_COUNTERS'))  ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_BALANCE_CODE_OID
ALTER TABLE OBJTREP_BALANCE_COUNTERS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_BALANCE_CODE_OID  FOREIGN KEY(BALANCE_CODE_OID)  REFERENCES DCEREPORT_BALANCE_CODES(OID)
ALTER TABLE OBJTREP_BALANCE_COUNTERS NOCHECK CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_BALANCE_CODE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_BALANCE_COUNTERS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_BALANCE_COUNTERS'))  ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_EMPLOYEE_OID
ALTER TABLE OBJTREP_BALANCE_COUNTERS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_BALANCE_COUNTERS NOCHECK CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_BALANCE_COUNTERS_PERIOD_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_BALANCE_COUNTERS'))  ALTER TABLE OBJTREP_BALANCE_COUNTERS DROP CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_PERIOD_OID
ALTER TABLE OBJTREP_BALANCE_COUNTERS WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_PERIOD_OID  FOREIGN KEY(PERIOD_OID)  REFERENCES OBJTREP_ATTENDANCEPERIODS(OID)
ALTER TABLE OBJTREP_BALANCE_COUNTERS NOCHECK CONSTRAINT FK_OBJTREP_BALANCE_COUNTERS_PERIOD_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_ANOMALIES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_ANOMALIES'))  ALTER TABLE OBJTREP_ANOMALIES DROP CONSTRAINT FK_OBJTREP_ANOMALIES_EMPLOYEE_OID
ALTER TABLE OBJTREP_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_ANOMALIES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE OBJTREP_ANOMALIES NOCHECK CONSTRAINT FK_OBJTREP_ANOMALIES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_OBJTREP_ANOMALIES_REASON_OID') AND parent_object_id = OBJECT_ID(N'OBJTREP_ANOMALIES'))  ALTER TABLE OBJTREP_ANOMALIES DROP CONSTRAINT FK_OBJTREP_ANOMALIES_REASON_OID
ALTER TABLE OBJTREP_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_OBJTREP_ANOMALIES_REASON_OID  FOREIGN KEY(REASON_OID)  REFERENCES OBJTREP_ANOMALYREASONS(OID)
ALTER TABLE OBJTREP_ANOMALIES NOCHECK CONSTRAINT FK_OBJTREP_ANOMALIES_REASON_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSAREA_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ACCESS_OPERATIONS'))  ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSAREA_OID
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSAREA_OID  FOREIGN KEY(ACCESSAREA_OID)  REFERENCES DCEREPORT_ACCESS_AREAS(OID)
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS NOCHECK CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSAREA_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSBADGE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ACCESS_OPERATIONS'))  ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSBADGE_OID
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSBADGE_OID  FOREIGN KEY(ACCESSBADGE_OID)  REFERENCES DCEREPORT_ACCESS_BADGES(OID)
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS NOCHECK CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSBADGE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSGATE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ACCESS_OPERATIONS'))  ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSGATE_OID
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSGATE_OID  FOREIGN KEY(ACCESSGATE_OID)  REFERENCES DCEREPORT_ACCESS_GATES(OID)
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS NOCHECK CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSGATE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSREADERDEVICE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ACCESS_OPERATIONS'))  ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSREADERDEVICE_OID
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSREADERDEVICE_OID  FOREIGN KEY(ACCESSREADERDEVICE_OID)  REFERENCES DCEREPORT_ACCESS_READERDEVICES(OID)
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS NOCHECK CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_ACCESSREADERDEVICE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_ACCESS_OPERATIONS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_ACCESS_OPERATIONS'))  ALTER TABLE DCEREPORT_ACCESS_OPERATIONS DROP CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_EMPLOYEE_OID
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_ACCESS_OPERATIONS NOCHECK CONSTRAINT FK_DCEREPORT_ACCESS_OPERATIONS_EMPLOYEE_OID

