  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_DEPT_EMPLOYEES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_DEPT_EMPLOYEES
  GO

  CREATE TABLE OBJTREP_DEPT_EMPLOYEES
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    EMPLOYEE_OID         BIGINT,
    EMPLOYEE_NAME        VARCHAR(64),
    EMPLOYEE_FIRSTNAME   VARCHAR(64),
    EMP_DEP_LINK_DTSVALIDFROM DATETIME2,
    EMP_DEP_LINK_DTSVALIDUNTIL DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_DEPT_EMPLOYEES
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_DEPT_EMPLOYEES_EMPLOYEE_OID ON OBJTREP_DEPT_EMPLOYEES(EMPLOYEE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_COSTCENTERS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_COSTCENTERS
  GO

  CREATE TABLE DCEREPORT_COSTCENTERS
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    ID                   VARCHAR(64),
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_COSTCENTERS
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_PLANNED_ATTENDANCES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_PLANNED_ATTENDANCES
  GO

  CREATE TABLE DCEREPORT_PLANNED_ATTENDANCES
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    CATEGORY             VARCHAR(64),
    DTSSTART             DATETIME2,
    DTSSTOP              DATETIME2,
    DAY_CODE_OID         BIGINT,
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_PLANNED_ATTENDANCES
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IDCEREPORT_PLANNED_ATTENDANCES_EMPLOYEE_OID ON DCEREPORT_PLANNED_ATTENDANCES(EMPLOYEE_OID)
  GO

  CREATE INDEX IDCEREPORT_PLANNED_ATTENDANCES_DAY_CODE_OID ON DCEREPORT_PLANNED_ATTENDANCES(DAY_CODE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_DAY_CODES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_DAY_CODES
  GO

  CREATE TABLE DCEREPORT_DAY_CODES
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(255),
    DESCRIPTION          VARCHAR(255),
    ID                   VARCHAR(255),
    UNIT                 VARCHAR(3),
    TYPE                 VARCHAR(10),
    BALANCE_CODE_OID     BIGINT,
    TRANSFER_FACTOR      FLOAT,
    TRANSFER_TYPE        VARCHAR(9),
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_DAY_CODES
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IDCEREPORT_DAY_CODES_BALANCE_CODE_OID ON DCEREPORT_DAY_CODES(BALANCE_CODE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_BALANCE_CODES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_BALANCE_CODES
  GO

  CREATE TABLE DCEREPORT_BALANCE_CODES
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(255),
    DESCRIPTION          VARCHAR(255),
    ID                   VARCHAR(255),
    UNIT                 VARCHAR(3),
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_BALANCE_CODES
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_DAY_COUNTERS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_DAY_COUNTERS
  GO

  CREATE TABLE OBJTREP_DAY_COUNTERS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DAY_CODE_OID         BIGINT,
    DTS                  DATETIME2,
    DURATION             FLOAT,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_DAY_COUNTERS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_DAY_COUNTERS_EMPLOYEE_OID ON OBJTREP_DAY_COUNTERS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_DAY_COUNTERS_DAY_CODE_OID ON OBJTREP_DAY_COUNTERS(DAY_CODE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_DAYATTCNTRCOSTDTLS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_DAYATTCNTRCOSTDTLS
  GO

  CREATE TABLE OBJTREP_DAYATTCNTRCOSTDTLS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DAY_CODE_OID         BIGINT,
    COSTCENTER_OID       BIGINT,
    USRTXT1              VARCHAR(255),
    USRTXT2              VARCHAR(255),
    USRTXT3              VARCHAR(255),
    USRTXT4              VARCHAR(255),
    USRTXT5              VARCHAR(255),
    DTS                  DATETIME2,
    DURATION             BIGINT,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_DAYATTCNTRCOSTDTLS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_DAYATTCNTRCOSTDTLS_EMPLOYEE_OID ON OBJTREP_DAYATTCNTRCOSTDTLS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_DAYATTCNTRCOSTDTLS_DAY_CODE_OID ON OBJTREP_DAYATTCNTRCOSTDTLS(DAY_CODE_OID)
  GO

  CREATE INDEX IOBJTREP_DAYATTCNTRCOSTDTLS_COSTCENTER_OID ON OBJTREP_DAYATTCNTRCOSTDTLS(COSTCENTER_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_ANOMALYREASONS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_ANOMALYREASONS
  GO

  CREATE TABLE OBJTREP_ANOMALYREASONS
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    TYPE                 INT,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_ANOMALYREASONS
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_CLOCKINGEVENTS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_CLOCKINGEVENTS
  GO

  CREATE TABLE OBJTREP_CLOCKINGEVENTS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DEVICE_OID           BIGINT,
    DTS                  DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_CLOCKINGEVENTS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_CLOCKINGEVENTS_EMPLOYEE_OID ON OBJTREP_CLOCKINGEVENTS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_CLOCKINGEVENTS_DEVICE_OID ON OBJTREP_CLOCKINGEVENTS(DEVICE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_INFOEVENTS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_INFOEVENTS
  GO

  CREATE TABLE OBJTREP_INFOEVENTS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DEVICE_OID           BIGINT,
    DTS                  DATETIME2,
    USRTXT1              VARCHAR(255),
    USRTXT2              VARCHAR(255),
    USRTXT3              VARCHAR(255),
    USRTXT4              VARCHAR(255),
    USRTXT5              VARCHAR(255),
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_INFOEVENTS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_INFOEVENTS_EMPLOYEE_OID ON OBJTREP_INFOEVENTS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_INFOEVENTS_DEVICE_OID ON OBJTREP_INFOEVENTS(DEVICE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_COSTCENTEREVENTS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_COSTCENTEREVENTS
  GO

  CREATE TABLE OBJTREP_COSTCENTEREVENTS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DEVICE_OID           BIGINT,
    COSTCENTER_OID       BIGINT,
    DTS                  DATETIME2,
    USRTXT1              VARCHAR(255),
    USRTXT2              VARCHAR(255),
    USRTXT3              VARCHAR(255),
    USRTXT4              VARCHAR(255),
    USRTXT5              VARCHAR(255),
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_COSTCENTEREVENTS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_COSTCENTEREVENTS_EMPLOYEE_OID ON OBJTREP_COSTCENTEREVENTS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_COSTCENTEREVENTS_DEVICE_OID ON OBJTREP_COSTCENTEREVENTS(DEVICE_OID)
  GO

  CREATE INDEX IOBJTREP_COSTCENTEREVENTS_COSTCENTER_OID ON OBJTREP_COSTCENTEREVENTS(COSTCENTER_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_ACTUAL_ATTENDANCES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_ACTUAL_ATTENDANCES
  GO

  CREATE TABLE OBJTREP_ACTUAL_ATTENDANCES
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    CATEGORY             VARCHAR(64),
    DTSSTART             DATETIME2,
    DTSSTOP              DATETIME2,
    DAY_CODE_OID         BIGINT,
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_ACTUAL_ATTENDANCES
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_ACTUAL_ATTENDANCES_EMPLOYEE_OID ON OBJTREP_ACTUAL_ATTENDANCES(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_ACTUAL_ATTENDANCES_DAY_CODE_OID ON OBJTREP_ACTUAL_ATTENDANCES(DAY_CODE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_ATTENDANCEPERIODS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_ATTENDANCEPERIODS
  GO

  CREATE TABLE OBJTREP_ATTENDANCEPERIODS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    DTSSTART             DATETIME2,
    DTSSTOP              DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_ATTENDANCEPERIODS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_ATTENDANCEPERIODS_EMPLOYEE_OID ON OBJTREP_ATTENDANCEPERIODS(EMPLOYEE_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_BALANCE_COUNTERS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_BALANCE_COUNTERS
  GO

  CREATE TABLE OBJTREP_BALANCE_COUNTERS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    BALANCE_CODE_OID     BIGINT,
    PERIOD_OID           BIGINT,
    START_VALUE          FLOAT,
    END_VALUE            FLOAT,
    PLANNED_VALUE        FLOAT,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_BALANCE_COUNTERS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_BALANCE_COUNTERS_EMPLOYEE_OID ON OBJTREP_BALANCE_COUNTERS(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_BALANCE_COUNTERS_BALANCE_CODE_OID ON OBJTREP_BALANCE_COUNTERS(BALANCE_CODE_OID)
  GO

  CREATE INDEX IOBJTREP_BALANCE_COUNTERS_PERIOD_OID ON OBJTREP_BALANCE_COUNTERS(PERIOD_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('OBJTREP_ANOMALIES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE OBJTREP_ANOMALIES
  GO

  CREATE TABLE OBJTREP_ANOMALIES
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    REASON_OID           BIGINT,
    DESCRIPTION          VARCHAR(255),
    DTS                  DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_OBJTREP_ANOMALIES
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IOBJTREP_ANOMALIES_EMPLOYEE_OID ON OBJTREP_ANOMALIES(EMPLOYEE_OID)
  GO

  CREATE INDEX IOBJTREP_ANOMALIES_REASON_OID ON OBJTREP_ANOMALIES(REASON_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_ACCESS_OPERATIONS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_ACCESS_OPERATIONS
  GO

  CREATE TABLE DCEREPORT_ACCESS_OPERATIONS
  (
    OID                  BIGINT NOT NULL,
    EMPLOYEE_OID         BIGINT,
    ACCESSBADGE_OID      BIGINT,
    DTSSTART             DATETIME2,
    DTSSTOP              DATETIME2,
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNTIL        DATETIME2,
    STATUS               INT,
    ACCESSREADERDEVICE_OID BIGINT,
    ACCESSGATE_OID       BIGINT,
    ACCESSAREA_OID       BIGINT,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_ACCESS_OPERATIONS
    PRIMARY KEY (OID)
  )
  GO

  CREATE INDEX IDCEREPORT_ACCESS_OPERATIONS_EMPLOYEE_OID ON DCEREPORT_ACCESS_OPERATIONS(EMPLOYEE_OID)
  GO

  CREATE INDEX IDCEREPORT_ACCESS_OPERATIONS_ACCESSBADGE_OID ON DCEREPORT_ACCESS_OPERATIONS(ACCESSBADGE_OID)
  GO

  CREATE INDEX IDCEREPORT_ACCESS_OPERATIONS_ACCESSREADERDEVICE_OID ON DCEREPORT_ACCESS_OPERATIONS(ACCESSREADERDEVICE_OID)
  GO

  CREATE INDEX IDCEREPORT_ACCESS_OPERATIONS_ACCESSGATE_OID ON DCEREPORT_ACCESS_OPERATIONS(ACCESSGATE_OID)
  GO

  CREATE INDEX IDCEREPORT_ACCESS_OPERATIONS_ACCESSAREA_OID ON DCEREPORT_ACCESS_OPERATIONS(ACCESSAREA_OID)
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_ACCESS_BADGES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_ACCESS_BADGES
  GO

  CREATE TABLE DCEREPORT_ACCESS_BADGES
  (
    OID                  BIGINT NOT NULL,
    ID                   VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    STATUS               VARCHAR(7),
    DTSSTART             DATETIME2,
    DTSSTOP              DATETIME2,
    DTSVALIDFROM         DATETIME2,
    DTSVALIDUNITL        DATETIME2,
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_ACCESS_BADGES
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_ACCESS_READERDEVICES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_ACCESS_READERDEVICES
  GO

  CREATE TABLE DCEREPORT_ACCESS_READERDEVICES
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    ACCESSTYPE           VARCHAR(3),
    DEVICEADDRESS        VARCHAR(64),
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_ACCESS_READERDEVICES
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_ACCESS_GATES') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_ACCESS_GATES
  GO

  CREATE TABLE DCEREPORT_ACCESS_GATES
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_ACCESS_GATES
    PRIMARY KEY (OID)
  )
  GO

  IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DCEREPORT_ACCESS_AREAS') AND OBJECTPROPERTY(ID, 'IsUserTable') = 1)
  DROP TABLE DCEREPORT_ACCESS_AREAS
  GO

  CREATE TABLE DCEREPORT_ACCESS_AREAS
  (
    OID                  BIGINT NOT NULL,
    NAME                 VARCHAR(64),
    DESCRIPTION          VARCHAR(255),
    EVACUATIONZONE       VARCHAR(32),
    DTSUPDATE            DATETIME2,
    CONSTRAINT PK_DCEREPORT_ACCESS_AREAS
    PRIMARY KEY (OID)
  )
  GO

