IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPACITYALLOCATIONS_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPACITYALLOCATIONS'))  ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_EMPLOYEE_OID
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS NOCHECK CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPACITYALLOCATIONS_PLANNINGCELL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPACITYALLOCATIONS'))  ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_PLANNINGCELL_OID
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_PLANNINGCELL_OID  FOREIGN KEY(PLANNINGCELL_OID)  REFERENCES DCEREPORT_PLANNINGCELLS(OID)
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS NOCHECK CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_PLANNINGCELL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPACITYALLOCATIONS_SHIFT_TYPE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPACITYALLOCATIONS'))  ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SHIFT_TYPE_OID
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SHIFT_TYPE_OID  FOREIGN KEY(SHIFT_TYPE_OID)  REFERENCES DCEREPORT_SHIFT_TYPES(OID)
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS NOCHECK CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SHIFT_TYPE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPACITYALLOCATIONS_SKILL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPACITYALLOCATIONS'))  ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS DROP CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SKILL_OID
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SKILL_OID  FOREIGN KEY(SKILL_OID)  REFERENCES DCEREPORT_SKILLS(OID)
ALTER TABLE DCEREPORT_CAPACITYALLOCATIONS NOCHECK CONSTRAINT FK_DCEREPORT_CAPACITYALLOCATIONS_SKILL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPALLOC_ANOMALIES_CAP_ANOMALY_REASON_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPALLOC_ANOMALIES'))  ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAP_ANOMALY_REASON_OID
ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAP_ANOMALY_REASON_OID  FOREIGN KEY(CAP_ANOMALY_REASON_OID)  REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID)
ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAP_ANOMALY_REASON_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPALLOC_ANOMALIES_CAPACITY_ALLOCATION_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPALLOC_ANOMALIES'))  ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAPACITY_ALLOCATION_OID
ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAPACITY_ALLOCATION_OID  FOREIGN KEY(CAPACITY_ALLOCATION_OID)  REFERENCES DCEREPORT_CAPACITYALLOCATIONS(OID)
ALTER TABLE DCEREPORT_CAPALLOC_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_CAPALLOC_ANOMALIES_CAPACITY_ALLOCATION_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFTCAPREQUIREMENTS_PLANNINGCELL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFTCAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_PLANNINGCELL_OID
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_PLANNINGCELL_OID  FOREIGN KEY(PLANNINGCELL_OID)  REFERENCES DCEREPORT_PLANNINGCELLS(OID)
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_PLANNINGCELL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SHIFT_TYPE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFTCAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SHIFT_TYPE_OID
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SHIFT_TYPE_OID  FOREIGN KEY(SHIFT_TYPE_OID)  REFERENCES DCEREPORT_SHIFT_TYPES(OID)
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SHIFT_TYPE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SKILL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFTCAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SKILL_OID
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SKILL_OID  FOREIGN KEY(SKILL_OID)  REFERENCES DCEREPORT_SKILLS(OID)
ALTER TABLE DCEREPORT_SHIFTCAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_SHIFTCAPREQUIREMENTS_SKILL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_CAP_ANOMALY_REASON_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHFTCAPREQ_ANOMALIES'))  ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_CAP_ANOMALY_REASON_OID
ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_CAP_ANOMALY_REASON_OID  FOREIGN KEY(CAP_ANOMALY_REASON_OID)  REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID)
ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_CAP_ANOMALY_REASON_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_SHIFT_CAPREQUIREMENT_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHFTCAPREQ_ANOMALIES'))  ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_SHIFT_CAPREQUIREMENT_OID
ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_SHIFT_CAPREQUIREMENT_OID  FOREIGN KEY(SHIFT_CAPREQUIREMENT_OID)  REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID)
ALTER TABLE DCEREPORT_SHFTCAPREQ_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_SHFTCAPREQ_ANOMALIES_SHIFT_CAPREQUIREMENT_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAPREQ_LINK_CAPACITYREQUIREMENT_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAPREQ_LINK'))  ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_CAPACITYREQUIREMENT_OID
ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_CAPACITYREQUIREMENT_OID  FOREIGN KEY(CAPACITYREQUIREMENT_OID)  REFERENCES DCEREPORT_CAPREQUIREMENTS(OID)
ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_CAPACITYREQUIREMENT_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAPREQ_LINK_SHIFT_CAPREQUIREMENT_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAPREQ_LINK'))  ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_SHIFT_CAPREQUIREMENT_OID
ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_SHIFT_CAPREQUIREMENT_OID  FOREIGN KEY(SHIFT_CAPREQUIREMENT_OID)  REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID)
ALTER TABLE DCEREPORT_SHIFT_CAPREQ_LINK NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAPREQ_LINK_SHIFT_CAPREQUIREMENT_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPREQUIREMENTS_PLANNINGCELL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PLANNINGCELL_OID
ALTER TABLE DCEREPORT_CAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PLANNINGCELL_OID  FOREIGN KEY(PLANNINGCELL_OID)  REFERENCES DCEREPORT_PLANNINGCELLS(OID)
ALTER TABLE DCEREPORT_CAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PLANNINGCELL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPREQUIREMENTS_PROCESSRESOURCE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PROCESSRESOURCE_OID
ALTER TABLE DCEREPORT_CAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PROCESSRESOURCE_OID  FOREIGN KEY(PROCESSRESOURCE_OID)  REFERENCES DCEREPORT_PROCESSRESOURCES(OID)
ALTER TABLE DCEREPORT_CAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_PROCESSRESOURCE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPREQUIREMENTS_SKILL_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPREQUIREMENTS'))  ALTER TABLE DCEREPORT_CAPREQUIREMENTS DROP CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_SKILL_OID
ALTER TABLE DCEREPORT_CAPREQUIREMENTS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_SKILL_OID  FOREIGN KEY(SKILL_OID)  REFERENCES DCEREPORT_SKILLS(OID)
ALTER TABLE DCEREPORT_CAPREQUIREMENTS NOCHECK CONSTRAINT FK_DCEREPORT_CAPREQUIREMENTS_SKILL_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAPACITIES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAPACITIES'))  ALTER TABLE DCEREPORT_SHIFT_CAPACITIES DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_EMPLOYEE_OID
ALTER TABLE DCEREPORT_SHIFT_CAPACITIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_SHIFT_CAPACITIES NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAPACITIES_SHIFT_TYPE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAPACITIES'))  ALTER TABLE DCEREPORT_SHIFT_CAPACITIES DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_SHIFT_TYPE_OID
ALTER TABLE DCEREPORT_SHIFT_CAPACITIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_SHIFT_TYPE_OID  FOREIGN KEY(SHIFT_TYPE_OID)  REFERENCES DCEREPORT_SHIFT_TYPES(OID)
ALTER TABLE DCEREPORT_SHIFT_CAPACITIES NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAPACITIES_SHIFT_TYPE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAP_ANOMALIES_CAP_ANOMALY_REASON_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAP_ANOMALIES'))  ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_CAP_ANOMALY_REASON_OID
ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_CAP_ANOMALY_REASON_OID  FOREIGN KEY(CAP_ANOMALY_REASON_OID)  REFERENCES DCEREPORT_CAP_ANOMALY_REASONS(OID)
ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_CAP_ANOMALY_REASON_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAP_ANOMALIES_SHIFT_CAPREQUIREMENT_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAP_ANOMALIES'))  ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_SHIFT_CAPREQUIREMENT_OID
ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_SHIFT_CAPREQUIREMENT_OID  FOREIGN KEY(SHIFT_CAPREQUIREMENT_OID)  REFERENCES DCEREPORT_SHIFTCAPREQUIREMENTS(OID)
ALTER TABLE DCEREPORT_SHIFT_CAP_ANOMALIES NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAP_ANOMALIES_SHIFT_CAPREQUIREMENT_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAP_LINK_CAPACITY_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAP_LINK'))  ALTER TABLE DCEREPORT_SHIFT_CAP_LINK DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_CAPACITY_OID
ALTER TABLE DCEREPORT_SHIFT_CAP_LINK WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_CAPACITY_OID  FOREIGN KEY(CAPACITY_OID)  REFERENCES DCEREPORT_CAPACITIES(OID)
ALTER TABLE DCEREPORT_SHIFT_CAP_LINK NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_CAPACITY_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_SHIFT_CAP_LINK_SHIFT_CAPACITY_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_SHIFT_CAP_LINK'))  ALTER TABLE DCEREPORT_SHIFT_CAP_LINK DROP CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_SHIFT_CAPACITY_OID
ALTER TABLE DCEREPORT_SHIFT_CAP_LINK WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_SHIFT_CAPACITY_OID  FOREIGN KEY(SHIFT_CAPACITY_OID)  REFERENCES DCEREPORT_SHIFT_CAPACITIES(OID)
ALTER TABLE DCEREPORT_SHIFT_CAP_LINK NOCHECK CONSTRAINT FK_DCEREPORT_SHIFT_CAP_LINK_SHIFT_CAPACITY_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_CAPACITIES_EMPLOYEE_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_CAPACITIES'))  ALTER TABLE DCEREPORT_CAPACITIES DROP CONSTRAINT FK_DCEREPORT_CAPACITIES_EMPLOYEE_OID
ALTER TABLE DCEREPORT_CAPACITIES WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_CAPACITIES_EMPLOYEE_OID  FOREIGN KEY(EMPLOYEE_OID)  REFERENCES DCEREPORT_EMPLOYEES(OID)
ALTER TABLE DCEREPORT_CAPACITIES NOCHECK CONSTRAINT FK_DCEREPORT_CAPACITIES_EMPLOYEE_OID

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_DCEREPORT_PLANNINGCELLS_COSTCENTER_OID') AND parent_object_id = OBJECT_ID(N'DCEREPORT_PLANNINGCELLS'))  ALTER TABLE DCEREPORT_PLANNINGCELLS DROP CONSTRAINT FK_DCEREPORT_PLANNINGCELLS_COSTCENTER_OID
ALTER TABLE DCEREPORT_PLANNINGCELLS WITH NOCHECK  ADD CONSTRAINT FK_DCEREPORT_PLANNINGCELLS_COSTCENTER_OID  FOREIGN KEY(COSTCENTER_OID)  REFERENCES DCEREPORT_COSTCENTERS(OID)
ALTER TABLE DCEREPORT_PLANNINGCELLS NOCHECK CONSTRAINT FK_DCEREPORT_PLANNINGCELLS_COSTCENTER_OID

