------------------------------------------------------------------------------------------------------------------------------------------
--                                                   DATABASE TABLE UPDATE SCRIPT (ORACLE)                                              --
------------------------------------------------------------------------------------------------------------------------------------------
-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCEOID column to PROCESSUNITOID
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJT_PROCESSAGGREGATION'
    AND COLUMN_NAME = 'PROCESSUNITOID';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJT_PROCESSAGGREGATION RENAME COLUMN PROCESSRESOURCEOID TO PROCESSUNITOID';
  END IF;
END;
/

-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATE column to PROCESSUNITSTATE
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJT_PROCESSAGGREGATION'
    AND COLUMN_NAME = 'PROCESSUNITSTATE';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJT_PROCESSAGGREGATION RENAME COLUMN PROCESSRESOURCESTATE TO PROCESSUNITSTATE';
  END IF;
END;
/

-- Rename OBJT_PROCESSAGGREGATION.PROCESSRESOURCESTATEDURATION column to PROCESSUNITSTATEDURATION
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJT_PROCESSAGGREGATION'
    AND COLUMN_NAME = 'PROCESSUNITSTATEDURATION';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJT_PROCESSAGGREGATION RENAME COLUMN PROCESSRESOURCESTATEDURATION TO PROCESSUNITSTATEDURATION';
  END IF;
END;
/


-- Rename OBJT_UOMCONVERSION.OFFSET column to OFFSETVALUE
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJT_UOMCONVERSION'
    AND COLUMN_NAME = 'OFFSETVALUE';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJT_UOMCONVERSION RENAME COLUMN OFFSET TO OFFSETVALUE';
  END IF;
END;
/


-- Rename OBJT_ATTENDANCEPATTERNLINK.OFFSET column to OFFSETVALUE
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJT_ATTENDANCEPATTERNLINK'
    AND COLUMN_NAME = 'OFFSETVALUE';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJT_ATTENDANCEPATTERNLINK RENAME COLUMN OFFSET TO OFFSETVALUE';
  END IF;
END;
/


-- Rename OBJTBU_BALANCINGCONFIG.OFFSET column to OFFSETVALUE
DECLARE
  COUNT_OBJECT INTEGER;

BEGIN
  SELECT COUNT(*) INTO COUNT_OBJECT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'OBJTBU_BALANCINGCONFIG'
    AND COLUMN_NAME = 'OFFSETVALUE';

  IF COUNT_OBJECT = 0
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OBJTBU_BALANCINGCONFIG RENAME COLUMN OFFSET TO OFFSETVALUE';
  END IF;
END;
/

