on:
  push:
    branches:
      - "feature/*"
      - "hotfix/*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Merge branch
        uses: Germanedge/github-auto-branch-merge@main
        with:
          target_branch: 'dev'
          source_branch: ${{ env.GITHUB_REF_NAME }}
          commit_message: "[Automated] Merge branch '${{env.GITHUB_REF_NAME}}' into dev"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Send slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: git-action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: 'job status: ${{ job.status }}'
